### ISSUE TITLE
DefaultJwtParser does not use UTC

### ISSUE THREAD

**Issue by spidiTsakirales** [jwtk/jjwt#107]
Hello, 

When generating a jwt, as part of the claims we add an expiration of UTC.now+30 minutes.
When  parsing back the jwt the DefaultJwtParser the dates are checked with the local timezone of the machine .

 Exception msg io.jsonwebtoken.ExpiredJwtException: JWT expired at 2016-03-30T11:37:33+0100. Current time: 2016-03-30T12:07:34+0100

            Date now = null;
            SimpleDateFormat sdf;

            //https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-30#section-4.1.4
            //token MUST NOT be accepted on or after any specified exp time:
            Date exp = claims.getExpiration();
            if (exp != null) {

                now = new Date();

                if (now.equals(exp) || now.after(exp)) {
                    sdf = new SimpleDateFormat(ISO_8601_FORMAT);
                    String expVal = sdf.format(exp);
                    String nowVal = sdf.format(now);

                    String msg = "JWT expired at " + expVal + ". Current time: " + nowVal;
                    throw new ExpiredJwtException(header, claims, msg);
                }
            }
Are there any plans to change that in future?

**Comment by lhazlewood** [comment]
The date checks are valid - `java.util.Date` is timezone independent (per the Javadoc).

What you are seeing is a bug that the _text_ in the exception message (the printed date) is reflecting the local timezone, and yes, that string logic should probably be UTC-based by default.

We'll use this issue to track the fix - thanks for submitting it!

**Comment by spidiTsakirales** [comment]
Thanks for getting back. Dates are always fun! 
Per Javadoc indeed only date.toString() is in localDateTime which caused confusion here. We actually saw a use case where one server would issue a jjwt token with expiry set to 30 min, another server would parse it and as servers were in different timezones, parsing would fail.

We use jdk 1.8 ZonedDateTime which we convert to Java.util.Date.
I think there is something in the way we do conversion 

Just out of curiosity do you have any plans of updating the jdk version to 1.8 at some point?
In that case ZonedDateTime may prove handy in this scenario, where ZonedDateTime.isAfter() could be utilized

**Comment by lhazlewood** [comment]
We will support 1.8 at some point, but there are still many on 1.7, so it probably won't be until next year I would guess.
