### ISSUE TITLE
NoClassDefFoundError: com.google.android.gms.R$string in android  project

### ISSUE THREAD

**Issue by QiuMing** [jwtk/jjwt#111]
Hi, I am trying to use jjwt  for my android project,but while I add 
` compile 'io.jsonwebtoken:jjwt:0.6.0'` in  my build.gradle profile, I  could not start my app   and  get exception like this
` Could not find class 'android.app.AppOpsManager', referenced from method com.google.android.gms.common.zze.zzb
04-03 23:48:06.681 12759-12759/? E/AndroidRuntime: FATAL EXCEPTION: main
04-03 23:48:06.681 12759-12759/? E/AndroidRuntime: java.lang.NoClassDefFoundError: com.google.android.gms.R$string`

If  I remove jjwt,it will work fine again.
It  seems is my project problem ,but I don't know  how to resolve it.Can you give me some hint?
My project is  on https://github.com/QiuMing/ChenXi . Hope you can give me some tips.Thanks very much

**Comment by lhazlewood** [comment]
It appears that you need to enable Multidex with Gradle:

http://stackoverflow.com/questions/34831445/java-lang-noclassdeffounderror-com-google-android-gms-rstring-error-after-ad

**Comment by QiuMing** [comment]
Thank you  very much.That is I  want  to find and it solve  my problem  at last.Thanks
