### ISSUE TITLE
Documentation on use of Public/Private Keys

### ISSUE THREAD

**Issue by bearrito** [jwtk/jjwt#112]
Any docs or even links to relevent tests on using Public/Private Keys would be useful.

I have seen and read : https://github.com/jwtk/jjwt/issues/25 but could not figure out how to actually use the keypair.

I'm attempting to do what I think should be the obvious thing but receive

```
java.lang.IllegalArgumentException: MAC signatures must be computed and verified using a SecretKey.  The specified key of type sun.security.rsa.RSAPrivateCrtKeyImpl is not a SecretKey.

```

**Comment by GuillaumeUnice** [comment]
+1

**Comment by lhazlewood** [comment]
Hiya,

We want to document this properly, but in the mean time, here's a minor example (excuse the Groovy - it was adapted from a test class):

```groovy
KeyPair kp = RsaProvider.generateKeyPair(keySize)
PublicKey publicKey = kp.getPublic();
PrivateKey privateKey = kp.getPrivate();

def claims = [iss: 'joe']

String jws = Jwts.builder().setClaims(claims).signWith(alg, privateKey).compact();

def token = Jwts.parser().setSigningKey(publicKey).parseClaimsJws(jws);
```

More tests are in https://github.com/jwtk/jjwt/blob/master/src/test/groovy/io/jsonwebtoken/JwtsTest.groovy

HTH!

**Comment by shumy** [comment]
Most naturally we only have the public key from an external IdP.
So not helping most of us!
How do I use google public keys?

https://www.googleapis.com/oauth2/v1/certs
or
https://www.googleapis.com/oauth2/v3/certs

**Comment by djKianoosh** [comment]
@shumy let's assume you have a public key like the one you can find on https://jwt.io/ on their debugger example (remember to select RS256 from the dropdown at the top).
```
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDdlatRjRjogo3WojgGHFHYLugdUWAY9iR3fy4arWNA1KoS8kVw33cJibXr8bvwUAUparCwlvdbH6dvEOfou0/gCFQsHUfQrSDv+MuSUMAe8jzKE4qW+jK+xQU9a03GUnKHkkle+Q0pX/g6jXZ7r1/xAK5Do2kQ+X5xK9cipRgEKwIDAQAB
```
and also the encoded payload they have on the left (you can play with the payload data in json on the right), like this:
```
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImFkZGl0aW9uYWwiOnsibW9yZSI6ImRhdGEifX0.uC4txszjuKqXlAlBbcNJHqX2Un3-JGp_AwKabBTnK4Al6ZcbjgBnOzfHyfTRxfGuswO8lJ4iaZtRdrdHsafEZZSKmNCmcPaWSkGJgvlCs8HCp3EbzIAd5RvNAlF-bTS9Igk3d4NdxSDsliv9s9SIlUrt2At6kKwjL9CzibC2_u8
```

With just the public key, you can validate the encoded payload like this:
```
import io.jsonwebtoken.*
import java.security.*
import java.security.spec.*

def publicKeyString = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDdlatRjRjogo3WojgGHFHYLugdUWAY9iR3fy4arWNA1KoS8kVw33cJibXr8bvwUAUparCwlvdbH6dvEOfou0/gCFQsHUfQrSDv+MuSUMAe8jzKE4qW+jK+xQU9a03GUnKHkkle+Q0pX/g6jXZ7r1/xAK5Do2kQ+X5xK9cipRgEKwIDAQAB"
def jwsEncodedPayload = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImFkZGl0aW9uYWwiOnsibW9yZSI6ImRhdGEifX0.uC4txszjuKqXlAlBbcNJHqX2Un3-JGp_AwKabBTnK4Al6ZcbjgBnOzfHyfTRxfGuswO8lJ4iaZtRdrdHsafEZZSKmNCmcPaWSkGJgvlCs8HCp3EbzIAd5RvNAlF-bTS9Igk3d4NdxSDsliv9s9SIlUrt2At6kKwjL9CzibC2_u8"

KeyFactory kf = KeyFactory.getInstance("RSA");
byte[] byteKey = Base64.getDecoder().decode(publicKeyString)
X509EncodedKeySpec X509publicKey = new X509EncodedKeySpec(byteKey);
PublicKey pub = kf.generatePublic(X509publicKey)

Jws token = Jwts.parser().setSigningKey(pub).parseClaimsJws(jwsEncodedPayload);

```

The output of the last parse is:
```
Result: header={alg=RS256, typ=JWT},body={sub=1234567890, name=John Doe, admin=true, additional={more=data}},signature=uC4txszjuKqXlAlBbcNJHqX2Un3-JGp_AwKabBTnK4Al6ZcbjgBnOzfHyfTRxfGuswO8lJ4iaZtRdrdHsafEZZSKmNCmcPaWSkGJgvlCs8HCp3EbzIAd5RvNAlF-bTS9Igk3d4NdxSDsliv9s9SIlUrt2At6kKwjL9CzibC2_u8
```

And `token.body` is `['sub':'1234567890', 'name':'John Doe', 'admin':true, 'additional':['more':'data']]`

**Comment by pme123** [comment]
@lhazlewood 

Even with your example I get the IllegalArgumentException described above:
`java.lang.IllegalArgumentException: MAC signatures must be computed and verified using a SecretKey.  The specified key of type sun.security.rsa.RSAPrivateCrtKeyImpl is not a SecretKey.
`

**Comment by ItsFunny** [comment]
can i encrypt by publickey and parse by private key ?

**Comment by lhazlewood** [comment]
@ItsFunny no, you cannot encrypt or create signatures with the public key.  Doing so would completely violate the security model of such keys: since anyone can get access to a public key, then anyone would be able to 'impersonate' you by simply using your public key if this were possible.

**Comment by lhazlewood** [comment]
Closing this as per the 0.10.0 release, signatures with both Secret and Public/Private keypairs are documented in the Readme.
