### ISSUE TITLE
OSGi bundle should not require android package

### ISSUE THREAD

**Issue by BryanHunt** [jwtk/jjwt#116]
The OSGi bundle imports package android.util which doesn't work in a pure Java OSGi environment.

Import-Package
  android.util                           
  com.fasterxml.jackson.core             {version=[2.4,3)}
  com.fasterxml.jackson.databind         {version=[2.4,3)}
  io.jsonwebtoken.lang                   
  javax.crypto                           
  javax.crypto.spec                      
  javax.xml.bind                         
  org.bouncycastle.jce                   {version=[1.51,2), resolution:=optional}
  org.bouncycastle.jce.spec              {version=[1.51,2), resolution:=optional}

**Comment by lhazlewood** [comment]
Hiya!

Can you please open a pull request?  No one on the JJWT team uses OSGi and we don't have an interest in maintaining its metadata ourselves, so if it should be supported in the future, we pretty much have to rely on Pull Requests from the JJWT community.

**Comment by BryanHunt** [comment]
I just looked at this some more, and it appears the pom file has the package marked as optional, but that change was after the 0.6.0 release.  I think it is a simple matter of cutting a release.

**Comment by lhazlewood** [comment]
closing as resolved since this will be in the next release.  If there is work to do beyond cutting the release, please feel free to re-open.

**Comment by cpilsworth** [comment]
Is there a schedule in mind for the 0.7 release?  The required `android.util` dependency of 0.6 is stopping me deploying this as a bundle in Apache Felix.

Many thanks, Chris

**Comment by BryanHunt** [comment]
@cpilsworth The workaround is to un-jar the bundle, remove android.util from the manifest (or make it optional) and re-jar the bundle

**Comment by lhazlewood** [comment]
`SpringOne` is this coming week, so we'll probably be able to release it asap after then.

**Comment by cpilsworth** [comment]
Thanks for the update, good to know.  Great library btw, very useful!

**Comment by cpilsworth** [comment]
I [wrapped the package](https://gist.github.com/cpilsworth/f6fc4d7f4970af0a93c877ec995231dc) in the meantime - rewriting the imports/exports and adding a no-android classifier.
