### ISSUE TITLE
Security vulnerability in JWT parser

### ISSUE THREAD

**Issue by laurensb** [jwtk/jjwt#119]
Hi,

I believe the security vulnerability described here:

https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

also effects JJWT.

One possible way of handling this would be to change the signature of JwtParser::setSigningKey to also include a parameter of type SignatureAlgorithm. Or at least to include a parameter indicating whether a secret key (e.g. HS256) or a public/private key (e.g. RS256) is used.

This change would break backwards compatibility however that is the whole point, this will force users of JJWT to resolve the vulnerability.

An alternative (e.g. adding a requireAlgorithm to JwtParser) is NOT secure because it requires explicit user action to prevent the vulnerability from occurring.

**Comment by nbarbettini** [comment]
@laurensb AFAIK, this has already been addressed here: https://github.com/jwtk/jjwt/issues/20

**Comment by laurensb** [comment]
@nbarbettini Thanks for pointing out that issue, I searched for something similar, but obviously I didn't search well enough.
Looking at the code I now realize that the RSA and ECDSA validators check whether the key is of the correct type, so the issue can indeed not occur.
