### ISSUE TITLE
How to use in adt of  Eclipse ?

### ISSUE THREAD

**Issue by sunfeng90** [jwtk/jjwt#126]
There are any jars to help the user of eclipse to realise the JWT?

**Comment by lookuptable** [comment]
Not sure what you're asking exactly.

but if you just want to import this project into eclipse, you can run `mvn eclipse:eclipse` and then import

**Comment by lookuptable** [comment]
Are you using any build tool like maven or gradle?

**Comment by sunfeng90** [comment]
No,I using adt and eclipse.

**Comment by lhazlewood** [comment]
Pleas use maven or gradle.  The JJWT project does not have plans to support IDE-specific artifacts.
