### ISSUE TITLE
Signature verification key accepted but they are not same

### ISSUE THREAD

**Issue by CodeMax** [jwtk/jjwt#128]
When i create a Token which has the Password "abc123" with the following lines:

`byte[] apiKeySecretBytes = DatatypeConverter.parseBase64Binary("abc123");`
`Key signingKey = new SecretKeySpec(apiKeySecretBytes, signatureAlgorithm.getJcaName());`
`JwtBuilder builder = Jwts.builder().signWith(SignatureAlgorithm.HS512, signingKey)`

And then parse this Token by using the Password "abc1234"

`Claims claims = Jwts.parser().setSigningKey(DatatypeConverter.parseBase64Binary("abc1234"))
									 .parseClaimsJws(jwt).getBody();`

...then it is also accepted.
Is that a correct behavior and i am just missing something? (Version 0.6.0)

**Comment by lhazlewood** [comment]
"abc123" is not base64 encoded text - you can't use `parseBase64Binary`.

JWS signatures should always be computed and verified by a secure-random key of sufficient length for the algorithm you are using.  Normal 'passwords' (like what people use for username logins) are usually always a bad idea for creating signatures - the cryptographic properties (entropy, length) are very different.

See JJWT's `MacProvider.generateKey` methods to generate a valid signing key.

**Comment by lhazlewood** [comment]
oh, but other than key generation, yes, your builder/parser calls look fine.  This is pretty much the same scenario shown in the Readme's [Usage](https://github.com/jwtk/jjwt#usage) section.  Cheers!

**Comment by lhazlewood** [comment]
Closing as there is no work to be done for JJWT.  For general questions, please use StackOverflow and use the `jjwt` tag.  Thanks!
