### ISSUE TITLE
Verify signature without based64 encoded

### ISSUE THREAD

**Issue by miladsalehi** [jwtk/jjwt#138]
Hi,

When i input my signed json in jwt.io debugger must check secret base64 encoded to verify signature.
How can i verify signature without based64 encoded?

Thanks.

**Comment by lhazlewood** [comment]
Hi @miladsalehi,

Can you please ask this question on StackOverflow.com and use the `jjwt` tag?  GitHub issues are only used to track work that must be done in the project.
