### ISSUE TITLE
Different secrets allow same token

### ISSUE THREAD

**Issue by Rhaea** [jwtk/jjwt#144]
Using the secret:
2vwvM326yzyixttGADWoq4rw6iVfj6UQzPmkgKfRY6tPv9M3sC
on one server, and the secret
2vwvM326yzyixttGADWoq4rw6iVfj6UQzPmkgKfRY6tPv9M3sB
on the other will create a situation where both servers accept tokens comming from one another. 

I can only think of one reason, namely that parsing the secret will ignore certain bytes if the length is not dividable by some number or similar. 
This should of course not happen, and is a security risk. I hope you can verify the issue, and easily fix it. 

Thanks for an otherwise well build and easy to use framework!

**Comment by lhazlewood** [comment]
It is not a security risk.  From the sound of your issue, I'd assume you're using an HMAC SHA hashing algorithm, which truncates keys if the key length is greater than the algorithm block size.

Please either ask questions or do your research first before claiming something is a security risk, as doing so could cause worry for others following the issue tracker when no reason to worry exists.

**Comment by lhazlewood** [comment]
I just read this message much later and it came across as short/terse and confrontational - that was not my desire! I'm sorry about that!  In any event, I hope all is well and you found the answer you needed )
