### ISSUE TITLE
Update Method Signatures from the completed JWT spec

### ISSUE THREAD

**Issue by edjiang** [jwtk/jjwt#147]
Talking with @lhazlewood today:

JJWT was written against the draft JWT spec, and so there's some forms of terminology that are now "off". For instance, in JJWT, a JWT and JWS are different things. In the final version of the spec, what we referred to as "JWT" is now a special case of a JWS. 

Also, a JWT is only a "compact" JWS or JWE, although a JWS can have multiple representations. 

We should review the spec to make sure that we match the naming of concepts in the spec, so it makes sense to all end users. 

https://tools.ietf.org/html/rfc7519

**Comment by hdost** [comment]
JWS - https://tools.ietf.org/html/rfc7515
JWE - https://tools.ietf.org/html/rfc7516

**Comment by lhazlewood** [comment]
The `jwe` branch merge among other changes has used/fixed to reflect the finalized RFC language and concepts.  0.12.0 release will contain these changes.
