### ISSUE TITLE
ECDSA curve misnamed in README

### ISSUE THREAD

**Issue by mike9005** [jwtk/jjwt#149]
In the [Supported Features section](https://github.com/jwtk/jjwt/blob/master/README.md#specification-compliant) of the README, the NIST `P-521` curve is misnamed as `P-512` in the `ES512` JWS algorithm description.

Reference: the [RFC on ECC in TLS](https://tools.ietf.org/html/rfc4492#appendix-A).

**Comment by lhazlewood** [comment]
Can you please submit a pull request?

**Comment by mike9005** [comment]
I would but don't think I have access rights?

**Comment by lhazlewood** [comment]
You fork the repo into your own github account, create a branch there, and then submit a pull request from your fork/branch to this repo.  Here's a helpful link:  https://help.github.com/articles/using-pull-requests/

HTH!
