### ISSUE TITLE
JWT token has an invalid signature

### ISSUE THREAD

**Issue by kyeljmd** [jwtk/jjwt#152]
I'm testing the jjwt for my token generation.  I am validating the created tokens through the debugger on  jwt.io.

Here's how I generate the token.

        long nowMillis = System.currentTimeMillis();
        long expMillis = nowMillis + (ONE_MINUTE_IN_MILLIS * TOKEN_DURATION_IN_MIN);

        return  Jwts
                .builder()
                .setId("01")
                .setIssuedAt(new Date(nowMillis))
                .setHeaderParam("typ","JWT")
                .setSubject(userName)
                .setIssuer(issuer)
                .setExpiration(new Date(expMillis))
                .signWith(signatureAlgorithm, key).compact();

    `
https://jwt.io/#debugger?&id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIwMSIsImlhdCI6MTQ3MTE0NzU0MSwic3ViIjoia2RhdmlkIiwiaXNzIjoiYXV0aC1zZXJ2ZXIiLCJleHAiOjE0NzExNDkzNDF9.Sv4KN0HujD1ZDE9wxZ_AvmD26-m43xWesirqWwEXg2Q

When I paste the jwt token  on the jwt.io jwt token debugger it results to an invalid signature. what am I missing?

**Comment by kyeljmd** [comment]
This can be also seen on [Stackoverflow](http://stackoverflow.com/questions/38939056/jjwt-generated-token-has-an-invalid-signature)

**Comment by lhazlewood** [comment]
Hi @kyeljmd!  Please do not cross-post :) GitHub issues are for issues and StackOverflow is for questions :)

I've answered your question at SO, so I'll close this issue.  Cheers!
