### ISSUE TITLE
NoClassDefFoundError on jboss

### ISSUE THREAD

**Issue by nejads** [jwtk/jjwt#153]
Hi ! 
I am trying to get started with jjwt on wildfly10.0 and Resteasy.
The application deploy on web server perfectly but Resteasy can not find Macprovider class in runtime. 

I got this error: 
**org.jboss.resteasy.spi.UnhandledException: java.lang.NoClassDefFoundError: io/jsonwebtoken/impl/crypto/MacProvider**

My maven configuration is as following: 
`<dependencies>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt</artifactId>
            <version>0.6.0</version>
        </dependency>
</dependencies>`

But I've also provided and tested "compile scope" but still same problem. Could you help me and describe what is going wrong ?

**Comment by lhazlewood** [comment]
That should be all that is required to ensure the class is in your classpath.  Since the JJWT authors don't use JBoss, please provide a test case/project that re-creates the issue - there's nothing we can do without that.

**Comment by nejads** [comment]
Your suggestion has solved my problem ! 
I started a new project with the default values in the build section in POM.XML file and surprisingly JJWT worked like a charm. 
Specifically, The project with a custom <finalName> tag in the build configuration doesn't work and without this tag works.

**Comment by lhazlewood** [comment]
I'm glad to hear it worked out for you! 👍

**Comment by ahmeeeeeeed** [comment]
same problem if you have fixed it can you tell me how
