### ISSUE TITLE
UTF-8 encoding

### ISSUE THREAD

**Issue by DaspawnW** [jwtk/jjwt#154]
We send in the JWToken firstname and lastname of the user. The lastname contains umlauts like "ö" or "ü". I think the current implementation of the JWToken only implements US-ASCII, so the returned value is unreadable.

**Comment by eric-taix** [comment]
I wrote a simple unit test which create a token and parse it (the subject contains "ö") and the result is just fine !

`String token = factory.createToken("etaixö", new DeviceTest(true, false, false), null);
JwtToken jwtToken = factory.parseToken(token);
assertEquals("etaixö", jwtToken.getUsername());
`

Note: the factory and JwtToken are convenient classes for my application.

**Comment by DaspawnW** [comment]
ok, thank you so i'll have a look at my code ;-)

**Comment by lhazlewood** [comment]
Closing due to inability to recreate.  Please feel free to re-open this issue and provide a test case that demonstrates the problem and we'll be happy to take a look and/or fix anything if necessary.
