### ISSUE TITLE
how to get the Map from claims during parsing?

### ISSUE THREAD

**Issue by sridhar1982** [jwtk/jjwt#155]
I have set-up custom claims as map during jwt generation. when decoding jwt, I want to retrieve the map.

I am trying to do this;

```
 Jws<Claims> jwsClaims = Jwts.parser().setSigningKey(secretKey).parseClaimsJws(token);
 Claims claims = jwsClaims.getBody();
```

how to get `Map<String,Object>` from claims?

This is how I set custom claims

```
Jwts.builder()
                .setClaims(getMapFromResponseObject(myObj))
                .setIssuedAt(now)
                .setExpiration(expiration)
                .setIssuer(ISSUER)
                .signWith(SignatureAlgorithm.HS512, secretKey)
                .compact();


private Map<String,Object> getMapFromResponseObject(MyObject myObj){
        ObjectMapper m = new ObjectMapper();
        Map<String,Object> props = m.convertValue(myObj, Map.class);
        return props;
    }
```

**Comment by eric-taix** [comment]
Claims implements Map<String, Object> with convenient methods for registered claims. Registered claims are stored into this map (ie "iss" -> "http://myapp.com", "sub" -> "me").

So just retrieve claims from body and you are done !
`Claims claims = Jwts.parser().setSigningKey(secret).parseClaimsJws(token).getBody();
claims.get("whatyouwant");`

**Comment by sridhar1982** [comment]
that is still looking for each k-v pair I put as map. I want to retrieve entire map, rather than individual keys. when `.setClaims(getMapFromResponseObject(myObj))`, I set a Map collection and I want to retrieve the same collection, not individual key-value pairs

**Comment by lhazlewood** [comment]
I don't understand the question.  The `Claims` object *is* the entire claims map:

    Map<String,Object> map = (Map<String,Object>)claims;

Does this make sense?  If not, could you provide a small code snippet that shows what you would like to happen?

**Comment by sridhar1982** [comment]
Just as I cited above.

```
Map<String,Person> map = new HasMap<>();
map.put("hello", new Person("hello"));
map.put("world", new Person("world");

Jwts.builder()
                .setClaims(map)
                .setIssuedAt(now)
                .setExpiration(expiration)
                .setIssuer(ISSUER)
                .signWith(SignatureAlgorithm.HS512, secretKey)
                .compact();
```

now when I parse, I would like to get back the map which i set as claims
i.e  `Map<String,String> map = (Map<String,String>) claims;`

The claims by itself contains expiration, iss, subject etc which I do not want. Just the map which I set as claims. The reason I ask this, I have a mapper which coverts this map to java object and vice-versa.

**Comment by dogeared** [comment]
I think you'll want to do:

.claim("serialized", claims)

Then, when you parse, you can just pull out "serialized"

Note: you may want to call is something other than claims as that's generally understood to be all the claims.

HTH,

Micah

**Comment by sridhar1982** [comment]
@dogeared thats what I have been doing. when you pull out, you more items out of serialized. see my comments reply above

**Comment by dogeared** [comment]
In your example, you are calling:

setClaims

Note that my example is:

claim

They are two different methods

**Comment by eric-taix** [comment]
As @dogeared said just use `JwtBuilder#claim` method :

```
Map<String,Person> serializedObjects = myMapper.serialize(myObjectsToConvert);  
Jwts.builder()  
                .claim("myPrivateClaimKey", serializedObjects)  
                .setIssuedAt(now)  
                .setExpiration(expiration)  
                .setIssuer(ISSUER)  
                .signWith(SignatureAlgorithm.HS512, secretKey)  
                .compact();
``` 
 
The JSON representation will be:
```
{
  "iss": "ISSUER"
  ...
  "myPrivateClaimKey": {
    "hello": {
      "name": "xxxx"
    },
    "world": {
      "name": "yyyy"
    }
  }
}
```
 
When you deserialize the Jwt body, just get "myPrivateClaimKey":  
  
```
Object serializedObjects = Jwts.parser().setSigningKey(secretKey).parseClaimsJws(token).getBody().get("myPrivateClaimKey");  
Object objects = myMapper.deserialize(serializedObjects);
``` 
  
Does it make sense?

**Comment by sridhar1982** [comment]
yes, that should work. I will try it in my applicaton

**Comment by lhazlewood** [comment]
IMO, JWT building/parsing is a completely orthogonal concern from object mapping, but the two can be done cleanly - without polluting either concern - as recommended above.  Closing per the recommended solution from @dogeared and @eric-taix.  Thanks!
