### ISSUE TITLE
How to decode?

### ISSUE THREAD

**Issue by yang22zhang** [jwtk/jjwt#156]
I have a code like: 
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ

How do I decode it?
Cases without decoding, can determine if expired?
There is no API help me understand JJWT?

**Comment by lhazlewood** [comment]
```java
String token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ";
Jwts.parser().setSigningKey(yourPrivateKey).parseClaimsJws(token);
```

An example of this is in the [Quickstart](https://github.com/jwtk/jjwt#quickstart)

**Comment by lhazlewood** [comment]
For follow-up questions, please use StackOverflow.com.  Please use GitHub for reporting bugs, problems or feature enhancements or requests.  Thanks!
