### ISSUE TITLE
Claim get value exception ,but no exception msg 

### ISSUE THREAD

**Issue by tianzhidao28** [jwtk/jjwt#157]
jwt build : 

  return Jwts.builder().setNotBefore(today).setIssuedAt(today).setClaims(new HashMap<String, Object>(){{
                put(EncryptUserId_KEY,userInfo.eid);
                put(UserName_KEY,userInfo.uname);
                put(Admin_KEY,userInfo.admin);
                put(User_Id_KEY,userInfo.uid);
                put(RegistrationID_KEY,userInfo.jid);
            }})
            .signWith(SignatureAlgorithm.HS256,key)
            .compact();

this is no exception jwt get User_Id_KEY 

```
 try{
            Claims claims = jwtParser.parseClaimsJws(jwt).getBody();
            Long uid = claims.get(User_Id_KEY,Long.class);
            if (uid < 0) {
                return null;
            }
            String uname = claims.get(UserName_KEY,String.class);
            boolean admin = claims.get(Admin_KEY,Boolean.class);
            String eid = claims.get(EncryptUserId_KEY,String.class);
            String jid = claims.get(RegistrationID_KEY,String.class);
            return new TokenUserInfo(eid,uname,admin,uid,jid);
        }catch (Throwable t){
            t.printStackTrace();
        }
        return null;

```

when execute to  the line   " Long uid = claims.get(User_Id_KEY,Long.class);  "
the program direct got to the line " return null "

???

 I found my userId is Long ,
but at last it become Integer

**Comment by lhazlewood** [comment]
I believe you're seeing the same problem as documented in #142

**Comment by lhazlewood** [comment]
Closing as duplicate. If you believe otherwise, please feel free to re-open the issue.
