### ISSUE TITLE
Import of constant does not resolve in Android Studio

### ISSUE THREAD

**Issue by oliverhausler** [jwtk/jjwt#16]
Something minor but something you may want to fix throughout. I am using Android Studio with default settings, and the "HS256" does not resolve on this line:

String compact = Jwts.builder().setSubject("Joe").signWith(HS256, key).compact();

I'd suggest you change it to

String compact = Jwts.builder().setSubject("Joe").signWith(SignatureAlgorithm.HS256, key).compact();

and import SignatureAlgorithm instead.

I don't know if this is a default setting which came in from an alpha version of Android Studio or if this is still default, but my Android Studio (or the settings, haven't checked this) do not allow the direct import of a Constant. I'd change it as a precaution because other users may run into the same issue.

**Comment by oliverhausler** [comment]
[and Les, if everybody would write easy-to-use code like yours devving would be much easier]

**Comment by oliverhausler** [comment]
I just looked at both versions again and it's the static import which my Android Studio does not like, for whatever reason.

I have

import io.jsonwebtoken.SignatureAlgorithm;

instead of the static import with *

I googled and found this http://stackoverflow.com/questions/4387134/intellij-static-import-completion so it doesn't seem to be the default setting in Android Studio to allow static imports like yours.

**Comment by lhazlewood** [comment]
Ah yes, this assumes static imports - I assume that people use these regularly :/

Thanks for the note and the kudos!

**Comment by lhazlewood** [comment]
Static imports are a standard Java language feature, regardless of what an IDE may or may not do by default.  Also, the first code example shows how to use this:

```java
import io.jsonwebtoken.Jwts;
import static io.jsonwebtoken.SignatureAlgorithm.*;
...
```

Any objection to me closing this issue since this is not a JJWT issue?  Or do you still feel like the example should be changed to use a non-static import?

I consider this a language feature and not something that should be changed based on an IDE's default settings - thoughts?

**Comment by oliverhausler** [comment]
I agree with you and I agree Google/IntelliJ should set a different default for Android Studio. I don't know the reason but I will file a ticket there.

I only told you because I like your tool and it would be sad to see people leave just because they can't get it to work.

You can close this.


-------- Original message --------
From: Les Hazlewood
Date:2015/02/11 17:02 (GMT-08:00)
To: jwtk/jjwt
Cc: Oliver Hausler
Subject: Re: [jjwt] Import of constant does not resolve in Android Studio (#16)


Static imports are a standard Java language feature, regardless of what an IDE may or may not do by default. Also, the first code example shows how to use this:

import io.jsonwebtoken.Jwts;
import static io.jsonwebtoken.SignatureAlgorithm.*;
...

Any objection to me closing this issue since this is not a JJWT issue? Or do you still feel like the example should be changed to use a non-static import?

I consider this a language feature and not something that should be changed based on an IDE's default settings - thoughts?

-

**Comment by lhazlewood** [comment]
Resolving now that the Readme example does not use static imports - should work for Android folks too.
