### ISSUE TITLE
Validate signature before decompression

### ISSUE THREAD

**Issue by lhazlewood** [jwtk/jjwt#166]
This could cause a breaking change for the `SigningKeyResolver` interface since the `Claims` argument would not be available before decompression.  As a result this might need need to wait until 0.8.

**Comment by thomseno** [comment]
Is there a schedule for this? Waiting for a fix in milestone 0.8 (#142)... Regards.

**Comment by lhazlewood** [comment]
This work has been merged to `master` long ago - we missed closing the issue.
