### ISSUE TITLE
Why are 'expected' and 'actual' arguments of assertEquals switched in a lot of tests?

### ISSUE THREAD

**Issue by sainaen** [jwtk/jjwt#169]
It's not an issue with the library per se, but I found that a lot of tests have `assertEquals()` or `assertSame()` calls with the first (`expected`) argument being result of some interaction with an object under the test, while the second (`actual`) arg is a predefined “correct” value. This leads to confusing messages in case of assertion failures (see example below.)

So I was wondering if it's intentional and part of the project's code style? Should I follow it while writing new tests?

#### Example
For example, one of the tests,`JwtsTest#testConvenienceId()` starts with check when `setId()` method is called, an `id` claim is actually set and can be retrieved from the token with `getId()`:
```java
String id = UUID.randomUUID().toString();
String compact = Jwts.builder().setId(id).compact();
Claims claims = Jwts.parser().parse(compact).body as Claims
assertEquals claims.getId(), id
// the rest is skipped for brevity
```
But notice, that `assertEquals` gets a result of execution `claims.getId()` as `expected` argument and then a correct `id` as `actual`. So when, let's say `setId()` incorrectly always sets a jti claim to `'oops'`, an assert failure message looks like this:
```
org.junit.ComparisonFailure: 
Expected :oops
Actual   :803e5a98-9e20-4eca-aba3-775b1b4bbe6a
```
which, in my opinion, is confusing, especially if you're not familiar with the failing test yet.

**Comment by lhazlewood** [comment]
Hi @sainaen,

Great question - the answer is that it is a total mistake.  TestNG and JUnit switched the argument positions of what is expected vs what is actual, and it's easy to forget which is which when writing tests.

We should definitely only use the API as documented.  Please feel free to change anything in a PR if desired!  (Also if you submit a PR, please feel free to ask that this issue be re-opened so you can link the PR to it).
