### ISSUE TITLE
Can JWT be shared between either party, any party can be verifier or generator?

### ISSUE THREAD

**Issue by thegamblerrises** [jwtk/jjwt#170]
I am in a confusion. I have two servers and one UI. Server A [nodejs] generates JWT-A, UI takes it and sends it to Server B [java]. The problem is, Serve B is not trusting JWT-A, however it perfectly verifies JWT-B (which it generates on its own).

Problem gets hard when I can verify JWT-A online if I provide secret key. Below is the JWT-A, which came from Server A.

`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjM4MjI5NmI0LWNkMzUtNDFiYy04MjE5LTlmM2E4YTQ3ZGYzYyJ9.RTuRMxAGwvoGRD0pqwbrLzGq6C4mMWWAbMltla4DuR4`

I can verify it online if I provide Secret Key, but JJWT throws below error.

`io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.`

Below is the part of code which verifies-
`Claims body = Jwts.parser().setSigningKey(secret).parseClaimsJws(jwt).getBody();`

Am I missing something, is it a bad implementation? Please correct me. Thanks.

**Comment by lhazlewood** [comment]
Is your `secret` a Base64 String that represents a byte array?  Please read the javadoc for the `setSigningKey` method.

**Comment by thegamblerrises** [comment]
Thanks. What a silly mistake.

**Comment by lhazlewood** [comment]
No worries! I'm glad you were able to get it to work :)
