### ISSUE TITLE
Document whether DefaultJwtParser is thread-safe and/or resuable

### ISSUE THREAD

**Issue by dnault** [jwtk/jjwt#171]
Looks like that's the intent; can you make a definitive statement?

Thanks!

**Comment by lhazlewood** [comment]
Sure!  We hope to add proper docs soon (not just the README), so thanks for the issue!

**Comment by agemooij** [comment]
Just to make sure this is in fact the case, could you please confirm that `DefaultJwtParser` is in fact thread-safe and that this is guaranteed to be the case in the future?

**Comment by ricardoccpaiva** [comment]
any news on this ?

**Comment by rubeninoto** [comment]
any news?

**Comment by lhazlewood** [comment]
For those following along on this issue, JJWT the upcoming JJWT 0.11.0 release introduces a `JwtParserBuilder` that is returned from `Jwts.parserBuilder()` (contrast that with today's `Jwts.parser()`.  Instances of parsers returned from `Jwts.parserBuilder().....build()` are immutable.  Further, `Jwts.parser()` will be removed when 1.0.0 is released eventually.

cc @bdemers - can you please use this issue to ensure documentation for the 0.11.0 method JavaDoc, release notes and standard documentation makes this explicitly clear?

**Comment by lhazlewood** [comment]
Closing per edits in #559.  Will be released with 0.11.0
