### ISSUE TITLE
Generating a JWKS from RsaProvider.getPublic()?

### ISSUE THREAD

**Issue by myshkin5** [jwtk/jjwt#173]
Hi,

Got my production code to work fine (thanks jjwt!) but I am trying to fix a bunch of broken integration tests that used to assume there was no security. I wanted to keep things as real as possible so I thought I would stand up a mock http server that would return a JWKS. I create a public/private key pair using `RsaProvider` then I encode the public key in a bit of json wrapper. The app pulls in the json and attempts to regenerate the public key but I get `java.io.IOException: DerInputStream.getLength(): lengthTag=127, too big`.

Here's the code that creates the cert that I wrap in some json (on the mock http server):

```java
    final KeyPair keyPair = RsaProvider.generateKeyPair(2048);
    final String encodedPublicKey = Base64.getEncoder().encodeToString(
            keyPair.getPublic().getEncoded());
```

Here's the production code that converts the encoded public key to a `PublicKey` object (note this code works fine with a JWKS from Auth0 but not with the JWKS I'm generating from `RsaProvider`):

```java
    private static PublicKey createPublicKey(final String encodedPublicKey) {

        final byte[] encodedKey = Base64.getDecoder().decode(encodedPublicKey);

        final X509Certificate cert;
        try {
            final CertificateFactory factory = CertificateFactory.getInstance("X.509");
            cert = (X509Certificate)factory.generateCertificate(new ByteArrayInputStream(encodedKey));
        } catch (final CertificateException e) {
            throw new RuntimeException(e);
        }

        return cert.getPublicKey();
    }
```

Any help is greatly appreciated!

Dwayne

**Comment by lhazlewood** [comment]
The `CertificateFactory` approach isn't quite right when you have the JVM encoded public key bytes - you want to use a `KeyFactory` instead.

Try this:

```java
final byte[] encodedKeyBytes = Base64.getDecoder().decode(encodedPublicKey);
return KeyFactory.getInstance("RSA").generatePublic(new X509EncodedKeySpec(encodedKeyBytes));
```

(from http://stackoverflow.com/questions/2411096/how-to-recover-a-rsa-public-key-from-a-byte-array).

HTH!

**Comment by lhazlewood** [comment]
@myshkin5 is this issue solved for you?  I'd prefer to close this out if so and use GitHub Issues only for actionable work for the team.  We prefer StackOverflow be used for general questions if possible.  Thoughts?

**Comment by myshkin5** [comment]
@lhazlewood That did work. Thanks! I can't figure out how to have the same code parse an Auth0 public key and a Java public key but none of my remaining issues are jjwt issues.

Thanks again!

**Comment by lhazlewood** [comment]
👍
