### ISSUE TITLE
Customisable claims in format "Date by Seconds"

### ISSUE THREAD

**Issue by andreas-lundgren-storytel** [jwtk/jjwt#181]
A nice-to-have feature would be to make the list at https://github.com/jwtk/jjwt/blob/48dae365b18aadf6323b32f89f63960cca3a3f47/src/main/java/io/jsonwebtoken/impl/DefaultClaims.java#L116 customisable, allowing users to add custom claims that are dates represented in seconds. This should be added when creating the JWT parser and serialiser.

**Comment by lhazlewood** [comment]
Closing this as it will be implemented and resolved via #474 .  Please use that issue for any further comments.  Thanks!
