### ISSUE TITLE
Are there some big companies using the jjwt?

### ISSUE THREAD

**Issue by yqzhan2014** [jwtk/jjwt#185]
I want to see some real apis which use jwt as the auth.
Can someone give me confidence to use it.

**Comment by RobWin** [comment]
Google uses JWT for its ID token.

https://developers.google.com/identity/protocols/OpenIDConnect

**Comment by lhazlewood** [comment]
Please use StackOverflow for general questions.  GitHub is used for ticketing (bugs, feature enhancements, etc).

JWT is used by almost all modern Identity Management companies - you should have every confidence using it.
