### ISSUE TITLE
Is parseClaimsJws method thread safe?

### ISSUE THREAD

**Issue by akoshman** [jwtk/jjwt#186]
Hi,

For sake of optimize a code I'd want to create once and save for further use a parser:

`Jwts.parser().setSigningKey(signKey)`

Can someone say is it safe to execute `parser.parseClaimsJws()` method simultaneously from different threads?

Thanks for help.

**Comment by lhazlewood** [comment]
It is thread-safe *iff* you don't change the parser configuration.

**Comment by akoshman** [comment]
@lhazlewood Thank you for help
