### ISSUE TITLE
Signed JWSs/JWTs are not supported

### ISSUE THREAD

**Issue by oliverhausler** [jwtk/jjwt#187]
When I use `Jwts.parser().parsePlaintextJws(token)` on one of my tokens, I get an exception with something like "Signed JWSs/JWTs are not supported".

That doesn't make much sense to me. Am I doing this wrong?

I want to look at my own token on the client, to read the fields. I can't give the secret to the client. Will I need to use a different library? What is the reason that I can't read fields in a signed token if the token isn't encrypted?

https://jwt.io/ can read all fields.

**Comment by gposcidonio** [comment]
How are you generating the token?

**Comment by oliverhausler** [comment]
```
token = Jwts.builder()
                    .setIssuer(ISSUER)
                    .setId(sessionId)
                    .claim("type", TYPE)
                    .setSubject(userId)
                    .setAudience(hostname)
                    .claim("scopes", scopes)
                    .claim("origins", origins)
                    .setIssuedAt(issuedAt)
                    .setExpiration(expiration)
                    .signWith(SignatureAlgorithm.HS256, SECRET_KEY)
                    .compact();
```

**Comment by gposcidonio** [comment]
Perhaps you need the following:
```
Jwts.parser.setSigningKey(SECRET_KEY).parsePlaintextJws(token);
```

**Comment by oliverhausler** [comment]
Yes, that would work, but the signing key is not known on the client. Plaintext fields should always be readable, no matter if I know the key or not.

**Comment by dogeared** [comment]
@oliverhausler - If the JWT is signed, and is therefore a JWS, the specification makes it incumbent upon the JWT library to verify that signature. This is laid out in:

* [RFC 7519 - JWT, section 7.2, #6 and #7](https://tools.ietf.org/html/rfc7519#section-7.2)
* [RFC 7516 - JWE, section 9](https://tools.ietf.org/html/rfc7516#section-9)
* [RFC 7515 - JWS, section 5.2](https://tools.ietf.org/html/rfc7515#section-5.2) 

```
However, in all cases, at least one JWS Signature value MUST successfully validate, or the JWS MUST be considered invalid.
```

**Comment by lhazlewood** [comment]
closing per @gposcidonio and @dogeared last comments.  Also note that the term 'plaintext jwt' is no longer valid upon finalization of RFC 7519 (they removed that term and the support for arbitrary text payloads and now have only JSON Claims Set payloads that maybe secure or unsecure).  We'll remove 'parsePlaintext*' method variants from JJWT before the 1.0 final release to stay consistent with the RFC.
