### ISSUE TITLE
JWT tokens gives SignatureException exception.

### ISSUE THREAD

**Issue by ankit8051** [jwtk/jjwt#188]
Hi Team,

We have used jjwt lib for generating the token and use this token to validate the user on other api.

**Token Generation Code::**
```
String token = Jwts.builder().setSubject(loginRequest.getUserName())
							.setExpiration(new Date(System.currentTimeMillis() + 30000))
			                .claim("Test Data", "Test Data").claim("ipAddress", IpAddress)
			                .signWith(SignatureAlgorithm.HS512, secretKey).compact();
```

**Token Decryption Code**

```
Map<String, Object> tokenDetail = new HashMap<String, Object>();
		ObjectMapper mapper = new ObjectMapper();
		
		// parsing and validating JWT token.
		try {
			final Claims claims = Jwts.parser().setSigningKey(secretKey)
		            .parseClaimsJws(token).getBody();
			LOGGER.debug("Token parsed and validated.");
		
		} catch(ArrayIndexOutOfBoundsException ex) {
			throw new MalformedJwtException(ex.getMessage(), ex);
		}
```

We have different clients which are working on different machines and they are using this token for user authentication.

They will decrypt the token by using above code. SecretKey is same for both the client.

Now the issue is for one application this is working fine and on another machine, it is throwing SignatureException  exception. Both the machine is having the same configuration like java version and all.

Is there any other issue causing this problem?

**Comment by gposcidonio** [comment]
Could you provide the output of the error? What does the `SignatureException` message contain?

**Comment by huhanghao** [comment]
I have the same proble as ankit8051 write.My exception is"io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted."

**Comment by huhanghao** [comment]
I have already fixed this problem,and find the reason.
Claims secret = Jwts.parser().setSigningKey("secret".getBytes("UTF-8")).parseClaimsJws(data).getBody();

focus on "getBytes("UTF-8")".Eventhough my AS have already set encoding mode as “UTF-8”，I have to set it again here.

**Comment by lhazlewood** [comment]
Closing this as the `secret` was not a Base64-encoded string.  Please read the `setSigningKey` method JavaDoc.

Note: if your key string is not base64-encoded, you might be using a poorly-formed (i.e. insecure) key.
