### ISSUE TITLE
manifest.mf additional data for osgi supporting

### ISSUE THREAD

**Issue by enflout** [jwtk/jjwt#19]
Hi, your lib is awesome. Could you please add some manifest data to run it in osgi-container?

**Comment by lhazlewood** [comment]
Sure - do you have a pull request to enable this?

**Comment by enflout** [comment]
@lhazlewood, it will be first time when I do this kind of action, but I can try. So I'll try to send a pull-request on the next week :)

**Comment by lhazlewood** [comment]
Thanks!  It will be a good learning experience :)

**Comment by lhazlewood** [comment]
Closing as PR #24 was merged.  This will be released with 0.5
