### ISSUE TITLE
No signature validation if the signature part is empty ! 

### ISSUE THREAD

**Issue by ymlaine** [jwtk/jjwt#193]
Hi,

When verifying a token, (supposed to be RS512 signed in my case) if I parse it with the signature part empty (so ending with the 3rd dot  : xxxxx.yyyy. ) the token is parsed without any Signature Exception !!

Tested on 0.6 and 0.7
 
Code example : 

`		Object body = Jwts.parser().setSigningKey(pubkey).parse(s).getBody();`

I had to add this security check code before parsing the token, but seems weird :

		String[] jwtParts = s.split("\\.");
		if (jwtParts.length <3) {
			throw new EMandatException("Incomplete token");
		}
		if (StringUtils.isEmpty(jwtParts[2])) {
			throw new EMandatException("Signature part missing");			
		}

**Comment by lhazlewood** [comment]
Don't call `parse` if you know it is a signed token.  Call `parseClaimsJws`.

**Comment by ymlaine** [comment]
Ok, thanks, I guessed I was doing smth wrong, but at the same time, I don't really understand the concept to check a signature if it's not mandatory... Anyway... I updated my code, it works better now. :) Thx !
