### ISSUE TITLE
Creating JWT

### ISSUE THREAD

**Issue by BorisB-Tradair** [jwtk/jjwt#197]
Hello,

I saw on YouTube a video regarding the JWT. 
https://youtu.be/oXxbB5kv9OA?t=15m40s

Following this video, I have a question:
Does the way the jwt token being build using the jjwt-repo, is the same as on the youtube video?
If no, is it also OK, and what method is "better"?

Thanks from advanced!

**Comment by lhazlewood** [comment]
Hi, can you please ask this question on StackOverflow and use the `jjwt` tag?  We uses the GH issue tracker for actionable work items only.  Thank you!
