### ISSUE TITLE
Security issue?

### ISSUE THREAD

**Issue by oliverhausler** [jwtk/jjwt#202]
Hi @lhazlewood 

This is old and I assume you are aware of this and the library has the required safety measures, but I wanted to point you to this here just to make sure:

https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/

Cheers, Oliver.

**Comment by cleiter** [comment]
See https://github.com/jwtk/jjwt/issues/20

**Comment by oliverhausler** [comment]
@cleiter Thanks! I searched issues but overlooked this.
