### ISSUE TITLE
Signing key Base64 encoding discrepancy

### ISSUE THREAD

**Issue by jbonevich** [jwtk/jjwt#204]
This is NOT a bug, but an observation that you may want to capture in documentation (but at least it is here in the issues so that it does not trip up others).

When I created a JWT using this wonderful library, I was at first signing it with a Base64 encoded string:
>        String secret = "secret";
>        byte[] base64SigningKey = Base64.getEncoder().encode(secret.getBytes());
>        String jwt = Jwts.builder().setSubject("Bob").signWith(SignatureAlgorithm.HS256, base64SigningKey).compact();

However, when I then parsed and validated the JWT, I got errors:
>        Jws<Claims> jws = Jwts.parser().setSigningKey(secret).parseClaimsJws(jwt);

which yielded:
> io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.

Took me a while to track down and it makes complete sense now, but I would have loved to have seen it in the docs:
* Be consistent in your use of builder.signWith() and parser.setSigningKey(): use the String argument versions on each end, or use the byte[] versions on both
    * if you use the String arguments they will use a platform-dependent Base64 codec  (TextCodec.BASE64 which relies on an implementation specific to the platform: JAXB DataConverter in the case of JVM, android.util.Base64 for Android)
    * These internal codecs may be inconsistent with other codecs (such as Java 8's java.util. Base64 class)

Hope this makes sense.

**Comment by clarkdo** [comment]
+1 
Met the same issue due to TextCodec.BASE64 inconsistent behaviour.
Suggestion of @jbonevich is very helpful for newbies.

**Comment by samwebber** [comment]
+1 
It would be helpful if you could set the TextCodecFactory in the builder and parser (with the current default) the builder and parser used it rather than static references. At least you would have some control over how the base64 encoding or decoding is done.

**Comment by lhazlewood** [comment]
Thanks for the issue folks - we'll need to clarify this in the documentation for sure.  You're definitely not the only ones to experience this issue.

**Comment by mattdehring** [comment]
It seems to have to do with not being a valid Base64 string in that it isn't padded correctly. It truncates the last few bytes if the input string length isn't a factor of 4.

**Comment by lhazlewood** [comment]
@samwebber your suggestion is being tracked in the #333 description.  Thanks for the idea!

FWIW, I'm leaving this issue open to enhance documentation as part of the upcoming release that will include #333.

**Comment by lhazlewood** [comment]
This issue is now closed per the closing of #333 .  Documentation for this will be done as part of #355 .

**Comment by lhazlewood** [comment]
This has been fixed and released in 0.10.0.
