### ISSUE TITLE
Documentation error in JwtParser.java

### ISSUE THREAD

**Issue by rhonnava** [jwtk/jjwt#206]
Documentation error in JwtParser.java

There looks like a copy paste error in documentation for this method in JwtParser.java:

```
JwtParser setSigningKey(Key key);
```

The statement "This is a convenience method: the string argument is first BASE64-decoded to a byte array and this resulting byte array is used to invoke {@link #setSigningKey(byte[])}" describes the method just above it.

**Comment by dogeared** [comment]
Thanks for this. I'll create a PR to update those docs.
