### ISSUE TITLE
Usage of requireExpiration(Date expiration)

### ISSUE THREAD

**Issue by apollux** [jwtk/jjwt#213]
I want to validate a received token and make sure that it has a Expiration Time set. It looks like the only way to do such a thing is with the requireExpiration(Date expiration) method. However this requires the Expiration Time to equal the expiration passed as a parameter. On the receiving side I have no clue what the expiration time is going to be. I just want to make sure an expiration time is present in the token.

I have the following questions:
How can I require the presence of an exp claim?
What is the use case for the requireExpiration(Date expiration) since typically anyone who wants to validate the exp claim can not know the exact value of the expiration date.

**Comment by brotherYoung** [comment]
How did you solve it? thanks

**Comment by brotherYoung** [comment]
> How did you solve it? thanks



> I want to validate a received token and make sure that it has a Expiration Time set. It looks like the only way to do such a thing is with the requireExpiration(Date expiration) method. However this requires the Expiration Time to equal the expiration passed as a parameter. On the receiving side I have no clue what the expiration time is going to be. I just want to make sure an expiration time is present in the token.
> 
> I have the following questions:
> How can I require the presence of an exp claim?
> What is the use case for the requireExpiration(Date expiration) since typically anyone who wants to validate the exp claim can not know the exact value of the expiration date.

I've already put it into practice:

1. please set IssuedAt & Exp at the time of creation
`Jwts.builder().setSubject("Joe").setIssuedAt(new Date()).setExpiration(DateUtil.expirationDate(20000)).signWith(key).compact()`

2. if token expire, Claims throws exception automatic

**Comment by lhazlewood** [comment]
I'm closing this in favor of #474 - that issue will allow all sorts of custom validation other than `value != null && expectedValue.equals(value)` (which is what it is today)
