### ISSUE TITLE
Proguard exclusions

### ISSUE THREAD

**Issue by bpappin** [jwtk/jjwt#215]
What are the ProGuard exclusions for JJWT?

For instance, we can't build due to this error.
```
Warning:io.jsonwebtoken.impl.Base64Codec: can't find referenced class javax.xml.bind.DatatypeConverter
Warning:io.jsonwebtoken.impl.crypto.EllipticCurveProvider: can't find referenced class org.bouncycastle.jce.ECNamedCurveTable
Warning:there were 5 unresolved references to classes or interfaces.
```

**Comment by bpappin** [comment]
Related issues :

- #7
- #18
- #192
- #143

**Comment by bpappin** [comment]
one of the warning can be handled with ProGuard rules.

```
-keep class org.bouncycastle.** { *; }
-keepnames class org.bouncycastle.** { *; }
-dontwarn org.bouncycastle.**
```

**Comment by sbanouar** [comment]
Hi Brill Pappin,

The proguard exclusions for JJWT & Jackson are:

-keepnames class com.fasterxml.jackson.databind.** { *; }
-dontwarn com.fasterxml.jackson.databind.**
-keepattributes InnerClasses

-keep class org.bouncycastle.** { *; }
-keepnames class org.bouncycastle.** { *; }
-dontwarn org.bouncycastle.**

-keep class io.jsonwebtoken.** { *; }
-keepnames class io.jsonwebtoken.** { *; }
-keepnames interface io.jsonwebtoken.** { *; }

-dontwarn javax.xml.bind.DatatypeConverter
-dontwarn io.jsonwebtoken.impl.Base64Codec

-keepnames class com.fasterxml.jackson.** { * ; }
-keepnames interface com.fasterxml.jackson.** { *; }
 
I hope this help you.

**Comment by lhazlewood** [comment]
I've added this to a new wiki page:

https://github.com/jwtk/jjwt/wiki/ProGaurd-exclusions

Please free to re-open this issue if you think other actionable work needs to be done.

**Comment by ederpadilla** [comment]
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'. > Job failed, see logs for details	
-keepnames class com.fasterxml.jackson.databind.** { ; }



and steel send me this warning
Warning:com.fasterxml.jackson.databind.ext.DOMSerializer: can't find referenced class org.w3c.dom.bootstrap.DOMImplementationRegistry
Warning:io.jsonwebtoken.impl.crypto.EllipticCurveProvider: can't find referenced class org.bouncycastle.jce.ECNamedCurveTable

**Comment by asdfiop** [comment]
不好

**Comment by asdfiop** [comment]
不好

**Comment by c0state** [comment]
There were some syntax errors and/or incorrect rules in the snippet above I believe. Wiki entry has been updated with corrections.

**Comment by pedroromao-acceptto** [comment]
Wiki link 
https://github.com/jwtk/jjwt/wiki/ProGuard-exclusions
