### ISSUE TITLE
Incorrect body base64 length

### ISSUE THREAD

**Issue by trojanc** [jwtk/jjwt#216]
Hi, I'm having trouble using this created token from a JavaScript client.

The body of the generated token is not the proper length for base64

I see the class `Base64UrlCodec` is responsible for changing some characters and stripping the padding.
Why is that necessary? This means that a client trying to read the token can't use it without first reversing the replaced characters, and add the required padding... I tried to extend the `DefaultJwtBuilder` class to have it call `TextCodec.BASE64.encode` instead, but I could because of all the private fields....my only other option is to copy paste that whole class and make it generate properly padded base64 parts.

So, my question really is:
- Why is the body modified and not just a proper base64 string?
- Is there a way I can use another type of builder that creates base64 strings with correct padding?

**Comment by lhazlewood** [comment]
Base64Url encoding is different than Base64 encoding.  Base64Url encoding is mandated by the JWT specification - it's not our choice ;)  In other words, the JWT specification does not support plain Base64 encoding.  Your JavaScript client is not JWT-compatible.

That said, I'm closing this as there does not appear to be actionable work for the JJWT project.  If you have questions (as opposed to known actionable work), please use StackOverflow.com and use the `jjwt` tag.  Thanks!
