### ISSUE TITLE
Using Compression codes with JDK 1.6

### ISSUE THREAD

**Issue by sk901s** [jwtk/jjwt#218]
Hi

I have a claims object that is fairly large and need to compress it. I was interested in using the **.compressWith(CompressionCodecs.DEFLATE)** , however I am stuck with JDK 1.6 at work and noticed I need JDK 1.7 to use the inbuilt compression feature. 

I was wondering if there is a way to make it work for JDK1.6.

Thanks

**Comment by lhazlewood** [comment]
You'll have to implement the `CompressionCodec` interface yourself using a JDK 1.6-compatible implementation/algorithm:

```java
CompresionCodec codec = new MyJdk16CompatibleDeflateCodec();
// ...
.compressWith(codec)
```
