### ISSUE TITLE
SignatureException with correct signature

### ISSUE THREAD

**Issue by DavidDecraene** [jwtk/jjwt#219]
Here is a test case, built on https://jwt.io where it validates:

String token2 = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBfbWV0YWRhdGEiOnsibGFzdF9sb2NhdGlvbiI6IkJFIiwiZ3JvdXBzIjpbXSwicm9sZXMiOnsidXNyLWFkbWluIjp0cnVlLCJpbnRlbGwiOnRydWUsIm1udHIiOnRydWV9fX0.ozJKvOcl_O5uPOHaIzTJ34YyCoDqK0i1nNLSVs4Rm50";
String secret2 = "etcectectc";

Jwts.parser().setSigningKey(secret2).parseClaimsJws(token2); //throws signature exception

**Comment by DavidDecraene** [comment]
Note it can be resolved by doing this instead:
Jwts.parser().setSigningKey(secret2.getBytes("UTF-8")).parseClaimsJws(token2);

which means it is an encoding issue

**Comment by EralpB** [comment]
#146

**Comment by lhazlewood** [comment]
Your secret is not Base64-encoded, which is required - as documented - in the `setSigningKey` [JavaDoc](https://github.com/jwtk/jjwt/blob/master/src/main/java/io/jsonwebtoken/JwtParser.java#L165-L180).
