### ISSUE TITLE
Reusability of JwtParser vs. performance overhead

### ISSUE THREAD

**Issue by frederikheremans** [jwtk/jjwt#226]
The `DefaultJwtParser` contains a couple of members that are reusable across multiple `parse(...)` calls. For example, a parser always creates a new `ObjectMapper` instance which is recommended to be created only once and shared across your application (as it involves some setup, even though the number of models that it will generate/support is fairly limited for JWT).

1. The docs don't explicitly state that a parser can be and all examples seem to suggest to create a new parser instance for every call.
2. All `requireXX(..)` methods alter the claims that are contained in the parser instance, making it not thread safe.

Currently, in order to prevent a lot of short-lived object-mappers to be created, I only see two ways of circumventing that:

1. Do not use the `requireXX(..)` methods at all, let it only do the parsing. Assert the claims in your own code, based on the parsed result.
2. Extend the `DefaultJwtParser` class that uses a subclass of `DefaultClaims`, which keeps TheadLocal maps of claims, making the claim-assertion bit of the parsing thread-safe.

IMHO, these are workarounds. What I would suggest is either: 

1. Build the parser to be reusable (and encourage it in the docs) by passing the `Claims` as additional parameter with the parse call.
2. Keep the parser aware of the internal Claims state, allow usage of shared "resources" and document this usage.

WDYT? I'm in favour of the first solution and always happy to create PR and contribute if this is seen as a good idea...

**Comment by lhazlewood** [comment]
We definitely need to be more clear around these semantics.  Thanks for the issue!  We'll use this to keep track of the work required to update a proper documentation page (rather than just the README + Release notes).

**Comment by lhazlewood** [comment]
Note that #335 resolves the problem of multiple ObjectMappers used (now only one static instance is used by default), and it also allows you to plug in your own JSON implementation if JJWT's defaults aren't sufficient for whatever reason (or if you just want JJWT to use your existing ObjectMapper instance).  #335 functionality is already merged to master and will be released in 0.10.0.

We'll still keep this issue open however to track work around adding a new `JwtParserBuilder` with a `build()` method method that returns an immutable `JwtParser`, but this may imply backwards-incompatible changes that would need to wait until 1.0

**Comment by lhazlewood** [comment]
Closing this finally as #473 is a dedicated issue to represent the `JwtParserBuilder` work.
