### ISSUE TITLE
Is there a way to add custom field to payload ? 

### ISSUE THREAD

**Issue by Nbsaw** [jwtk/jjwt#227]
Hi all . 

I want to add a custom field(UserType) to my jwt payload. look like that , how can i do that ?

``` java
String compactJws = Jwts.builder()
                                 .setId(uid)
                                 .setCustomField("userType",userType)
                                 .setExpiration(getExp())
                                 .signWith(SignatureAlgorithm.HS512,key)
                                 .compact();
```

**Comment by johnv-git-slc** [comment]
.claim("UserType", "Purple")

**Comment by Nbsaw** [comment]
@johnv-git-slc Thanks bro 👍

**Comment by bakulinav** [comment]
Hello,
I there are any way to parse the same fields in more natural way, to make kind of customization of claims?
For example, extend `DefaultClaims` like:
```
public class CustomClaims extends DefaultClaims {
    public static final String USER_ID = "userId";
    public static final String COMPANY_ID = "companyId";
    public String getUserId() { return this.get(USER_ID, String.class); }
    ...
}
```
and use it like following:
```
Jws<CustomClaims> jwsClaims = Jwts.parser()
                    .parseClaimsJws(token);
...
String userId = jwsClaims.getBody().getUserId();

```
For now to me it's a big question how to make parser to parse my custom fields.

**Comment by pkalwar** [comment]
You can have a custom class like:

public static final class MyJwtToken extends DefaultClaims {
		private static final String USER_ID = "userId";
		// ... your other fields
		public MyJwtToken() {
			super();
		}
		private MyJwtToken(Claims claim) {
			super(claim);
		}

		public String getUserid() {
			return (String) get(USER_ID);
		}
		public void setUserid(String userId) {
			super.setValue(USER_ID, userId);
		}
		
		//.... other custom getters/setters
	}

and use this class like:


MyJwtToken myToken = new MyJwtToken(Jwts.parser().setSigningKey(tokenSigningKey).parseClaimsJws(tokenStr).getBody());


now you can call:   myToken.getUserid();

**Comment by lhazlewood** [comment]
I'd really recommend *not* subclassing the Claims implementation - you're tightly coupling your implementation to JJWT's.  Instead, it's better to use [composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance).  In other words, save your custom data as a claim, e.g. `.claim("foo", myData)`.  Once you acquire your custom data, you can convert it or inspect it however you wish.
