### ISSUE TITLE
Support another crypto provider

### ISSUE THREAD

**Issue by jmarginier** [jwtk/jjwt#228]
I wan't to create JWT token through PKCS11 interface.

So, I need to use another crypto provider (like IAIK). Because, your lib support JCE Key interface but we can't set the provider to read the key (or i missed that).

May be like that : Jwts.parser().setSigningKey(key).setProvider(myProvider)....

Thx :)

**Comment by Gingercookie** [comment]
The BouncyCastle JCE provider is loaded in the following file
jjwt/src/main/java/io/jsonwebtoken/lang/RuntimeEnvironment.java

I imagine you'd be able to use the same method to include whatever other JCE you'd like and add it for use.

**Comment by lhazlewood** [comment]
If I'm not mistaken, you can implement the `SigningKeyResolver` interface and call `Jwts.parser().setSigningKeyResolver(mySigningKeyResolver)...`.  That will allow you to look up  your PKCS11 key (which should implement the `java.security.Key` interface) and return it from the interface method.

If you believe this is mistaken, please do comment and we'll open up the issue again.
