### ISSUE TITLE
can i verify jwt in node js which is generated using this java api?

### ISSUE THREAD

**Issue by pravink** [jwtk/jjwt#229]
I am trying to use the jwt token generated using java in a different node application but I am getting invalid signature error while verifying JWS -  at valid = jws.verify(jwtString, header.alg, secretOrPublicKey);

Thanks in advance!
Pravin

**Comment by lhazlewood** [comment]
There are lots of people that use JJWT and Node JS together.  Please ask this question on StackOverflow.com using the `jjwt` tag.  GitHub Issues is used for actionable work to modify the JJWT source code.
