### ISSUE TITLE
Update jackson.version to 2.8.9

### ISSUE THREAD

**Issue by msymons** [jwtk/jjwt#231]
jjwt currently (v0.7.0) uses jackson-databind v2.8.2.  Update this by incrementing jackson.version to 2.8.9.

Addresses Jackson Deserializer security vulnerability:

FasterXML/jackson-databind#1599
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8.9

**Comment by msymons** [comment]
Pull request: #232

**Comment by lhazlewood** [comment]
PR merged - thanks!
