### ISSUE TITLE
Securing secret key

### ISSUE THREAD

**Issue by zishanj** [jwtk/jjwt#237]
As I have gone through your example, I have seen that JWT requires a secret key to sign the token. Since Android apk can be easily decompiled, is they any way to secure this key so attacker can't find it easily. Otherwise, it will be very easy to compromise the server with fake token generated from stolen key.

**Comment by zippo227** [comment]
@zishanj you should not put the secret key in the client application, only on the server. When the client sends up a request, it includes the jwt. The server will use the secret key verify the integrity of the jwt.

As long as you are using SSL/TLS, you should be able to safely assume that the client is receiving a verified token from the server. If you want to be extra secure, inspect the certificate from your connection with the server to ensure that the token is coming from the correct server.

**Comment by zishanj** [comment]
Actually my Android app does not provide with Login that will authenticate user and generate the token from server. I require an access to get REST API data from server and for that purpose I wish to use token to provide some security but without any user login.

**Comment by psevestre** [comment]
It seems to me that you need some kind of activation code to bootstrap your authorization process. One way to do this is to generate a UUID or a hash based on some combination of device info. Then you can send this to the server that will in turn generate the jet token. 
That said, if your app does not require a login, even one acquired via an oauth flow, then why bother with security at all ?

**Comment by psevestre** [comment]
Just to make clear: by "security" I mean identity and authorization aspects. You still have to worry about availability and integrity, of course.

**Comment by zippo227** [comment]
@zishanj You won't need the secret key on the client to do that. You could simply generate a token and embed it in the source code for your client. Then the server will know that the request is coming from your client.

**Comment by lhazlewood** [comment]
Closing as this doesn't represent actionable work for the JJWT library itself (unless I'm mistaken).  We use GitHub issues for actionable work and StackOverflow for these type of general questions (please use the `jjwt` tag on StackOverflow if it is a question regarding the JJWT library itself and the `jwt` tag if general to JWT but not specific to JJWT). Thanks!
