### ISSUE TITLE
Check JWT Signature problems !?

### ISSUE THREAD

**Issue by java1983** [jwtk/jjwt#248]
Build token:
final String SECRET = "ThisIsASecret";
String JWT = Jwts.builder()
                .setSubject("username")
                .setExpiration(new Date(System.currentTimeMillis() + 864_000_000))
                .signWith(SignatureAlgorithm.HS512, SECRET)
                .compact();
        res.addHeader("Authorization", "Bearer" + " " + JWT);

Check token:
1)final String SECRET = "ThisIsASecret";
String user = Jwts.parser().setSigningKey(SECRET).parseClaimsJws(token.replace("Bearer" + " ", "")).getBody().getSubject(); -> OK as expected

2)final String SECRET = "ThisIsASecretf";
String user = Jwts.parser().setSigningKey(SECRET).parseClaimsJws(token.replace("Bearer" + " ", "")).getBody().getSubject(); -> OK, but why ?

3)final String SECRET = "ThisIsASecretff";
String user = Jwts.parser().setSigningKey(SECRET).parseClaimsJws(token.replace("Bearer" + " ", "")).getBody().getSubject(); -> same OK, but why ?

4)final String SECRET = "ThisIsASecretfff";
String user = Jwts.parser().setSigningKey(SECRET).parseClaimsJws(token.replace("Bearer" + " ", "")).getBody().getSubject(); -> OK as expected, Exception: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.

**Comment by bhowell2** [comment]
This has been answered multiple times in the issues (e.g., #128 ). It has to do with Base 64 encoding. If you want to use a string like that, you must Base64 encode it first.

This would not work as expected:

```java
    final String SECRET = Base64.getEncoder().encodeToString("ThisIsASecret".getBytes());
    String token = Jwts.builder()
                     .setSubject("username")
                     .setExpiration(new Date(System.currentTimeMillis() + 864_000_000))
                     .signWith(SignatureAlgorithm.HS512, SECRET)
                     .compact();

    // passes
    final String SECRET1 = Base64.getEncoder().encodeToString("ThisIsASecret".getBytes());
    String user = Jwts.parser().setSigningKey(SECRET1).parseClaimsJws(token).getBody().getSubject();

    // fails
    final String SECRET2 = Base64.getEncoder().encodeToString("ThisIsASecretf".getBytes());
    String user2 = Jwts.parser().setSigningKey(SECRET2).parseClaimsJws(token).getBody().getSubject();

    // fails
    final String SECRET3 = "ThisIsASecretff";
    String user3 = Jwts.parser().setSigningKey(SECRET3).parseClaimsJws(token).getBody().getSubject();

    //fails
    final String SECRET4 = "ThisIsASecretfff";
    String user4 = Jwts.parser().setSigningKey(SECRET4).parseClaimsJws(token).getBody().getSubject();
```

**Comment by lhazlewood** [comment]
Closing per response above.  Thanks @bhowell2 !
