### ISSUE TITLE
Update Jackson Deserializer

### ISSUE THREAD

**Issue by Staryjir** [jwtk/jjwt#255]
Can you please make a new version with updated the jackson databind library? - it may contains a security vulnerability - see below

https://github.com/FasterXML/jackson-databind/issues/1599

**Comment by harshilsharma63** [comment]
Any update on this?

**Comment by dogeared** [comment]
The latest master uses `2.8.9`. I will look into getting a release out this week.

**Comment by dogeared** [comment]
[0.8.0](http://search.maven.org/#artifactdetails%7Cio.jsonwebtoken%7Cjjwt%7C0.8.0%7Cjar) has just been released which includes the jackson version bump (among others)
