### ISSUE TITLE
gradle error

### ISSUE THREAD

**Issue by graemefunk87** [jwtk/jjwt#26]
I'm getting this error when trying to install your plugin

Could not transfer artifact io.jsonwebtoken:jjwt:zip:0.4 from/to m2repo_spockframework_org_ext_ (http://m2repo.spockframework.org/ext/): m2repo.spockframework.org (Use --stacktrace to see the full trace)

I've tried googling around and can't figure this out, and I'm new to the gradle game so any help would be awesome!

**Comment by lhazlewood** [comment]
did you include maven central in  your repositories config?

```gradle
repositories {
    mavenLocal()
    mavenCentral()
}
```

**Comment by graemefunk87** [comment]
not sure what I changed, but I finally got it to resolve, sorry about the inconvenience
