### ISSUE TITLE
Google JSON file

### ISSUE THREAD

**Issue by bdbais** [jwtk/jjwt#264]
Could you write a method for receiving in input a Google credential file .json?
or directly by json object or string ?

like: 
Key key = Macprovider.JSON("....");
like Key key = Macprovider.JSON(File handler);

Thx

**Comment by lhazlewood** [comment]
I'm sorry, but this is currently out of scope for this project.   JJWT is currently *strictly* limited to an implementation of the JWT RFCs and nothing more.  If enough others ask for this feature, it's always a possibility we'll add it in the future.
