### ISSUE TITLE
How do you use this in Windows?

### ISSUE THREAD

**Issue by totszwai** [jwtk/jjwt#273]
Is there a way to use this in Windows? 

This is the error I'm getting when I try to pass the ProvateKey to jjwt:

`The specified key of type sun.security.mscapi.RSAPrivateKey is not an RSA PrivateKey.`

**Comment by lhazlewood** [comment]
Your RSA key implementation does not implement the JDK-standard interfaces:

* `java.security.PrivateKey`
* `java.security.interfaces.RSAKey`
or:
* `java.security.interfaces.RSAPrivateKey`

Your `PrivateKey` implementation must implement these interfaces to function correctly.

It is recommended that you wrap your `sun`-specific implementation with one that implements the `java.security.interfaces.RSAPrivateKey` interface and that will cover all of your bases.  For example:

```java
public class StandardRsaPrivateKey implements java.security.interfaces.RSAPrivateKey {
    
    private final sun.security.mscapi.RSAPrivateKey target;

    public StandardRsaPrivateKey(sun.security.mscapi.RSAPrivateKey target) {
        this.target = target;
    }

    //implement the other methods and delegate to the `target` instance.  For example:
    @Override
    public BigInteger getModulus() {
        return this.target.getModulus();
    }

    //do the same for all remaining methods.
}
```

Then you can wrap your sun PrivateKey with this instance

```java
sun.security.mscapi.RSAPrivateKey platformSpecific = getWindowsPrivateKey(); //implement me

java.security.interfaces.RSAPrivateKey goodKey = 
    new StandardRsaPrivateKey(platformSpecific);
```

Then you can use the `goodKey` instance with the builder:

```java
Jwts.builder().signWith(SignatureAlgorithm.RS256, goodKey)
     // ... etc ...
     .build();
```

In the future, please ask usage questions on https://stackoverflow.com - we use GitHub issues only for actionable work on the codebase itself, not for general questions.  Thanks!
