### ISSUE TITLE
Add ECCN notice

### ISSUE THREAD

**Issue by otramony** [jwtk/jjwt#275]
Hello. Our team would like to use/include your library in our product, and since we export outside of the U.S., we're required to provide ECCN (Export Control Classification Number) information for all 3rd-party libraries that may use/include encryption.

**Comment by lhazlewood** [comment]
Hello - we currently do not have an ECCN since we haven't applied for it.  If we did apply, I suspect it would be categorized as 5D002.C.1

**Comment by lhazlewood** [comment]
P.S. It is unclear to me if we need to file or not - JJWT provides wrapper functions around the JDK, and the JDK (or BouncyCastle, if you use it) is the one that actually performs the encryption or signature calculations.

**Comment by otramony** [comment]
Hi Les. My understanding is that you wouldn't need it if that's the case with the wrapping functions. However, if you want to confirm this for JJWT, please reach out to your legal team. Thank you for your time and for responding.

**Comment by lhazlewood** [comment]
@otramony I did some deep diving/research and JJWT would indeed be categorized as `5D002.C.1`. I hope that helps!

**Comment by ramonyoung7** [comment]
Great! Thanks a lot.

**Comment by lhazlewood** [comment]
internal note: leaving this open to track the work for adding an ECCN notice to the readme (or similar).  Will be done with the 0.10. release
