### ISSUE TITLE
jwt token error-Getting signature exception

### ISSUE THREAD

**Issue by sreelekshmikp** [jwtk/jjwt#276]
Below m code for generating and decoding the token, But getting the following error. Please help.

io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:354)

Make Token
-----------------------------
String token = Jwts.builder()
        .setSubject(((User) auth.getPrincipal()).getUsername())
        .signWith(SignatureAlgorithm.HS512, SECRET.getBytes("UTF-8"))
        .compact();
        res.addHeader(HEADER_STRING, TOKEN_PREFIX + token);

Decoding token
--------------------------
 String token = request.getHeader(HEADER_STRING);
        if (token != null) {
            // parse the token.
        	
            String jwt = token.replace(TOKEN_PREFIX, "");
			try {
				Claims claims = Jwts.parser()
                .setSigningKey(SECRET.getBytes("UTF-8"))
                .parseClaimsJws(jwt)
                .getBody();
				if (claims.getSubject() != null) {
	                return new UsernamePasswordAuthenticationToken(claims.getSubject(), null, getAuthorities());
	            }
			}

**Comment by lhazlewood** [comment]
Do you have a JUnit test case method that you can copy-and-paste (using a different `SECRET` value of course) so we can try to re-create this?

**Comment by sreelekshmikp** [comment]
I found out the issue, While taking the Bearer token from Rest Client(plugin in Mozilla) The next line is coming as an extra space.
--
