### ISSUE TITLE
convenience method for setting expiration date on JWTSBuilder not working properly

### ISSUE THREAD

**Issue by hebront** [jwtk/jjwt#277]
When using the setExpirationDate convenience method on the JWTBuilder as per doc-o : 

* <p>This is a convenience method.  It will first ensure a Claims instance exists as the JWT body and then set
     * the Claims {@link Claims#setExpiration(java.util.Date) expiration} field with the specified value.  This allows
     * you to write code like this:</p>
     *
     * <pre>
     * String jwt = Jwts.builder().setExpiration(new Date(System.currentTimeMillis() + 3600000)).compact();
     * </pre>
     *

**# Returns a date around Jan 1, 1970**

**Comment by lhazlewood** [comment]
I don't see how this code returns a date of Jan 1, 1970.  If you're going to submit a bug, please create a code snippet that demonstrates the problem.

**Comment by hebront** [comment]
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.SignatureAlgorithm;
import io.jsonwebtoken.impl.crypto.MacProvider;

import java.security.Key;
import java.util.Date;

/**
 * Created by thebron on 10/13/2017.
 */
public class Tester {


    public String token(){
        // We need a signing key, so we'll create one just for this example. Usually
        // the key would be read from your application configuration instead.
        Key key = MacProvider.generateKey();

        String compactJws = Jwts.builder()
                .setExpiration(new Date(System.currentTimeMillis()))
                .setSubject("Joe")
                .signWith(SignatureAlgorithm.HS512, key)
                .compact();

        return compactJws;
    }

    public static void main(String args[]){

        Tester t= new Tester();
        System.out.println(t.token());
    }
}

The above code returns 
eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE1MTAyMjgwNzUsInN1YiI6IkpvZSJ9.jfD3v32anc1xG74vr3rgnzCPySVsBIJprdJVX2LgsEt4TWsOneXxhKbp5YkjmOs1z4ebGk2JaqGhQQ-nmN_wEw

And the "exp" is 
![image](https://user-images.githubusercontent.com/33470315/32604148-99089280-c51a-11e7-8230-2efff511b9ac.png)

And the time is 
![image](https://user-images.githubusercontent.com/33470315/32604164-a97f7a98-c51a-11e7-9fbf-93978b5e55fb.png)

**Comment by lhazlewood** [comment]
I'm afraid you are mistaken.  The JWT specification requires the `exp` value to be in *seconds* since epoch, not milliseconds.
