### ISSUE TITLE
Allow parsing signed JWTs without the key

### ISSUE THREAD

**Issue by sithmein** [jwtk/jjwt#280]
As a client I want to parse a JWT received from a server to inspect the contents. The JWT is signed by the server and obviously I don't have the secret signing key. Currently it's not possible to simply parse a JWT and ignore the signature (except by manually stripping the signature from the string). The library should offer a way to simply ignore the signature while parsing and not require the signing key.

**Comment by danjee** [comment]
+1

**Comment by kojotak** [comment]
There is a workaround described in https://stackoverflow.com/questions/34998859/android-jwt-parsing-payload-claims-when-signed - just replace the signature with empty string

**Comment by ardmn** [comment]
You are right . WTF I think. Why ?  @kojotak, thanks for advise.

**Comment by dereekb** [comment]
I ran into the same issue, and followed through these threads and ran into a few issues/exceptions, but figured out you can easily get the body of the jwt using the parse() function from the DefaultJwtParser.

```
public Claims decodeTokenClaims(String token) {
	String[] splitToken = token.split("\\.");
	String unsignedToken = splitToken[0] + "." + splitToken[1] + ".";

	DefaultJwtParser parser = new DefaultJwtParser();
        Jwt<?, ?> jwt = parser.parse(unsignedToken);
        Claims claims = (Claims) jwt.getBody();
	return claims;
}
```

This skips the signature validation, but still checks that the token is not expired and returns the body as a Claims object.

**Comment by lhazlewood** [comment]
Closing as a duplicate of #86 

Also @sithmein, the solution to your problem is not using HMAC because that is a shared secret.  Use asymmetric keys (RSA, EllipticCurve) and your client can verify the server's signature just fine.  That is the correct solution for that particular use case.

**Comment by ratulSharker** [comment]
> I ran into the same issue, and followed through these threads and ran into a few issues/exceptions, but figured out you can easily get the body of the jwt using the parse() function from the DefaultJwtParser.
> 
> ```
> public Claims decodeTokenClaims(String token) {
> 	String[] splitToken = token.split("\\.");
> 	String unsignedToken = splitToken[0] + "." + splitToken[1] + ".";
> 
> 	DefaultJwtParser parser = new DefaultJwtParser();
>         Jwt<?, ?> jwt = parser.parse(unsignedToken);
>         Claims claims = (Claims) jwt.getBody();
> 	return claims;
> }
> ```
> 
> This skips the signature validation, but still checks that the token is not expired and returns the body as a Claims object.

`DefaultJwtParser();` this constructor is been deprecated. 

How to parse signed JWTs without the key ?

**Comment by dereekb** [comment]
> > I ran into the same issue, and followed through these threads and ran into a few issues/exceptions, but figured out you can easily get the body of the jwt using the parse() function from the DefaultJwtParser.
> > ```
> > public Claims decodeTokenClaims(String token) {
> > 	String[] splitToken = token.split("\\.");
> > 	String unsignedToken = splitToken[0] + "." + splitToken[1] + ".";
> > 
> > 	DefaultJwtParser parser = new DefaultJwtParser();
> >         Jwt<?, ?> jwt = parser.parse(unsignedToken);
> >         Claims claims = (Claims) jwt.getBody();
> > 	return claims;
> > }
> > ```
> > 
> > 
> > This skips the signature validation, but still checks that the token is not expired and returns the body as a Claims object.
> 
> `DefaultJwtParser();` this constructor is been deprecated.
> 
> How to parse signed JWTs without the key ?

Been a while since I touched a project using this, but looks like with my project I updated to version 0.10.7 and just got the parser from `Jwts.parser();`.

```
private static final JwtParser DEFAULT_PARSER = Jwts.parser();

public Claims decodeTokenClaims(String token) {
	String[] splitToken = token.split("\\.");
	String unsignedToken = splitToken[0] + "." + splitToken[1] + ".";

	Jwt<?, ?> jwt = DEFAULT_PARSER.parse(unsignedToken);
	Claims claims = (Claims) jwt.getBody();
	return claims;
}
```

**Comment by ratulSharker** [comment]
@dereekb i am using [0.11.2](https://github.com/jwtk/jjwt#install-jdk-maven). From [here](https://github.com/jwtk/jjwt/blob/71ed1b67aafacb3a7383ee8de659023292a89135/api/src/main/java/io/jsonwebtoken/Jwts.java#L119) i came to know that `Jwts.parser()` became deprecated and documented to use `parserBuilder()`. 

I tried with `parserBuilder()`. I tried with a signed token with it's signature part chopped off !!! as follows

```java
public Claims decodeToken(String token) throws JwtException {
    String[] splitToken = token.split("\\.");
    String unsignedToken = splitToken[0] + "." + splitToken[1] + ".";
    
    Jws<Claims> parsedToken = Jwts.parserBuilder().build().parseClaimsJws(unsignedToken);
    return parsedToken.getBody();
}
```

which throws following error

> io.jsonwebtoken.UnsupportedJwtException: Unsigned Claims JWTs are not supported.
	at io.jsonwebtoken.JwtHandlerAdapter.onClaimsJwt(JwtHandlerAdapter.java:40)
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:563)
	at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:610)
	at io.jsonwebtoken.impl.ImmutableJwtParser.parseClaimsJws(ImmutableJwtParser.java:173)

**Comment by dereekb** [comment]
My guess is that was added to follow spec and prevent bugs from passing through on peoples apps.

You can either downgrade to a previous version (unless you needed features in 11), or re-implement (copy paste) the claims decoding code.

Here's the current code:
https://github.com/jwtk/jjwt/blob/72973f9b9ba72438d97834db2bd56e36d3c48592/impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtParser.java#L304

You could try opening up a new ticket and ask about them moving the header/body/claims decoding to an external class, since those variables seem localized to the code I linked above.

Then again, their stance on JWT is you should always verify a JWT's signature, and avoiding the cryptographic signing may going against their goals for the project:

https://github.com/jwtk/jjwt#signature-algorithms-keys

`
This is not because we want to make your life difficult, we promise! The reason why the JWT specification, and consequently JJWT, mandates key lengths is that the security model of a particular algorithm can completely break down if you don't adhere to the mandatory key properties of the algorithm, effectively having no security at all. No one wants completely insecure JWTs, right? Neither would we.
`

**Comment by gaetjen** [comment]
@ratulSharker
To parse the header and body without signature verification on 11.2 you can use `Jwts.parserBuilder().build().parseClaimsJw**t**(unsignedToken)`.

**Comment by git9999999** [comment]
@gaetjen Thanks for the solution :-)
Here is an example for you code
```
private static String getAuthorizationHeadersClaims(LinkedHashMap<String, JSONArray> headers) {
        var authorizationHeadersClaims = "";
        if (not(headers.isEmpty())) {
            var authorizations = headers.get("authorization");
            if (authorizations != null && not(authorizations.isEmpty())) {
                var jwt = (String) authorizations.get(0);
                if (jwt != null) {
                    var token = StringUtils.substringAfter(jwt, " ");
                    String[] splitToken = token.split("\\.");
                    String unsignedToken = splitToken[0] + "." + splitToken[1] + ".";
                    var claims =  Jwts.parserBuilder().build().parseClaimsJwt(unsignedToken);
                    authorizationHeadersClaims = claims.toString();
                }
            }

        }
        return authorizationHeadersClaims;
    }
```

**Comment by akahenry** [comment]
> @ratulSharker To parse the header and body without signature verification on 11.2 you can use `Jwts.parserBuilder().build().parseClaimsJwt(unsignedToken)`. (note **t** instead of **s** in the parseClaims function)

Apparently since 0.12 the `parse` method requires the signature which means that this won't work.

Does anyone have any idea how to keep getting the claims without the need of a signature?

**Comment by git9999999** [comment]
I can not use the NONE solution, as i have another use case.

I my use case i need the parsing of the JWT for logging and audit. To validate the Signature is not relevant to me. 

Currently i do not see a way to achieve that.

@lhazlewood please could you suggest a solution :-)

**Comment by git9999999** [comment]
@bdemers My application does intercept REST request to other application. I store the Request in a DB and try also to store additional metadata to the requests. One of that data are the Claims of the JWT token. 
I do not have access to any Public Keys. It is also no requirement to validate the signature. 

I know that my requirements are against all security advice out there, but it is as it is. :-)

I hope you I could show you my use case. If you have any more questions, just let me know.

**Comment by bdemers** [comment]
@git9999999,
Security issues aside (as to which there are many!) **I don't recommend this doing this**

But a JWS (a signed JWT) is basically a section of three strings separated by a period:

```
<header>.<payload>.<signature>
```

Each of those sections is base64 url encoded, so could either:
1. decode the middle section and assume it's JSON, and parse it with a JSON lib
2. Remove the signature, and replace the header with a known one: `base64-url {"typ":"JWT","alg":"none"}`, parse it with JJWT

This is often useful for debugging and testing, but again, i'd recommend against doing this in a production application

**Comment by git9999999** [comment]
@bdemers Thanks for the advice, I will do it like you proposed.
