### ISSUE TITLE
java.lang.IllegalArgumentException: bad base-64

### ISSUE THREAD

**Issue by anshdiv** [jwtk/jjwt#287]
try {
                        Jws<Claims> claims  = Jwts.parser().setSigningKey("IamSingleBitch@582").parseClaimsJws(response);
                        Log.e("Jwt claims",claims.getBody().toString());
                        //OK, we can trust this JWT

                    } catch (Exception e) {
                        //don't trust the JWT!
                        e.printStackTrace();
                        Log.e("Jwt error","fdjf");
                    }

**Comment by lhazlewood** [comment]
This will be addressed as part of #333.  Please follow that issue for related work.
