### ISSUE TITLE
Expiry date of token expressed in seconds, however milliseconds are expected

### ISSUE THREAD

**Issue by Ben-Hermans** [jwtk/jjwt#289]
Dear,

When passing my expiration date to the setExpiration method of the DefaultJwtBuilder class, it seems that somewhere down the line, the time expressed as milliseconds is converted to seconds (setDate method of JwtMap class). This makes that the value of my expiration date is stored as the value expressed in seconds. 

When decoding the token, the expiration date is now a value in seconds, whereas one would expect it to be expressed in miliseconds. This is leading to incorrect expiration dates when the client is handling the token.

If any additional information is required, please let me know.
Thanks for considering.

**Comment by mbeattie** [comment]
The "exp" registered claim is in seconds according to the spec.

https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32#page-9
Its value MUST be a number containing a NumericDate value.

https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32#page-6
NumericDate
      A JSON numeric value representing the number of seconds from 1970-
      01-01T00:00:00Z UTC until the specified UTC date/time, ignoring
      leap seconds.

**Comment by Ben-Hermans** [comment]
Hi @mbeattie,

Thank you for the answer. I expected this to be mentioned in the readme. When I couldn't find it I did some additional research, but didn't come up with the idea to check the official JWT spec.
