### ISSUE TITLE
Invalidating JWTs on sign out?

### ISSUE THREAD

**Issue by hotmeatballsoup** [jwtk/jjwt#296]
I'm new to JWT and was wondering if it is possible to invalidate/void JWTs on the server-side when a user signs out of an application (I'm also wondering if it even *makes sense* to do so!). Idea is:

1. User clicks a sign out link in their app
2. App makes a call to `POST https://api.myapp.example.com/auth/invalidate`
3. The JWT (which is an authorization/bearer token in the HTTP request header) is somehow invalidated
4. Now, no one can ever use that JWT again

I'm not sure if this is an unorthodox approach to signout logic or not, or whether its acceptable to just let the JWT linger as valid, even after the user signs out (I guess I could shorten the life of the JWT expiry to, say, 60 mins or something).

So again: wondering if its possible to do this kind of "*invalidation*" using JJWT (and if so, **how?!**) as well as whether it even makes sense to do this (and if not, what does a typical signout flow look like?!). Thanks!

**Comment by Bragolgirith** [comment]
Related info: https://github.com/jwtk/jjwt/issues/201

**Comment by lhazlewood** [comment]
Just a friendly note:  GitHub Issues are used to track actionable work to change the JJWT codebase.  Please ask usability questions on StackOverflow using the `#jjwt` tag.  Thanks!

**Comment by bitbythecron** [comment]
Thanks @lhazlewood -- [here you go!](https://stackoverflow.com/questions/51272360/can-jjwt-invalidate-tokens-on-the-server-side)
