### ISSUE TITLE
Remove usage of javax.xml.bind.DatatypeConverter (removed in Java 9) 

### ISSUE THREAD

**Issue by gregoryalary** [jwtk/jjwt#297]
JDK9 marks the package javax.xml.bind as deprecated for removal.

The current use results in a java.lang.NoClassDefFoundError :

`Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at io.jsonwebtoken.impl.Base64Codec.decode(Base64Codec.java:26)
	at io.jsonwebtoken.impl.DefaultJwtBuilder.signWith(DefaultJwtBuilder.java:99)`

**Comment by dachristensen** [comment]
I ran into this as well. I just submitted a pull request that resolves this, but breaks the build for java7 as it leverages java.util.Base64 which was added in Java8. As such, I closed the pull request myself. If jjwt needs to support java7, then I'm not sure of a good way to get around this without adding an external dependency on something like commons-codec.

**Comment by RyanBard** [comment]
You can also fix the problem by explicitly depending on jaxb:
* https://github.com/jwtk/jjwt/issues/282
* https://github.com/jwtk/jjwt/pull/283/files

**Comment by lhazlewood** [comment]
Closing as a duplicate of #333.  Work will be tracked via that issue and we hope to have that released asap in the coming days.  Thanks to @RyanBard for the jaxb optional dependency pointer!

**Comment by lhazlewood** [comment]
This has been fixed and released in 0.10.0.
