### ISSUE TITLE
JWT Infinite loop on sign

### ISSUE THREAD

**Issue by jorexe** [jwtk/jjwt#298]
Hi, i'm trying to generate a jwt but i get stucked at signWith method. This is my code:

	Claims claims = Jwts.claims().setExpiration(expCal.getTime()).setIssuer(LAYER_PROVIDER_ID).setIssuedAt(new Date()).setSubject("my-api");
	Header header = Jwts.jwsHeader().setType("JWT").setContentType("layer-eit:v=1").setCompressionAlgorithm("RS256");
	JwtBuilder builder = Jwts.builder()
			.setId(UUID.randomUUID().toString())
			.setClaims(claims)
			.claim("alg", "RS256")
			.claim("kid", LAYER_KEY_ID)
			.setHeader((Map<String, Object>) header)
			.setHeaderParam("prn", LAYER_SERVER_ID)
			.setHeaderParam("nce", nonce)
			.signWith(SignatureAlgorithm.RS256, MY_PRIVATE_KEY);
	return builder.compact()

I'm working with this doc

https://docs.layer.com/reference/client_api/authentication.out#identity-token

Thanks you!

**Comment by lhazlewood** [comment]
What is the data type of `MY_PRIVATE_KEY` ?

**Comment by jorexe** [comment]
Hi @lhazlewood, it was a problem with my private key. Thanks you!
