### ISSUE TITLE
Adds \ to JSON

### ISSUE THREAD

**Issue by asirazhi** [jwtk/jjwt#299]
Hey, I am trying to parse a JSON. The code is below.
        ```
Gson gson = new Gson();
        String accountJson= gson.toJson(account);
String accountJws = Jwts.builder()
                .setSubject(accountJson)
                .signWith(SignatureAlgorithm.HS512, "fhdskjfeksldfkdsnvdsnvndsvndsv")
                .compact();
        log.info("accountJson:" + accountJson);
        log.info("accountJws:" + accountJws);
```

As the result it gives:

> accountJson:{"name":"John","surname":"Smith"}
>accountJws: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ7XCJuYW1lXCI6XCJKb2huXCIsXCJzdXJuYW1lXCI6XCJTbWl0aFwifSJ9.W5UZ6LTcaeLQaxOfdwku_wrsu9THmnrlSNgOmRwW0f3rvEvGNBDyINcAAcQiVV5c8MeCt3Oyj5YVPNSier0i8g

When I put the Jws into jwt.io/#debugger it gives 

>  {
>  "sub": "{\"name\":\"John\",\"surname\":\"Smith\"}"
>}

So it replaces " with \" and adds "sub". Is there any approach so that jwt.io/#debugger will give the same result as the initial JSON?

**Comment by lhazlewood** [comment]
You're setting a JSON object escaped as a string as a JSON value.   Escapes are expected.

Please note that GitHub issues are for actionable work to change the JJWT codebase.  For API or usage help, please ask questions on StackOverflow.com and use the `#jjwt` tag.  Thanks!
