### ISSUE TITLE
what is apiKey.getSecret()

### ISSUE THREAD

**Issue by bluesnail95** [jwtk/jjwt#300]
byte[] apiKeySecretBytes = DatatypeConverter.parseBase64Binary(apiKey.getSecret());

execuse me ,could you tell me what is apiKey.where is this class?

**Comment by SasinduJayashma** [comment]
Did u find an answer for this?

**Comment by bluesnail95** [comment]
no, I don't .

**Comment by lhazlewood** [comment]
I'm not sure where you saw that - maybe on StackOverflow?

It's just an example of using an API Key in a 3rd party SDK to communicate with a web service.  That api key, if it is a secure-random byte array, can also be a reasonable candidate to use as a signing key for creating JWTs.  There is no `apiKey` concept in JJWT - it was just an example of using a suitable byte array as a signing key.

Just a minor reminder - GitHub is for actionable work by the JJWT team.  If you have questions, please use StackOverflow.com and use the `jjwt` tag in your question.  Thanks!
