### ISSUE TITLE
Security Vulnerability - Jackson

### ISSUE THREAD

**Issue by aabashkin** [jwtk/jjwt#302]
Please upgrade to Jackson databind 2.8.11 or 2.9.4 to address an important security vulnerability: https://github.com/FasterXML/jackson-databind/issues/1904

**Comment by RyanBard** [comment]
PR: https://github.com/jwtk/jjwt/pull/306

**Comment by glebsts** [comment]
Can it be prioritized, mb minor version release? Quite scary to live with that.

**Comment by lhazlewood** [comment]
We'll get it out when we can, for sure.  In the meantime, the quick workaround is using a maven [<exclude> directive](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html#) when depending on JJWT and then explicitly using the Jackson version you want to as a runtime dependency.

**Comment by lhazlewood** [comment]
Merged to 0.9.x branch pending release.

**Comment by lhazlewood** [comment]
0.9.1 has been released.  Please allow 15-30 minutes for the release to propagate to Maven Central.
