### ISSUE TITLE
Keys generated by this library are not valid according to https://jwt.io/

### ISSUE THREAD

**Issue by monzonj** [jwtk/jjwt#307]
For instance, take this example:

```
import io.jsonwebtoken.*;
import io.jsonwebtoken.impl.crypto.MacProvider;

import java.security.Key;

public class Test {
    public static void main(String ... args){
        String key = "secret";

        String compactJws = Jwts.builder()
                .setSubject("Joe")
                .signWith(SignatureAlgorithm.HS256, key)
                .compact();

        System.out.println(compactJws);
    }
}
```
The output is:
```
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKb2UifQ.XIKER3owR8BS3Krhsksg9INh9VBSejdn_qN-ONtPans
```

When validating this token at https://jwt.io/ it says the signature is not correct (see attached screenshot)

Am I doing something wrong? or is this library not JWT compliant?

![json_web_tokens_-_jwt_io](https://user-images.githubusercontent.com/986520/36911401-b89aa890-1e43-11e8-9f95-a6a14e08b593.png)

**Comment by monzonj** [comment]
Ok, the key must be base64 encoded, as the "signwith" method declares. Sorry for that.

This is the good example:

import io.jsonwebtoken.*;
import io.jsonwebtoken.impl.TextCodec;

```
public class Test {
    public static void main(String ... args){
        String key = "secret";

        String compactJws = Jwts.builder()
                .setSubject("Joe")
                .signWith(SignatureAlgorithm.HS256, TextCodec.BASE64.encode(key))
                .compact();

        System.out.println(compactJws);
    }
}
```

**Comment by lhazlewood** [comment]
Just in case others come across this:

jwt.io is not a JWT authority.  They're just a website run by a company who has time and again shown examples using insecure keys.  The string literal `secret` is not a cryptographically valid signing key for JWT's HMAC algorithms, and that company is being negligent even showing that in an example.  Don't just blindly trust that website - they've previously made implementation and security flaws in their implementations.

Please read the `JwtBuilder` `signWith` JavaDoc.  It explains that any string is expected to be a Base64-encoded byte array, not a spoken-language string. :)

Additionally, please read this [StackOverflow answer on keys and key lengths required for cryptographic security strength](https://stackoverflow.com/questions/40252903/static-secret-as-byte-key-or-string/40274325#40274325) that explains why the string literal `secret` and any other similar strings should not be used.
