### ISSUE TITLE
Remove jackson dependency ?

### ISSUE THREAD

**Issue by christopheblin** [jwtk/jjwt#309]
From what I understand, jjwt only use jackson to convert json into Map<String, Object> (object being used sometimes for Dates) and to seraialize the Map<String, object> back to json. Nothing complicated is used (like JsonIgnore, registering mapper and other tricks)

So my question is : why jjwt does not rely directly on an embedded json impl (like org.json) ?

The use case are :
* using jjwt in a project where another json lib is used (especially another older version of jackson...)
* no need to upgrade jjwt when jackson has an issue
* jjwt would truly be a microlib (Jackson is a fat library, around 1.4Mo)

If that is possible, I can try to work on a PR

**Comment by aadrian** [comment]
@christopheblin the statement from Jackson was that it's faster.

**Comment by christopheblin** [comment]
@aadrian  well that is probably true for big payload, but JWT is not used in that case I suppose (the diff should be negligible).

And if you really want that, then I think you should modify DefaultJwtParser to use a static ObjectMapper (like in DefaultJwtBuilder)

**Comment by aadrian** [comment]
@christopheblin AFAIK org.json is not optimized at all, independent of the payload size. It's also important how often that payload is checked :) .

**Comment by christopheblin** [comment]
@aadrian Yes true, org.json is not optimized but, at the moment, the usage of jackson is incorrect and I think it is slower than any other lib (i.e there should be a single instance of the ObjectMapper)

**Comment by tgeens** [comment]
@christopheblin has no issue with performance, but with the jackson dependency on the classpath ?

**Comment by christopheblin** [comment]
@tgeens  Yes that is exactly my problem (need 1.4Mo of jackson to use the 110ko of jjwt...). That is not really a big deal nor a criticism to jjwt, just something not very clean :)

**Comment by cptwunderlich** [comment]
We are already using gson in our project and now that we are adding jjwt, it also pulls in jackson. I think some libraries solve this by providing "bridge packages", e.g., jjwt-core + jjwt-gson/jjwt-jackson - and org.json could be used as a fallback.

**Comment by tgeens** [comment]
There is no need to have additional "bridge packages".

Modern Spring (Boot) applications detect and use what is already available
on the classpath.

Example - detect Jackon2:



*private static final boolean jackson2Present =
ClassUtils.isPresent("com.fasterxml.jackson.databind.ObjectMapper",
RestTemplate.class.getClassLoader()) &&
ClassUtils.isPresent("com.fasterxml.jackson.core.JsonGenerator",
RestTemplate.class.getClassLoader());*

and in the constructor:



*if (jackson2Present) {   this.messageConverters.add(new
MappingJackson2HttpMessageConverter());}*
*else ...*

And the rest of the lib can use the *MessageConverter* interface.

This implies a compile-time dependency on Jackson2 to compile
*MappingJackson2HttpMessageConverter
*- but declare that dependency as 'provided'.
If it's not available at run-time, no problem, use something else available
on the classpath, fallback to org.json or throw an error!


Kind regards,

Toon Geens

**Comment by lhazlewood** [comment]
@tgeens is right - we do this technique today for BouncyCastle for example.  We can definitely extend this approach to the JSON parser.   Even so, we should still allow for an override (e.g. `Jwts.parser().setJsonMapper(JsonMapper mapper)` where `JsonMapper` is a jjwt interface that can be implemented to delegate to the json api of choice.  I'm not sure if `JsonMapper` is the best name (I'm just thinking out loud), but that's just an example.

**Comment by lhazlewood** [comment]
Closing this issue in favor of tracking this work as #335.  Please continue the discussion in that thread if desired.

**Comment by lhazlewood** [comment]
For those following this thread, Jackson is now optional and you can choose your own implementation in 0.10.0.  There is a JSON-Java (`org.json`) implementation as well which can work natively on Android without any additional dependencies.  Please see the Readme docs for more information.

**Comment by patton73** [comment]
Is there also an implementation that relies on gson library. I mean Google com.google.json library?
Thanks.
