### ISSUE TITLE
Access to object mapper

### ISSUE THREAD

**Issue by rs-renato** [jwtk/jjwt#310]
Shouldn't necessary to expose the ObjectMapper contained into `DefaultJwtParser`? Or, necessary to let me configure this object mapper?

For example, I  need to have a custom jwt output (omit null values, empty values, etc, may be generate the token in UpperCamelCase..) and for while, I can't do it because the object mapper isnt public.

So, I think it's necessary to let me configure the object mapper on my own or let me custom it.

There is any way to do it (customize the output) without access to this object mapper?

**Comment by lhazlewood** [comment]
Closing in favor of tracking this as #335.  Please add further comments or discussion to that issue.  Thanks!
