### ISSUE TITLE
clear some warnings

### ISSUE THREAD

**Issue by aharonha** [jwtk/jjwt#313]
When cloning the project using eclipse it shows a lot of warnings.
Some of them are just missing generics tags

**Comment by lhazlewood** [comment]
This is IDE-specific, and not in scope for the JJWT codebase (i.e. it doesn't impact JJWT users in any way).  The JJWT developers use IntelliJ.

That said, if you have a PR to issue that modifies the code accordingly, we'd definitely be open to reviewing it.   I'm closing this issue in the meantime, but feel free to open a PR with those changes.
