### ISSUE TITLE
Different signature for the same payload and header between jjwt and nimbus

### ISSUE THREAD

**Issue by nmDejamobile** [jwtk/jjwt#314]
Hi,

My server part uses the Nimbus library (https://bitbucket.org/connect2id/nimbus-jose-jwt/) and I'm trying to use JJWT on the Android mobile part.

But for the same signing algorithm, apiKey and payload, we obtain a different signature.
Then my generated JWT token with JJWT can't be verified on the server part that use Nimbus.

I then tried to implement both JJWT and Nimbus on the Android part to see the difference :

## Common parts for both implementations :
API key: **94da642fa8fba9c8f03d6f30cb70ed4911d35e887fea4efd3db74bc4273c6972**

JSON string representation of the following requestBody object used as payload: 
```
{
  "hceTechnicalId": "AB4B664E4C1CBA8B4FA6B016AAC312330EEE74A9CB74177A295097DBC7CC0E80",
  "idpar2": "fGb3nCVYh8",
  "numcr": "20000"
}
```
## Code for JJWT implementation :
```
Gson gson = new Gson();
String jjwtString = Jwts.builder()
  .setPayload(gson.toJson(requestBody))
  .signWith(SignatureAlgorithm.HS256, apiKey)
  .compact();
```

> jjwtString: eyJhbGciOiJIUzI1NiJ9.eyJoY2VUZWNobmljYWxJZCI6IjVEQjk5RDFFMUUzQzdCNzBDNTRBQkNERkM4NkM4NUQ3MEZFRkM3QUMzRUJBMzY5NUM0MzlCNEI1QTQ3NDBEQkUiLCJpZHBhcjIiOiJIUEVBaXZaV2VlIiwibnVtY3IiOiIyMDAwMCJ9.**GZRpso87ueKYKskN1FWf6FN-hT41bJU1yeikTmYFWVw**

## Code for Nimbus implementation :
```
Gson gson = new Gson();
JWSSigner signer = new MACSigner(apiKey);
JWSObject jwsObject = new JWSObject(new JWSHeader(JWSAlgorithm.HS256), new Payload(gson.toJson(requestBody)));
String nimbusdsString = jwsObject.sign(signer);
```

> nimbusdsString: eyJhbGciOiJIUzI1NiJ9.eyJoY2VUZWNobmljYWxJZCI6IjVEQjk5RDFFMUUzQzdCNzBDNTRBQkNERkM4NkM4NUQ3MEZFRkM3QUMzRUJBMzY5NUM0MzlCNEI1QTQ3NDBEQkUiLCJpZHBhcjIiOiJIUEVBaXZaV2VlIiwibnVtY3IiOiIyMDAwMCJ9.**CQNayiPVTZFI8zDPYPU5kBqxcIkM3DDc9pkGTlQCQw8**

I tried lowercase and uppercase of the api key and it also fails.

Also using https://jwt.io/#debugger the Nimbus signature seems to match but not the JJWT one.

Dependencies used are : 
-    implementation 'io.jsonwebtoken:jjwt:0.9.0'
-    implementation 'com.nimbusds:nimbus-jose-jwt:5.2'

Android app has the following versions:
- COMPILE_SDK_VERSION=27
- BUILD_TOOLS_VERSION=27.0.3
- MIN_SDK_VERSION=21
- TARGET_SDK_VERSION=26

**Comment by lhazlewood** [comment]
Your API Key string is not a Base64-encoded byte array.  Please read the JavaDoc for `signWith` and see what the 2nd argument is supposed to be.

**Comment by nmDejamobile** [comment]
I will try that thanks!

**Comment by androidty** [comment]
I'm an android development engineer, and I had this problem, and I used all kinds of base64 encoding, but it didn't work, I used Nimbus, and it worked
