### ISSUE TITLE
Generic parameter to Header type

### ISSUE THREAD

**Issue by jplace** [jwtk/jjwt#316]
What is the generic parameter of the Header type supposed to be?

```
public interface Header<T extends Header<T>> extends Map<String,Object>
```

It looks as if the generic parameter is recursive. I don't understand how it can be used since there is no type to satisfy the recursion base case.

Am I misunderstanding?

**Comment by lhazlewood** [comment]
It's for sub-interfaces that return T from a method (for method chaining).

Without this, if I called `aJwsHeader.setContentType` the return type would be `Header` not `JwsHeader`, which is expected.
