### ISSUE TITLE
io.jsonwebtoken.impl.Base64Codec does not work with Java 9 

### ISSUE THREAD

**Issue by floragunncom** [jwtk/jjwt#317]
<pre>
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
  at io.jsonwebtoken.impl.Base64Codec.decode(Base64Codec.java:26) ~[jjwt-0.9.0.jar:0.9.0]
</pre>

Suggestion is to use replace javax.xml.DatatypeConverter with java.util.Base64

**Comment by RyanBard** [comment]
See #297 and #282 for details on this (this ticket is a duplicate of at least 1 of those).  For an idea of a fix and/or workaround, you can look at #282 and its open PR: https://github.com/jwtk/jjwt/pull/283/files

**Comment by floragunncom** [comment]
Its not only about DatatypeConverter its also about the general java 9 readiness of this library

**Comment by RyanBard** [comment]
I didn't run into any other problems other than jaxb when testing in java 9 (check out: https://github.com/RyanBard/jjwt-consumer-example).  Did I miss something?

**Comment by floragunncom** [comment]
@RyanBard you're right, seems its only the DatatypeConverter which interferes with Java 9.
But have not checked Java 10 or 11-EA

**Comment by floragunncom** [comment]
Any chance that we get a new release soon? The last commit in the master branch is 7 month old! So for me jjwt currently looks like a dead project.

**Comment by lhazlewood** [comment]
@floragunncom it's definitely not dead - we've just been insanely busy.  I *really* hope we can get one out in the next 3-4 weeks.

**Comment by floragunncom** [comment]
Great to hear. Let me know if we could help to drive it forward.

**Comment by getjack** [comment]
@floragunncom Can confirm the problem for JDK10 (10.0.0.1). Problems appears on runtime.

**Comment by lhazlewood** [comment]
Closing as a duplicate of #333.  Work will be tracked via that issue and we hope to have that released asap in the coming days.

**Comment by pradipta** [comment]
Facing this on 11
