### ISSUE TITLE
Enforcing a specific required algorithm for JwtParser

### ISSUE THREAD

**Issue by bcrist** [jwtk/jjwt#320]
I was surprised that there isn't already a method like `JwtParser requireAlgorithm(SignatureAlgorithm algorithm)` in JwtParser.  I realize that JwtParser will throw an exception if an attacker tries to get around the signature verification by specifying algorithm "none", but it still seems like if you have control over the algorithm used to create tokens, the best practice for validating them should be to ensure the token matches the expected algorithm exactly.

As a workaround we're currently using something like this:
```
Jwt jwt = Jwts.parser().setSigningKey(...).parse(token);
if (jwt instanceof Jws) {
    if (ALGORITHM != SignatureAlgorithm.forName(((JwsHeader<?>)jws.getHeader()).getAlgorithm())) {
        throw new MalformedJwtException("Algorithm must be " + ALGORITHM);
    }
    ...
} else {
    throw ...
}
```
but that's rather a mouthful compared to:
```
Jwt jwt = Jwts.parser().requireAlgorithm(ALGORITHM).setSigningKey(...).parse(token);
```

**Comment by lhazlewood** [comment]
Nice issue - thanks for taking the time to add this!  I think it's a nice enhancement.

**Comment by JeremyColton** [comment]
Nice addition, When will this update be released?

**Comment by lhazlewood** [comment]
Actually, I don't see why this is necessary?  When you use `parseClaimsJws` as documented for parsing JWSs, you cannot forge an `alg` header and still have signature validation succeed.  You should never use the unqualified `parse` method if you are expecting a specific type of token, e.g. a JWS.

**Comment by vraravam** [comment]
I have a JWT that was created using `SignatureAlgorithm.HS256` - but when I try to parse it, I get an error `SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted`. Is this error related to this feature request?

**Comment by lhazlewood** [comment]
Closing per the author's closure of #346
