### ISSUE TITLE
Generating Jwt Id

### ISSUE THREAD

**Issue by rosh89** [jwtk/jjwt#323]
I wasn't sure if there is a forum for discussion. If there is one, i apologize for posting this as an issue. 

Question:
I did not find an API in jjwt to generate a token ID / jti / jwt ID. Is this intentional or something that is planned for the future? I noticed this in another library[1] and was wondering if jjwt would support this too.

Thanks!

[1] https://static.javadoc.io/org.bitbucket.b_c/jose4j/0.4.4/org/jose4j/jwt/JwtClaims.html#setGeneratedJwtId()

**Comment by rosh89** [comment]
I'm guessing this isn't needed as consumers can use Java's UUID class, directly? (Closing this issue.)

**Comment by lhazlewood** [comment]
@rosh89 glad to see you answered this yourself 👍   The reality is that there are so many different ID formats that people like to use, that JJWT doesn't need to be in that business.  A UUID is a great default if you don't have a preference.

**Comment by rosh89** [comment]
Thanks Les! That makes sense.
