### ISSUE TITLE
Implement Refresh Token

### ISSUE THREAD

**Issue by alchemistgo87** [jwtk/jjwt#33]
How can I implement Refresh Token if I want user's token to get refreshed after a certain amount of time?

**Comment by lhazlewood** [comment]
This is not the responsibility of jjwt - it is the responsibility of your OAuth implementation (that might use JJWT) to create the refresh token correctly.

**Comment by yosaku01** [comment]
@alchemistgo87 , you can refrer the class org.springframework.security.oauth2.provider.token.DefaultTokenServices
