### ISSUE TITLE
rs256 for privatekey

### ISSUE THREAD

**Issue by SeaCN** [jwtk/jjwt#330]
I generate privateKey use puttyGen tool.  and how to use it  to create a Key in my code? then I can use this key to compact. e.g. `Jwts.builder()
				  .setPayload(payload).setHeader(header)
				  .signWith(SignatureAlgorithm.RS256, signingKey)
				  .compact();
`

**Comment by SeaCN** [comment]
I get the privatekey as a .ppk file, and need to make a Key object using this file. Can you share me an example for this,thank you very much

**Comment by lhazlewood** [comment]
Just a friendly reminder: JJWT's GitHub issues are for actionable work that requires changes to the JJWT codebase. Please use StackOverflow with the `#jjwt` tag for usability/help questions. Thanks!
