### ISSUE TITLE
Using Android SHA-1 to hide String

### ISSUE THREAD

**Issue by ricardofavero** [jwtk/jjwt#340]
I was looking for a way to hide a String in an Android application and found this answer: https://stackoverflow.com/a/35576792

It seemed to be a good solution as each application has its own SHA-1 fingerprint.

As suggested, I wrote one code for encoding and another for decoding a string. I just copied and pasted the encoded String to the second code.

**Printing enconded String**
```java
        try {
            PackageInfo info = getPackageManager().getPackageInfo(
                    "com.example.test",
                    PackageManager.GET_SIGNATURES);
            for (Signature signature : info.signatures) {
                MessageDigest md = MessageDigest.getInstance("SHA");
                md.update(signature.toByteArray());
                
                String hash = Base64.encodeToString(md.digest(), Base64.DEFAULT);

                    String compactJws = Jwts.builder()
                            .setSubject("HideThis")
                            .signWith(SignatureAlgorithm.HS256, hash)
                            .compact();

                   Log.d("Result", compactJws); // <----------------------------------

            }
        } catch (PackageManager.NameNotFoundException e) {

        } catch (NoSuchAlgorithmException e) {

        }
```

**Decoding String**
```java
        try {
            PackageInfo info = getPackageManager().getPackageInfo(
                    "com.example.test",
                    PackageManager.GET_SIGNATURES);
            for (Signature signature : info.signatures) {
                MessageDigest md = MessageDigest.getInstance("SHA");
                md.update(signature.toByteArray());

                String hash = Base64.encodeToString(md.digest(), Base64.DEFAULT);

                String myString = Jwts.parser().setSigningKey(hash).parseClaimsJws(PASTED_ENCODED_STRING_HERE).getBody().getSubject();

                Log.d("My String:", myString);
            }
        } catch (PackageManager.NameNotFoundException e) {

        } catch (NoSuchAlgorithmException e) {

        }
```

The problem is that the String is decoded in any new application I create, with totally different SHA-1 keys.

What am I missing here? I wanted it to work only within my application.

This is the first time I use this library, I apologize if this is a silly question.

**Comment by lhazlewood** [comment]
@ ricardofavero no need to base64-encode your key bytes - in fact the `setSigningKey(String)` will be deprecated on the next release.  Instead, you should do:

```java
byte[] keyBytes = md.digest();
Key key = new SecretKeySpec(keyBytes, SignatureAlgorithm.HS256.getJcaName());
Jwts.builder().signWith(SignatureAlgorithm.HS256, key);
```

That said, the linked answer isn't secure at all - it merely is obscuring the data, not encrypting it (anyone skilled enough could find the SHA fingerprint and re-create the final digest, being able to impersonate you).  Your best bet is to use a secure server somewhere and use public/private key cryptography (the client can reference the server's public key and use that to verify JWTs that come from the server).

Finally, as a friendly reminder, we use GitHub issues to track actionable work that will change the JJWT codebase.  Please use StackOverflow.com and use the `#jjwt` tag for general usability/help questions.  Thanks!
