### ISSUE TITLE
How to retrieve the secret used in MacProvider.generateKey()

### ISSUE THREAD

**Issue by RicoSpm** [jwtk/jjwt#345]
Hi,

How can I retrieve the plaintext secret from the signature of a JWT? I would need to compare the secret coming from the signature with the original one.

Thank you.

Riccardo

**Comment by lhazlewood** [comment]
It is impossible to look at a signature only and then find the secret based on that.  That would completely eliminate the entire security model of cryptographic hashes. :)

JWTs can however have a `kid` field ("key identifier") in the Claims that have some sort of identifier that lets the signing validator know which key was used to create the signature.  It is up to the verifier to look up the signature verification key based on that in whatever implementation-specific way that makes sense.

Finally, as a friendly reminder, GitHub Issues are to track actionable work that imply changes in JJWT's codebase.  Please use StackOverflow.com and the `#jjwt` tag for usage help or general questions.  Thanks!
