### ISSUE TITLE
Upgrade Bouncycastle

### ISSUE THREAD

**Issue by fkoseoglu** [jwtk/jjwt#353]
> **Affecting org.bouncycastle:bcprov-jdk15on artifact, versions [1.54,1.59]**

> Affected versions of this package are vulnerable to Insecure Encryption. It has a flaw in the Low-level interface to RSA key pair generator, specifically RSA Key Pairs generated in low-level API with added certainty may have less M-R tests than expected.

> Source: https://snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-32369

Any plans to upgrade BC version to BC 1.60 beta 4 or later?

**Comment by lhazlewood** [comment]
Yep, happy to do this in the upcoming 0.10.0 release which should be out this week.

**Comment by lhazlewood** [comment]
This has been fixed and released in 0.10.0.  JJWT 0.10.0 now uses BC 1.60 final
