### ISSUE TITLE
Validate JWT RSA256 signature

### ISSUE THREAD

**Issue by RicoSpm** [jwtk/jjwt#358]
Hi,

I have a JWT signed with a RSA256 algorithm. What about to validate a JWT like this one? Do I have to use the same statement as the README.md reports, using the public key got from the public certificate used to sign the JWT?

    try {

        Jwts.parser().setSigningKey(public_key).parseClaimsJws(jwt);

        //OK, we can trust this JWT

    } catch (SignatureException e) {

        //don't trust the JWT!
    }

Thank you!

**Comment by lhazlewood** [comment]
Just a friendly reminder: JJWT's GitHub issues are for actionable work that requires changes to the JJWT codebase. Please use StackOverflow with the `#jjwt` tag for usability/help questions. Thanks!

As to your question:

Yes, you should verify a signed JWT (aka 'JWS') with the public key, and your code example looks good.

Only the private key should be used to _create_ a JWS, but the public key can be used to verify it.
