### ISSUE TITLE
Possible security vulnerability

### ISSUE THREAD

**Issue by gamedevhelper** [jwtk/jjwt#36]
Two security issues. 

1) Must change the parse function and make it mandatory to specify decrypt algorithm instead of reading it from header.

2) 'none' algorithm is open for abuse.  

Please read this article https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/ to see the detail discussion on these issues.

**Comment by lhazlewood** [comment]
I'm curious - did you report this because you think JJWT might be vulnerable?  Or did you test JJWT and find that it is vulnerable?

Did you see my comment in the linked article?

**Comment by gamedevhelper** [comment]
I was reporting it that JJWT might be vulnerable.  I just went back and read the comments and thank yo for verifing that JJWT is not vulnerable to those attack (https://github.com/jwtk/jjwt/issues/20) .  Case closed.
