### ISSUE TITLE
JSON POJO unmarshalling

### ISSUE THREAD

**Issue by lhazlewood** [jwtk/jjwt#369]
Per the discussion in #214:

Improve the exception message:

String msg = "Cannot convert existing claim value of type " + value.getClass() + " to desired type " + requiredType + ". JJWT only converts simple Date, Long, Integer, Short and Byte types automatically. Anything more complex is expected to be already converted to your desired type by the JSON Deserializer implementation. You may specify a custom Deserializer for a JwtParser with the desired conversion configuration via the JwtParser#deserializeJsonWith method. See https://github.com/jwtk/jjwt/README.md#whatever for more information.";

Plus:

* JavaDoc for the `Claims#get` method (dunno why it is missing)
* supporting `new JacksonDeserializer(Maps.of("user", User.class))`
* public documentation on marshaling/unmarshaling and how to do it w/ JJWT (which is the `https://github.com/jwtk/jjwt/README.md#whatever` link in the above exception message).

cc @cbudtz

**Comment by lhazlewood** [comment]
Didn't have time to get this in 0.10.0.  We should be able to get this in the next release.

**Comment by javapapo** [comment]
+1 on this . thanks
