### ISSUE TITLE
"Advertise" on JWT.io

### ISSUE THREAD

**Issue by sparty02** [jwtk/jjwt#37]
Establish a presence on [jwt.io](http://jwt.io/) here, which I think you can do by submitting a PR somewhere [around here](https://github.com/jsonwebtoken/jsonwebtoken.github.io/tree/master/html/libraries)

**Comment by geoand** [comment]
+1 When I was out to find a Java JWT library I immediately went to http://jwt.io/ and picked the first suggestion from there.
Needless to say that this project seems much easier to use than the one I picked :(

**Comment by lhazlewood** [comment]
A PR has been opened: https://github.com/jsonwebtoken/jsonwebtoken.github.io/pull/102

Any +1s in the comment thread would be appreciated to show your support!

**Comment by lhazlewood** [comment]
Side note: @geoand has the coolest avatar ever :)

**Comment by geoand** [comment]
@lhazlewood Thanks! Let's hope the PR will be merged quickly :)

**Comment by nbarbettini** [comment]
Looks like they merged this, it's available on JWT.io now. (Although they listed the package maintainer wrong. :stuck_out_tongue_winking_eye: )

**Comment by lhazlewood** [comment]
We should ask them to fix that.  My name isn't _b_c :-P

**Comment by nbarbettini** [comment]
PR for typo fix: https://github.com/jsonwebtoken/jsonwebtoken.github.io/pull/143

**Comment by lhazlewood** [comment]
They merged the last PR.  Yay!
