### ISSUE TITLE
Mark BouncyCastle as an optional dependency

### ISSUE THREAD

**Issue by ufoscout** [jwtk/jjwt#372]
After an upgrade from 0.9.1 to 0.10.0 we noticed a huge increase in our final fat jar. This is due to the fact that in 0.10.0 the org.bouncycastle:bcprov-jdk15on is imported by default and not managed as optional any more.
We manually excluded it from our pom.xml file this way:
```xml
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-impl</artifactId>
                <version>0.10.0</version>
                <scope>runtime</scope>
                <exclusions>
                    <exclusion>
                        <groupId>org.bouncycastle</groupId>
                        <artifactId>*</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
```

now everything works as expected and the bouncycastle dependency is not included in the fat jar anymore. 
Is there any reason for having it mandatorily in the classpath? Is it a regression in 0.10.0?

**Comment by lhazlewood** [comment]
This is a total oversight and should be marked as optional for sure.  Adding an exclusion as you've done is the workaround until we can release 0.10.1.  Thanks for reporting this!

**Comment by ufoscout** [comment]
Great, thank you!

Please note that you declared it to be fixed in 0.10.1 but you added it to the 0.11.0 milestone.

**Comment by lhazlewood** [comment]
I know, I removed the milestone immediately thereafter.  I guess you didn't see that before sending the message ;)

**Comment by lhazlewood** [comment]
0.10.1 has been released - please allow 15-30 minutes to allow the release to show up in Maven Central.  Thanks for reporting the issue!
