### ISSUE TITLE
Typos/incorrect examples in JwtBuilder JavaDoc

### ISSUE THREAD

**Issue by wengertj** [jwtk/jjwt#386]
This is nothing critical - I think i just stumbled across two minor issues in the `JwtBuilder` JavaDoc:

[1 - setAudience(String aud)](https://github.com/jwtk/jjwt/blob/master/api/src/main/java/io/jsonwebtoken/JwtBuilder.java#L191)
```java
// ...
String jwt = Jwts.builder().setAudience("You").compact();
// Is:
Claims claims = Jwts.claims().setSubject("You");
// Should be:
Claims claims = Jwts.claims().setAudience("You");
// ...
```

[2 - setId(String jti)](https://github.com/jwtk/jjwt/blob/master/api/src/main/java/io/jsonwebtoken/JwtBuilder.java#L304)
```java
// ...
String jwt = Jwts.builder().setId(UUID.randomUUID().toString()).compact();
// Is:
Claims claims = Jwts.claims().setIssuedAt(UUID.randomUUID().toString());
// Should be:
Claims claims = Jwts.claims().setId(UUID.randomUUID().toString());
```

I'd be happy to open a PR if you guys are too busy.
Thanks and keep up the great work with this library 👍

**Comment by lhazlewood** [comment]
Doc PRs are always welcome! Thanks for finding this :)  And thanks for the kind words!
