### ISSUE TITLE
The signing key's algorithm 'HMACSHA256' does not equal a valid HmacSHA* algorithm name and cannot be used with HS256

### ISSUE THREAD

**Issue by ITWall** [jwtk/jjwt#387]
I did exactly the sample in readme file for android but I still got this error when I use 0.10.3 version. Please check it, thanks!

**Comment by rodmaz** [comment]
This is a potential duplicate issue. See issue [#381](https://github.com/jwtk/jjwt/issues/381)

**Comment by lhazlewood** [comment]
Thanks for reporting this!  I'd rather see duplicates instead of people not reporting.  I'll close this issue in favor of tracking the work with #381.
