### ISSUE TITLE
java.lang.NoClassDefFoundError: org.json.JSONString

### ISSUE THREAD

**Issue by ITWall** [jwtk/jjwt#388]
When I use 0.10.4 version, I got this error when I do the sample in readme. I don't know why but after add this library http://mvnrepository.com/artifact/org.json/json, I solved it. Not so sure if this is a bug or not.

**Comment by lhazlewood** [comment]
Sigh.  Android is killing me! 😭 

org.json.JSONString and org.json.JSONWriter are used by the implementation but never used by Android at runtime.  When the class is loaded, that's when it barfs.  I'll have to change the implementation again, potentially duplicating logic from later org.json releases that Android doesn't have.

Thanks for reporting this.  You're correct - the workaround in the meantime is to include the org.json .jar.

**Comment by rodmaz** [comment]
Same problem here on Android. Has this fixed on `0.10.5`? 
When we include version `0.10.5` we get `Gradle sync failed` on Gradle/Android Studio.

**Comment by rodmaz** [comment]
This was causing the reported `freeze` when we called the `compact()` method on Android.

**Comment by lhazlewood** [comment]
0.10.5 is being released as we speak.  Maven Central staging is *super* slow due to degraded network performance, so please allow it 30 minutes or so before trying.

**Comment by rodmaz** [comment]
Thanks. We tried it like 1h ago as the tag was already there. We will resume tomorrow. Thanks again @lhazlewood!

**Comment by fernando-jascovich** [comment]
Hi, I think that this issue (or some new form of it) is still around; when I set dependencies as explained in documentation: 
```
    runtimeOnly('io.jsonwebtoken:jjwt-orgjson:0.10.5') {
        exclude group: 'org.json', module: 'json' //provided by Android natively
    }
```
And then, I use the following example code:
```
        val token = Jwts.builder()
                .claim("myclaim", "myclaimValue")
                .signWith(SignatureAlgorithm.HS256, acceptableKey.toByteArray())
                .compact()
```
I get the following NPE:
```
java.lang.IllegalStateException: Unable to serialize header to json.
	at io.jsonwebtoken.impl.DefaultJwtBuilder.base64UrlEncode(DefaultJwtBuilder.java:381)
	at io.jsonwebtoken.impl.DefaultJwtBuilder.compact(DefaultJwtBuilder.java:333)
...
Caused by: io.jsonwebtoken.io.SerializationException: Unable to serialize object of type io.jsonwebtoken.impl.DefaultJwsHeader to JSON: null
	at io.jsonwebtoken.io.OrgJsonSerializer.serialize(OrgJsonSerializer.java:47)
	at io.jsonwebtoken.impl.DefaultJwtBuilder.toJson(DefaultJwtBuilder.java:392)
	at io.jsonwebtoken.impl.DefaultJwtBuilder.base64UrlEncode(DefaultJwtBuilder.java:379)
	... 50 more
Caused by: java.lang.NullPointerException
	at io.jsonwebtoken.io.OrgJsonSerializer.toJSONInstance(OrgJsonSerializer.java:67)
	at io.jsonwebtoken.io.OrgJsonSerializer.serialize(OrgJsonSerializer.java:40)
	... 52 more
```

And if I include `org.json.json` at `build.gradle` (this is, remove exclusion from `runtimeOnly` declaration), code works as expected. I think that there is some weird Android handling there.

**Comment by lhazlewood** [comment]
Did you set up proguard exclusions properly for org.json?

We can't re-create this - we'd need a sample project from someone to demonstrate the problem.

**Comment by fernando-jascovich** [comment]
I'm not using proguard in that project.
I will generate a sample project later so you can check it.

**Comment by fernando-jascovich** [comment]
I made this repository for demonstration: https://github.com/fernando-jascovich/jjwt-issue-388
However, it seems to work fine there. So I think my previous crash was due to some interaction with another third party library.

**Comment by lhazlewood** [comment]
@fernando-jascovich thanks so much for verifying.  If you are able to re-create the problem in the future, please do open a new ticket or request to re-open this one.  Cheers!
