### ISSUE TITLE
Does jjwt support applying multiple signatures

### ISSUE THREAD

**Issue by khoubyari** [jwtk/jjwt#389]
Per bottom of section https://tools.ietf.org/html/rfc7515#section-7.1  it is possible to sign a JWT with multiple signatures and the application can choose which signature to verify. Can JJWT do this? If so, can you share a code snippet as example? 

Thank you.

**Comment by lhazlewood** [comment]
I think your reference is mistaken.  Section 7.1 discusses compact JWSs and those only support one signature, one recipient.

[Section 7.2](https://tools.ietf.org/html/rfc7515#section-7.2) discusses JWS JSON Serialization (non-compact, just a standard JSON document) which _does_ support multiple signatures (e.g. 1 per recipient).  JWS JSON Serialization will be completed via #199, but we can't say when.

JJWT's versioning strategy is to only release `1.0.0` when we implement 100% of all features of the specification, which would include JSON Serialization.  That said, 95% of people looking to use JWTs are almost always looking for compact JWS or JWE support, so the non-compact JSON serialization will very likely be implemented last just before releasing 1.0.

Of course, should anyone want to help us implement it to make things go faster, we'd welcome it, but pending that, it will definitely be in 1.0 (and maybe even before then, we just can't say at the moment).

I hope that helps!

And as a friendly reminder, please note that JJWT's GitHub issues are for actionable work that requires changes to the JJWT codebase. Please use StackOverflow with the `#jjwt` tag for usability/help questions in the future.  Thanks!
