### ISSUE TITLE
DefaultJws class doesn't propagate the generic B type to the interface

### ISSUE THREAD

**Issue by josebarrueta** [jwtk/jjwt#39]
By not propagating the generic type to specific generic to the interface, IDEs warn of not passing the specific type in the Jws.

For example:

```
 Jws<MyClaims> jws = Jwts.parser().setSigningKeyResolver(issuerSigningKeyResolver).parse(jwt, new JwtHandlerAdapter<Jws<MyClaims>>() {
                @Override
                public Jws<MyClaims> onClaimsJws(Jws<Claims> jws) {
                    MyClaims myClaims = ...;
                    return new DefaultJws<>(jws.getHeader(), myClaims, jws.getSignature());
                }
            });

```

The IDE complains the the returned type is not of  ```Jws<MyClaims> ```. 

Solution will be add the generic body to the signature of the class:

```public class DefaultJws<B> implements Jws<B> ```

**Comment by lhazlewood** [comment]
Resolved by PR #40.  Will be released in 0.6.
