### ISSUE TITLE
Support running with JRE 11: Fix/remove usage of javax.xml.bind package

### ISSUE THREAD

**Issue by dcmoeller** [jwtk/jjwt#401]
Hello,

one of my projects use jjwt lib, version 0.9.1 at the moment (newest one in [Maven Repo](https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt)).
Running on JRE 11 breaks with e.g.
```
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
		        at io.jsonwebtoken.impl.Base64Codec.encode(Base64Codec.java:21)
		        [...]
```
javax.xml.bind package has been deprecated since Java 9 marked to get removed with a later version:

[https://docs.oracle.com/javase/9/docs/api/java.xml.bind-summary.html](https://docs.oracle.com/javase/9/docs/api/java.xml.bind-summary.html)

The same holds with Java 10, but Java 11 removes this module/package:

[https://docs.oracle.com/en/java/javase/11/migrate/index.html#JSMIG-GUID-561005C1-12BB-455C-AD41-00455CAD23A6](https://docs.oracle.com/en/java/javase/11/migrate/index.html#JSMIG-GUID-561005C1-12BB-455C-AD41-00455CAD23A6),
Chapter "Removal of Java EE and CORBA Modules".

I haven't yet digged into this issue any deeper to tell whether it's better to fix or remove usage of JAXB module.

Regards

Christian

**Comment by lhazlewood** [comment]
Hi there,

`javax.xml.bind` is no longer in use.  Please upgrade to the latest stable JJWT version.

See https://github.com/jwtk/jjwt#base64
