### ISSUE TITLE
Create Gittr chat room for JJWT

### ISSUE THREAD

**Issue by behrangsa** [jwtk/jjwt#407]
Please create a [Gittr](https://gitter.im) chat room for JJWT.

**Comment by lhazlewood** [comment]
We use slack.

For anyone wanting to join, feel free to [join the JJWT Slack workspace](https://join.slack.com/t/jwtk/shared_invite/enQtNTcxODc3NDAxOTcyLTYzMGIyMGZhNzA5ZWQwMWQ5MWQ4NjFkNDQyYzAxYzdhZDU1ZjYyOTUxMjliZTVkNTg0NzczZmY2ZDljNjI0Nzc)
