### ISSUE TITLE
Provide an implementation of SigningKeyResolver that resolves and caches certificates from the JWT header

### ISSUE THREAD

**Issue by behrangsa** [jwtk/jjwt#409]
Provide a default implementation of `SigningKeyResolver` that:

* Inspects the JWT header (e.g. `x5t` and `x5u` headers)
* Fetches the key from an internal cache (probably a `KeyCache` interface that can have multiple implementations, e.g. `InMemoryKeyCache`, `JdbcKeyCache`, etc.) if the key is already cached
  * If the key is not already in the cache, it fetches the key from `x5u` and caches it
* Validates the certificate's issuer, etc. against a CA provided by the user
* If successful, resolves the key. 
  * Otherwise throws an exception.

**Comment by lhazlewood** [comment]
Just reviewing this again:

This is the only request for such a feature we've ever had, and the internal implementation details are sufficiently complex plus require additional caching interfaces - it's probably just easier for the caller to implement their own `SigningKeyResolver` implementation to use whatever application-specific mechanisms that already exist (and to be honest, scenarios like this are exactly why the `SigningKeyResolver` interface exists).

As a result, we're going to pass on this particular request, but we could open it in the future if others wanted the same or similar functionality.  Thanks for the suggestion!
