### ISSUE TITLE
org.google.com gson extension

### ISSUE THREAD

**Issue by patton73** [jwtk/jjwt#410]
Is there also an implementation that relies on gson library. I mean Google com.google.gson library?
Thanks.

**Comment by patton73** [comment]
I have provided a pull request for that. 
https://github.com/jwtk/jjwt/pull/414

**Comment by lhazlewood** [comment]
While #414 has been merged, we can't consider this 'done' until the documentation in README.md has been updated to fully cover how to use/configure Gson.  It should be added to the `<a name="json"></a>` section near the bottom of the document.

Also CHANGELOG.md needs to be updated to represent the new feature.

I'll keep this open until someone can issue a PR for these two things or I take a crack at it, whichever comes first.

**Comment by lhazlewood** [comment]
This work has been completed via #476.  We can only merge that right before the 0.11.0 release.

**Comment by patton73** [comment]
Ok thank you.

**Comment by lhazlewood** [comment]
Docs merged to README-0-11-0 branch.  Those will be merged during the release.
