### ISSUE TITLE
Multiple versions of ClaimJwtException.class

### ISSUE THREAD

**Issue by ryber** [jwtk/jjwt#419]
Hello. When I pull in the main jsonwebtoken as well as the jackson extension I get a warning at startup:

> [WARNING] io.jsonwebtoken.ClaimJwtException scanned from multiple locations: jar:file:///D:/DEV/.m2/repo/io/jsonwebtoken/jjwt/0.9.1/jjwt-0.9.1.jar!/io/jsonwebtoken/ClaimJwtException.class, jar:file:///D:/DEV/.m2/repo/io/jsonwebtoken/jjwt-api/0.10.5/jjwt-api-0.10.5.jar!/io/jsonwebtoken/ClaimJwtException.class 

```xml
       <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt</artifactId>
            <version>0.9.1</version>
        </dependency>

        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-jackson</artifactId>
            <version>0.10.5</version>
        </dependency>
```

It's probably not a problem but might be if one changes independent of the other. Should I only use the Jackson one? Seems like I might be missing something then?

**Comment by lhazlewood** [comment]
You're using different JJWT versions.  The version must be the same for all JJWT artifacts.

**Comment by ryber** [comment]
I'm confused about how that is possible as there is no 0.10. series of jjwt and no .9 series of jackson? Am I now supposed to be using io.jsonwebtoken::jjwt anymore?

**Comment by lhazlewood** [comment]
The artifact IDs changed on the 0.10.X release.  Please see the docs for the correct artifact group and name IDs:

https://github.com/jwtk/jjwt#install-jdk

**Comment by ryber** [comment]
Sorry, just saw this part https://github.com/jwtk/jjwt#jdk-projects
