### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by hypnoce** [jwtk/jjwt#430]
Hi,

I noticed that this the pulse status of the project is relatively low. A bunch of PRs and issues are stacking up.
Is there a reason for such a low activity from the maintainers ?
If so, will it be possible to add more maintainer so this project can live with the community ?

Let me know what you think.

Thanks for your feedback.

**Comment by hypnoce** [comment]
@lhazlewood Thanks for your reply. I understand that you are currently very busy.
Nevertheless, keeping activity on the repo for corrective maintenance without any big new feature development would unblock many users.
I would be interested in such corrective maintenance (Bug fix, dependencies updates, travis build updates...) without being involved in bigger development for now.
Thanks !

**Comment by lhazlewood** [comment]
Just an FYI: we're releasing 0.10.7 today or tomorrow and hopefully 0.11.0 at the end of the week.
For further discussion, please feel free to join our Slack workspace via https://github.com/jwtk/jjwt/issues/407#issuecomment-471219769
