### ISSUE TITLE
How to ungzip or inflate the token in browser?

### ISSUE THREAD

**Issue by LucasHCruz** [jwtk/jjwt#435]
Hi guys, I'm generating a JWT in back end with DEFLATE or GZIP compression codec, but I can't decompress in browser. Does anyone knows some lib to do this with JJWT?

**Comment by lhazlewood** [comment]
Hi there!

Please feel free to ask this question on StackOverflow, where I'm sure you'd get some good answers.  We use GitHub issues for tracking actionable work on the JJWT codebase, not for general discussion.  Thanks!
