### ISSUE TITLE
EXPIRATION Claims wrong value

### ISSUE THREAD

**Issue by YooKiHyun** [jwtk/jjwt#439]
-The code below is incorrect
String token = Jwts.builder().claim(Claims.EXPIRATION, new Date()).compact();
Jws<Claims> claims = Jwts.parser().parseClaimsJws(token);
Date expr = claims.getBody().getExpiration();

-The code below is correct
String token = Jwts.builder().setExpiration(new Date()).compact();
Jws<Claims> claims = Jwts.parser().parseClaimsJws(token);
Date expr = claims.getBody().getExpiration();

**Comment by lhazlewood** [comment]
You must be using an old version (< 0.10) of JJWT. 

The following works with the latest stable JJWT release (0.10.6):

```java
final Date date = new Date(System.currentTimeMillis() + 10000);
final Key key = Keys.secretKeyFor(SignatureAlgorithm.HS256);

String token1 = Jwts.builder().claim(Claims.EXPIRATION, date).signWith(key).compact();
Jws claims1 = Jwts.parser().setSigningKey(key).parseClaimsJws(token1);
Date expr1 = claims1.getBody().getExpiration();

String token2 = Jwts.builder().setExpiration(date).signWith(key).compact();
Jws claims2 = Jwts.parser().setSigningKey(key).parseClaimsJws(token2);
Date expr2 = claims2.getBody().getExpiration();

assert expr1.equals(expr2)
```

Please upgrade to the latest stable JJWT release.
