### ISSUE TITLE
JJWT 0.11.1 released or not?

### ISSUE THREAD

**Issue by breun** [jwtk/jjwt#441]
https://github.com/jwtk/jjwt/releases/tag/jjwt-root-0.11.1 suggests that there has been a release of 0.11.1 a couple of days ago, but the latest version on Maven Central is 0.10.6 according to https://search.maven.org/search?q=g:io.jsonwebtoken%20AND%20a:jjwt-root&core=gav and that's also the latest version that's mentioned in the changelog at https://github.com/jwtk/jjwt/blob/master/CHANGELOG.md

So, has 0.11.1 actually been released? And if so, what's new?

**Comment by lhazlewood** [comment]
@dogeared  ? Was this a failed release?

**Comment by lhazlewood** [comment]
@breun after digging around, I believe that this was a tag created during a failed release attempt.  Neither 0.11.0 or 0.11.1 have been released.

I'll be working on the 0.11.0 release this week.
