### ISSUE TITLE
Please release a version using standard Jackson dependency

### ISSUE THREAD

**Issue by shevek** [jwtk/jjwt#442]
Please can you separate your custom code from the Jackson dependency so that we can build an application using your library. Right now, we have a clash between your jackson and the upstream one, and we cannot resolve it by excluding either one, because each contains something that the other does not.

**Comment by lhazlewood** [comment]
I don't understand this issue.  What 'custom code' are you talking about?

Can't you use an mvn exclude on our Jackson dependency to resolve your issue?

Can you please provide more information?  Exactly what in the JJWT codebase is causing you issues?

**Comment by shevek** [comment]
I found the issue at the time when we tried to integrate your codebase into our project, but I can't figure it out now. Sorry.
