### ISSUE TITLE
More flexible parsing support (old #328)

### ISSUE THREAD

**Issue by zolyfarkas** [jwtk/jjwt#444]
The idea is when parsing from some source, CharSequence is a bit more flexible... (String, StringBuilder ...)

for an example, in class Integer you have both:

public static int parseUnsignedInt(String s, int radix)
and:
public static int parseUnsignedInt(CharSequence s, int beginIndex, int endIndex, int radix)

in case on JWT, lets say the web token needs to be parsed out of a string like:

"Bearer [JWT token]"

I want tp avoid doing a substring() and allocate memory for no good reason.. having a CharSequence parsing variant I could simply do: parse(myString, "Bearer ".length(), myString.length())

The existing interfaces don't need to be changed, this would be additional....

**Comment by lhazlewood** [comment]
Please don't duplicate issues.  I'll re-open 328.
