### ISSUE TITLE
io.jsonwebtoken.lang.UnknownClassException: Unable to load class named [io.jsonwebtoken.impl.DefaultJwtParser] is thrown when passing jwt string for Claims

### ISSUE THREAD

**Issue by mkindika** [jwtk/jjwt#447]
I am getting a runtime exception while passing jwt string for Claims. 

```
implementation('io.jsonwebtoken:jjwt-api:0.10.5')
runtimeOnly('io.jsonwebtoken:jjwt-jackson:0.10.5')

Claims claims = Jwts.parser().setSigningKey(sKey).parseClaimsJws(jwt).getBody();
```

io.jsonwebtoken.lang.UnknownClassException: Unable to load class named [io.jsonwebtoken.impl.DefaultJwtParser] from the thread context, current, or system/application ClassLoaders.  All heuristics have been exhausted.  Class could not be found.

**Comment by lhazlewood** [comment]
You forgot the `jjwt-impl` .jar:

https://github.com/jwtk/jjwt#dependencies

**Comment by SharkFourSix** [comment]
OMG. Why? I'm using maven (uber jar) and I do not want external libs. The final jar does not contain the jjwt-impl classes but I can access the classes in IntelliJ

And where do I put the .JAR file?

**Comment by SharkFourSix** [comment]
> You forgot the `jjwt-impl` .jar:
> 
> https://github.com/jwtk/jjwt#dependencies

OMG. Why? I'm using maven (uber jar) and I do not want external libs. The final jar does not contain the jjwt-impl classes but I can access the classes in IntelliJ

And where do I put the .JAR file?

**Comment by lhazlewood** [comment]
For usability questions, please read https://github.com/jwtk/jjwt#help-questions

I can assure you that the classes are definitely in the respective .jar files, which means there is something wrong with how you are creating your fat jar - maybe a maven plugin configuration, or similar.  Double-check that whatever approach you are using ensures runtime dependencies are included in addition to compile dependencies.  Also, if you can, please ensure you're using the latest stable JJWT version, which is 0.11.0 at the time of writing.

Feel free to provide a sample (tiny) maven project that demonstrates your problem and we can see if we can help, but IMO this isn't really a JJWT question, but a general "fat jar with dependencies" question.
