### ISSUE TITLE
Release 0.10.7

### ISSUE THREAD

**Issue by hypnoce** [jwtk/jjwt#450]
Hi,

since all milestones are closed https://github.com/jwtk/jjwt/milestone/19 do you think it's possible to release 0.10.7 or is there any new issues ?

Thanks

**Comment by hypnoce** [comment]
Any chance to get a release ?

**Comment by mbaluda** [comment]
The release is mentioned in the release notes but is not available yet

**Comment by lhazlewood** [comment]
Releasing today
