### ISSUE TITLE
jwt token can not decode

### ISSUE THREAD

**Issue by DR-YangLong** [jwtk/jjwt#452]
i get a jwt:

eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyTmFtZSI6Iua1i-ivleaWsOWiniIsInN1YiI6ImxvZ2luVG9rZW4iLCJpc3MiOiJsZWFwbW90b3JfYXBpIiwiYXVkIjoiZmYzZjM2ZGMwOTlhZDRmYTUyMDI2NDJiMGM1NDU3OGYiLCJpYXQiOjE1NTcwNDk5NTUsImV4cCI6MTU1NzA1MDA3NX0.CNgATDgP2orHtBq_sPLrzmkmjhH2MLqbxiIQAovEKS5xPMYXLiqTpukub_AOYg-Bd0xU2-3Yb8m1SpErbWGsxw

the payload can not use js base64url to decode.

**Comment by kurenai-ryu** [comment]
your payload has non-ascii characters,
```javascript
{
  "userName": "测试新增",
  "sub": "loginToken",
  "iss": "leapmotor_api",
  "aud": "ff3f36dc099ad4fa5202642b0c54578f",
  "iat": 1557049955,
  "exp": 1557050075
}
```
better if you define with which character set it was encoded or change it to UTF-8

**Comment by lhazlewood** [comment]
We use GitHub Issues to track actionable work for changes that need to occur within the JJWT codebase.  Please use StackOverflow and the `jjwt` tag for asking general questions.  Thanks!
