### ISSUE TITLE
Cannot parse JWS with non-claims JSON payload.

### ISSUE THREAD

**Issue by CharlieReitzel** [jwtk/jjwt#460]
Besides assuming that all payloads are UTF-8 Strings, it also assumes that if the String starts and ends with curly brackets `{}`, it must be a Claims payload.

If I pass in JSON data as the payload, it successfully creates the JWS.  But when parsing the resulting JWS using parsePlainTextJws(), if with the exception:
```
io.jsonwebtoken.UnsupportedJwtException: Signed Claims JWSs are not supported.
  at io.jsonwebtoken.JwtHandlerAdapter.onClaimsJws(JwtHandlerAdapter.java:50)
  at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:519)
  at io.jsonwebtoken.impl.DefaultJwtParser.parsePlaintextJws(DefaultJwtParser.java:560)
```

If using plain parse(), it fails on deserialization because the returned Jwt<?, Claims>.getBody() returns a Claims object (effectively a map).

Here is the offending line in the source (version 0.10.5).
https://github.com/jwtk/jjwt/blob/86b6096946752cffcfbc9b0a5503f1ea195cc140/impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtParser.java#L300

**Comment by lhazlewood** [comment]
'Plaintext' (non JSON-claims) JWTs were a feature when the JWT specification was a draft, and JJWT was created and implemented this feature when it was a draft as well.  At the time of implementation, we just used an open and closing curly brace as a heuristic to determine if it was JSON or not, and if JSON, it must be a claims object.

When the JWT RFCs were finalized, plaintext JWTs were not supported at all in the specification - A JWSs (or JWEs) 'payload' must always be a JSON object now.  As a result, JJWT will remove support for this behavior just prior to the 1.0 release, so please don't rely on it as a feature set.  If anything just use a claim, like 'payload' and specify your string as desired, e.g. `jwtBuilder.claim("payload", myString)`.

I've just created #464 to track the deprecation notice in an upcoming release and #465 to track the work to remove it entirely for the 1.0 release.

Thanks for the report!

**Comment by lhazlewood** [comment]
Well, I thought it was removed, but the JWS RFC does indeed define a payload as any Base64URL string:  https://tools.ietf.org/html/rfc7515#section-3.3

So we'll have to keep the feature, and update the implementation to better handle your scenario and not rely on heuristics if you explicitly call `parsePlaintext*` methods.  Apologies for the confusion!

**Comment by lhazlewood** [comment]
Also implementation note:  The JWS RFC indicates that the `JWS Payload` can be any arbitrary octet sequence (byte array), not just a UTF-8 String.   The `cty` header should indicate the content type of the payload and, according to the RFC, it is the application (not the JWT library, i.e. JJWT) that needs to convert the payload to it's desired format based on the `cty` value.  That said, JWT might be able to make this easier:

1.  If no `cty` header exists, JJWT *must* return the byte array - no conversion to a string can be performed.
2.  If the `cty` header contains a media type that JJWT understands, JJWT can convert it on behalf of the application and return the final output.  This can be tricky however since registered media type handlers should be registered on the parser (e.g. map of content type name or enum to content type converter, similar to how the Spring Framework supports dynamic Content Type converters (map key: content type, map value: converter).

2 might be a lot of work and out of scope for JJWT - not sure.  1 must definitely be implemented.

**Comment by lhazlewood** [comment]
Marking for 1.0 as this might require a backwards incompatible change. (e.g. jwt.getBody())

**Comment by CharlieReitzel** [comment]
I'd suggest a new method name, like `jwt.getBodyBytes(...)`.

**Comment by lhazlewood** [comment]
@CharlieReitzel After thinking about it a bit, that won't be necessary given that `Jwt#getBody()` already uses generics, i.e.

```java
public interface Jwt<H extends Header, B> {
    H getHeader();
    B getBody();
}
```

The parser will just need to support Jwt instances with bodies other than `String` and `Claims` based on the `cty` (Content Type) header.

**Comment by CharlieReitzel** [comment]
That's not the correct use of the `cty` JWT header.   That header is intended for nested signing and encryption tokens (e.g. a signed "envelope" containing an encrypted "letter").

For non-claims content, I think you can safely expect the caller to know what is contained in the body, possibly by using a custom header.

**Comment by lhazlewood** [comment]
> That header is intended for nested signing and encryption tokens

That's not strictly true.  When not nested, applications can use that header to represent the media type of the payload:

https://tools.ietf.org/html/rfc7515#section-4.1.10 : 

```
The "cty" (content type) Header Parameter is used by JWS applications
to declare the media type [IANA.MediaTypes] of the secured content
(the payload).  This is intended for use by the application when more
than one kind of object could be present in the JWS Payload; the
application can use this value to disambiguate among the different
kinds of objects that might be present.  It will typically not be
used by applications when the kind of object is already known.  This
parameter is ignored by JWS implementations; any processing of this
parameter is performed by the JWS application.  Use of this Header
Parameter is OPTIONAL.```

And within that:  

> It will typically not be used by applications when the kind of object is already known

So based on that paragraph, callers of the JwtParser API should be able to (I think):

* tell the parser, "I know what type I will get back without checking the `cty` header, and that type is `Whatever.class`, so coerce `Jwt#getBody()` to that.  If it can't, throw an exception."
* tell the parser, "I don't know what type I will get back, but here is a `MediaTypeResolver` - use it to look at the `cty` header and return a `Function<byte[], T>` that will convert the payload to a type I care about.".  If unspecified, a default `MediaTypeResolver` can exist to perform conversions based on common media types
* when no `cty` header is present, default to heuristics:
  * Try to convert the byte array to a UTF-8 String
  * If a string, try to convert to JSON.  If that works, they are Claims
  * If neither of these succeed, return the raw byte array.

I'm just brainstorming here - there clearly needs to be some diligence in designing what the optimal `JwtParser` usage experience is.  99% of people only use JSON or String payloads, so maybe the heuristics are sufficient?  Comments/feedback welcome.

**Comment by CharlieReitzel** [comment]
I agree, that defaulting to a UTF-8 String payload is appropriate.   But I wouldn't go any further than that with the heuristics.

Better to let the caller make the decisions.  I.e. if the caller wants to use `cty` to specify a MIME type for a binary payload, let 'em.   If they don't, then don't force it.  If the caller calls `String jwt.getBody(String.class)` (or something like that), then it's probably worth having a `jwt.setEncoding( Charset cs )` method that must be called prior to `jwt.getBody()` to have an effect.   

Fwiw, this approach is in keeping with other JWT implementations.

**Comment by lhazlewood** [comment]
This functionality is now in `master` and will be in the `0.12.0` release.
