### ISSUE TITLE
Add build Jwt to JwtBuilder 

### ISSUE THREAD

**Issue by danilobuerger** [jwtk/jjwt#48]
`JwtBuilder` should have the ability to actually build a `Jwt` object instead of only the compact `String` representation.

I would 
- add `Jwt build();` to `JwtBuilder`
- add `String compact();` to `Jwt`
- move all functionality (minus return `String`) from `DefaultJwtBuilder.compact()` to `DefaultJwtBuilder.build()`
- implement `DefaultJwt.compact()` and `DefaultJws.compact()` to return the compact `String`
- make `DefaultJwtBuilder.compact()` call `return build().compact();` to not break api compatibility

If a core contributor could tell me if that would be accepted as a PR, i would do it. Otherwise, i could also implement another solution to this if outlined.

**Comment by lhazlewood** [comment]
What is the use case where a JWT object needs to be built instead of the compact string?  I'm just trying to understand the desired change since almost everyone only uses JWTs to 1) build the compact string, and then later 2) parse a compact string

**Comment by danilobuerger** [comment]
@lhazlewood I have an endpoint which spits out a JWT token. This token is later used by clients to auth. I want to make it easier for clients so that they don't necessarily have to parse the token. Thats why i am return the claims in my response to:

```
{
  "claims": {
    "sub": "...",
    ...
  },
  "token": "compact"
}
```

If we had a ``build`` i could do:

```
final Jwt jwt = builder.build();
response.put("claims", jwt.getBody());
response.put("token", jwt.compact());
````

Which would be awesome :dancer: 

Since we are not breaking API, and just adding another two public methods, and i would write it, i guess there is no harm to it even if you don't see my use case as a valid one. People will always do crazy stuff with libraries :tada:

**Comment by lhazlewood** [comment]
This is helpful, thanks!

I think the sentiment of the request definitely makes sense.  The only thing I'm currently debating is the notion of having `jwt.compact()` - this requires the JWT implementation know about JSON/JWT compaction logic, which feels a little too 'coupled' to me at the moment (not sure though - just thinking out loud).

In other words, in the spirit of the Single Responsibility Principle, it seems as if formatting of a JWT into a compact representation should be a separate concern from the JWT implementation itself.  Or maybe given that compaction is so core to JWT itself, that you just ignore SRP and do it anyway?

Thoughts?

**Comment by danilobuerger** [comment]
Hmm, yeah. Thats definitely a valid point. Maybe we could try a general Serializer approach. Moving the logic out of ``DefaultJwtBuilder.compact()`` into Serializer. That way something like

```
final Jwt jwt = builder.build();
response.put("claims", jwt.getBody());
response.put("token", Jwts.serializer().compact(jwt));
```

would be possible. I don't know however if thats worth the effort if we are always just stuck with the compact representation.

**Comment by danilobuerger** [comment]
@lhazlewood so how should we proceed?

**Comment by lhazlewood** [comment]
I think the Builder should still have `.compact()` - the reason is that the Builder is the coordinator for relevant behavior for creating JWTs and strings.  It in turn should delegate to respective components that perform specific responsibilities as necessary.

That said, what about something like this:

```java
Jwts.builder(jwt).signWith(HS256, key).compact();
```

By specifying a JWT instance, it's almost like you're 'kick starting' the builder, and normal signature/compaction calls can still be called as desired.

Thoughts?

**Comment by danilobuerger** [comment]
I like it. I will do a PR then :-).

However we could have a ``Jwt`` with ``B != String || Claims`` which the builder would not be able to support. I guess we have a couple of options there:

* Throw an exception from constructor
* Just cast like in ``DefaultJwtParser.parse(String compact, JwtHandler<T> handler)``

**Comment by lhazlewood** [comment]
I'd throw an exception if the payload is not a String or Claims - fail fast :)

**Comment by danilobuerger** [comment]
For my use case not necessary, but one thing that would not work out of the box:

```
Jwt jwt = builder.signWith(HS256, key).build();
Jwts.builder(jwt).compact();
```

Could be made to work though by adding ``JwtBuilder.setSignature(String signature)``. That way this could be invoked if a ``Jws`` is invoked.

**Comment by lhazlewood** [comment]
This has been very low priority for a long time now, so I'm closing it since it appears we may never get to it.  That said, if anyone else feels the need for this, please do comment.  If there is enough interest, we can certainly re-open it.
