### ISSUE TITLE
The SignatureAlgorithm change to an interface is complete or not ?

### ISSUE THREAD

**Issue by yangsaipp** [jwtk/jjwt#492]
I want to plug  own crypto Implementation to the jjwt library and use it instead of the default provided Crypto layer. I find some userful info on [https://github.com/jwtk/jjwt/pull/194](url). 

SignatureAlgorithm is alse enum on the master, So the SignatureAlgorithm change to an interface is complete or not ?

**Comment by lhazlewood** [comment]
It is not yet complete.  Because it's a backwards-incompatible change and would break semantic versioning, we cannot make this change until 1.0.  I've created #493 to track this work.

Also, in the future when asking questions, please read https://github.com/jwtk/jjwt#help-questions

Thanks!
