### ISSUE TITLE
Change all documentation to reference Jwts.parserBuilder() + build instead of Jwts.parser()

### ISSUE THREAD

**Issue by lhazlewood** [jwtk/jjwt#494]
@bdemers do you want to take a crack at this as a separate PR?  We can only merge it in immediately prior to cutting 0.11.0.

**Comment by lhazlewood** [comment]
@bdemers isn't this done?  Just curious why it's still marked as open when #499 was merged already.

**Comment by bdemers** [comment]
Yup, it _should_ have auto closed, the tooltip in #499 even says:
> This pull request closes issue #494
