### ISSUE TITLE
The jars are not valid OSGi bundles anymore

### ISSUE THREAD

**Issue by cschneider** [jwtk/jjwt#502]
Since this commit:
https://github.com/jwtk/jjwt/commit/439c027c2effcbc0e28d4507e8201071bd14f5d4

The jars do not contain the OSGi metadata anymore. I can do a PR to add it back.

**Comment by lhazlewood** [comment]
Hi @cschneider , a PR would be much appreciated, but you'll probably want to wait until https://github.com/jwtk/jjwt/pull/488 is merged since that PR should wrap-up the remaining module relocation effort.

**Comment by cschneider** [comment]
https://github.com/jwtk/jjwt/pull/503

**Comment by cschneider** [comment]
I just reactivated using the generated manifest in the jar plugin. When this was deactivated before the jar plugin used simply the plain manifest without any OSGi metadata.
