### ISSUE TITLE
Retrofit Converter

### ISSUE THREAD

**Issue by BugsBunnyBR** [jwtk/jjwt#51]
Hi, There is any known implementation of a retrofit[1] converter using jjwt?
It would be nice to have, for instance, a GSON converter[2] with the jjwt support.
[1] - https://github.com/square/retrofit
[2] - https://github.com/square/retrofit/tree/master/retrofit-converters/gson/src/main/java/retrofit

Thanks.

**Comment by lhazlewood** [comment]
I'm inclined to close this issue if there isn't actionable work to be done by the JJWT project team.  Have you pinged the Retrofit community with the same question?

**Comment by lhazlewood** [comment]
Closing as out of scope.  Happy to reopen if there is work to be done in JJWT.
