### ISSUE TITLE
0.9.1 incompatible with Java 11 because of DatatypeConverter

### ISSUE THREAD

**Issue by oliverhausler** [jwtk/jjwt#510]
@bdemers I saw you were trying to update to Java 11, and maybe this is solved in `latest`, but I wanted to tell you 0.9.1 does not run on JDK11 because you are using `DatatypeConverter` for encoding/decoding. You may want to use `java.util.Base64` instead.

```
java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
```

**Comment by bdemers** [comment]
@oliverhausler Can you try the latest release? That _should_ be fixed already. I'm using JJWT in another project that tests on both 8 & 11.

If you run into an issue let me know and I dig a bit more!

**Comment by lhazlewood** [comment]
Deterministic Base64 support for all platforms was fixed in the 0.10.0 release 😄 

https://github.com/jwtk/jjwt/blob/master/CHANGELOG.md#0100
https://github.com/jwtk/jjwt#base64

**Comment by oliverhausler** [comment]
@lhazlewood 0.10.0 is not available in Maven.
https://search.maven.org/search?q=a:jjwt

**Comment by bdemers** [comment]
@oliverhausler that syntax on search.maven does an absolute match.
You would want `q=jjwt` or `q=a:jjwt-api`

**Comment by bdemers** [comment]
(or search by group id: https://search.maven.org/search?q=g:io.jsonwebtoken )

**Comment by oliverhausler** [comment]
Thanks, I couldn't guess that the package has been split :(

![image](https://user-images.githubusercontent.com/8090341/66074893-26383a00-e50f-11e9-8675-2ef5639fb05b.png)

**Comment by lhazlewood** [comment]
Always check the documentation first 😄 

https://github.com/jwtk/jjwt#install
