### ISSUE TITLE
Caused by: io.jsonwebtoken.lang.UnknownClassException: Unable to load class named [io.jsonwebtoken.impl.DefaultJwtParser] from the thread context, current, or system/application ClassLoaders.  All heuristics have been exhausted.  Class could not be found.

### ISSUE THREAD

**Issue by neppxiao** [jwtk/jjwt#512]
I have an Android lib A that integrated jjwt.

implementation 'io.jsonwebtoken:jjwt-api:0.10.7'
runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.10.7'
runtimeOnly('io.jsonwebtoken:jjwt-orgjson:0.10.7') {
    exclude group: 'org.json', module: 'json' //provided by Android natively
}

I have my app depends on lib A. 
implementation(libA)

When my app is running, I get the UnknownClassException issue. 
                Jwts.parser().setSigningKey(publicKey).parseClaimsJws(jwsString).body["Base64SHA256File"]

**Comment by lhazlewood** [comment]
Your `jjwt-api` declaration should be `api` not `implementation`.  Other edits may be required - to be sure, read:  https://github.com/jwtk/jjwt#install-android

In the future, we kindly request that people do not use GitHub Issues to ask questions.  We use this system for actionable work required to change JJWT's codebase.  For future questions, please read https://github.com/jwtk/jjwt#questions.  Thanks!
