### ISSUE TITLE
Document working with secret key strings

### ISSUE THREAD

**Issue by oliverhausler** [jwtk/jjwt#517]
I have a string secret:
```
String secret = "EqjWQ7MYqS4VkF2vZLNOOH9r4XVa3XrIsibni4cJ6eEsAphTKHvnMoRmZdfC0PLD";
```

I am signing like this, but you have deprecated:
```
Jwts.builder().signWith(SignatureAlgorithm.HS256, secret)
```

So I assume there must be an equivalent, but this here gives me a different token:
```
SecretKey key = Keys.hmacShaKeyFor(SECRET.getBytes());
Jwts.builder().signWith(key, SignatureAlgorithm.HS256)
```

Would you please document how the key must be created to maintain compatibility.

**Comment by klehelley** [comment]
As can be seen in the JavaDoc for the `signWith` method (I haven't been able to rapidly find the formatted JavaDoc for the project, so I falled back to reading it in the code instead), the second argument is a Base64 representation of the secret key. By calling `String.getBytes()`, you are just converting the characters into their byte equivalent. Which is different than converting the Base64 string into its byte equivalent.

Normally, you should be able to convert your string in a way that works the same as the deprecated method by using `byte[] bytesSecret = java.util.Base64.getDecoder().decode(SECRET);`.

**Comment by lhazlewood** [comment]
Thanks for creating this issue to indicate that the current docs weren't sufficient for answering your question.  This is answered here:

https://stackoverflow.com/questions/40252903/static-secret-as-byte-key-or-string

But definitely should be in the proper JJWT documentation/readme.  We'll use this issue to represent the work to do so.

**Comment by lhazlewood** [comment]
Also note that, if you're going to use an HMAC-SHA algorithm and your secret key string is:

* Base64-encoded:
    
        Key secretKey = Keys.hmacShaKeyFor(Decoders.BASE64.decode(secretString));

* Base64URL-encoded:
    
        Key secretKey = Keys.hmacShaKeyFor(Decoders.BASE64URL.decode(secretString));

* Not encoded at all (e.g. a raw password string):
    
        Key secretKey = Keys.hmacShaKeyFor(secretString.getBytes(StandardCharsets.UTF_8));
    It is always incorrect to call `secretString.getBytes()` (without providing a charset).

**Comment by oliverhausler** [comment]
Thank you guys, confirmed working.
