### ISSUE TITLE
serializeToJsonWith method not present

### ISSUE THREAD

**Issue by sapangarg** [jwtk/jjwt#527]
i am trying to use serializeToJsonWith method present in Jwts.builer(), but it shows that the function is not there.

**Comment by lhazlewood** [comment]
Hi there!

This feature was introduced in version 0.10.0.  Please ensure your project uses 0.10.7 and you'll see the method.

Also, in the future, we respectfully request that people do not use GitHub Issues for asking usability questions.  We reserve this system for items that require changes to JJWT's codebase (feature requests, bugs, actionable work items, etc).  Thanks!

https://github.com/jwtk/jjwt#help-questions
