### ISSUE TITLE
/ converted to \/ [BUG]

### ISSUE THREAD

**Issue by hamam99** [jwtk/jjwt#533]
I have payload data for JWT `"route": "api/post-test"`, the generated JWT token was different from JWT token that I convert manual from website. So, i try decode generated token and found that  `"route": "api/post-test"` converted to ``"route": "api\/post-test"`.  Is it bug? Or anyone have solution?

**Comment by lhazlewood** [comment]
What is your test case? Do you have any code that we can run?  What website are you talking about?

**Comment by lhazlewood** [comment]
This works as expected:

```java
@Test
void testFoo() {
    Key key = Keys.secretKeyFor(SignatureAlgorithm.HS256);
    String claimKey = "route";
    String claimValue = "api/post-test";

    String jws = Jwts.builder().claim(claimKey, claimValue).signWith(key).compact();

    String parsedValue = Jwts.parserBuilder().setSigningKey(key).build().parseClaimsJws(jws).getBody().get(claimKey);

    assert claimValue.equals(parsedValue);
}
```

I don't know what website you're using, but JJWT doesn't assume validity in any website/tool.  It follows only the RFC standards published by the IETF.

**Comment by hamam99** [comment]
This is my payload 
`{
 typ: "JWT",
 alg: "HS256"
}.
{
 method: "GET",
 route: "api/get-test"
}`

It is the JWT token `eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZXRob2QiOiJHRVQiLCJyb3V0ZSI6ImFwaVwvZ2V0LXRlc3QifQ.gEup5umGYFl4WO0jVLh5mxaHa76GVZhJx55VsCUQS5Y`. The secret key is "_1234567890123456789012345678901234567890_".

But when  i  decode the jwt token using website _http://calebb.net/_ , I get result 
`{
 typ: "JWT",
 alg: "HS256"
}.
{
 method: "GET",
 route: "api\/get-test"
}`. 
The JWT token become mismatch with server because we match the JWT token generated by  android with JWT token generated by server.

**Comment by lhazlewood** [comment]
http://calebb.net must have a bug.  Other online decoders work just fine, for example https://www.jsonwebtoken.io as shown here:

![image](https://user-images.githubusercontent.com/121180/69169919-2a241980-0ac7-11ea-958c-2fd02d5744d5.png)


JJWT encodes and decodes properly, so this is not a JJWT issue, so I'm closing this bug report (it's not a JJWT bug).  You might want to report a bug with calebb.net and ask them to fix their implementation.   Good luck!

**Comment by hamam99** [comment]
Thank you for your response. I had fixed it with using
`.serializeToJsonWith(new GsonSerializer<>())` it will removing _escape string_ (_additional \_) .
