### ISSUE TITLE
java.util.map cannot be inherited with different type arguments 'String and null'

### ISSUE THREAD

**Issue by Zwilla** [jwtk/jjwt#538]
java.util.map cannot be inherited with different type arguments 'String and null'

https://github.com/jwtk/jjwt/blob/master/impl/src/main/java/io/jsonwebtoken/impl/DefaultJwsHeader.java

Error here:

public class DefaultJwsHeader extends DefaultHeader implements JwsHeader {

how to fix this?

Note, without fixing it will return always null

thx

**Comment by lhazlewood** [comment]
I don't understand the problem.  What does your code using JJWT look like?  Can you show how this is a problem for you in your project?

**Comment by lhazlewood** [comment]
Closing due to lack of follow-up from OP.
