### ISSUE TITLE
java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter When setup sign

### ISSUE THREAD

**Issue by FaustPipeDream** [jwtk/jjwt#543]
Hello, I' using 
```
<dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt</artifactId>
            <version>0.9.1</version>
  </dependency>
```
and When I setup sign use 
` Jwts.builder().signWith(SignatureAlgorithm.HS512, SECRET)`
I got a mistake 

> java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
> 	at io.jsonwebtoken.impl.Base64Codec.decode(Base64Codec.java:26) ~[jjwt-0.9.1.jar:0.9.1]
> 	at io.jsonwebtoken.impl.DefaultJwtBuilder.signWith(DefaultJwtBuilder.java:99) ~[jjwt-0.9.1.jar:0.9.1]
> 
What should I do to solve this problem?

**Comment by lhazlewood** [comment]
Please upgrade to the latest stable 0.10.7 release.  Enabling it in your project is documented here: https://github.com/jwtk/jjwt#install

**Comment by FaustPipeDream** [comment]
Thank you  It really works
