### ISSUE TITLE
JWT Expiration 10 years

### ISSUE THREAD

**Issue by feras-ngss** [jwtk/jjwt#562]
hi all, thanks for being there to help.
i was woundering is it okay to set a long value to the :
.setExpiration(new Date(System.currentTimeMillis() + 864000000))

to make the expiry date 10 years 
or we can just ignore the date it self and the token will never expire ? 
thank you

**Comment by lhazlewood** [comment]
Hi there!  In the future, please as questions per https://github.com/jwtk/jjwt#questions

That said, you don't need to set an expiration at all if you don't want to.  This is better in my opinion than setting a super long expiration like 10 years.

Ordinarily, most people wouldn't do this however, especially if the JWT is used for authentication or authorization.  If it is ever lost or stolen or intercepted, the person or thing that has the JWT (called the 'bearer') can use it to impersonate your or the system represented by the JWT.

So whether you use an expiration or not is entirely based on your application based on your needs/requirements.  Most secure production applications would not do this however.

Please ask any follow up questions as described in https://github.com/jwtk/jjwt#questions and we kindly ask that GitHub Issues be used only to track actionable work for changing the JJWT codebase.  Thanks!

**Comment by feras-ngss** [comment]
thank you very much for helping, and sorry for the bad behaviour of the way of posting the issue .
for me i will never do it but in fact this is a customer requirement

annways i solve it by passing null to the method.

thanks again.
