### ISSUE TITLE
Compile error - incompatible inheritance

### ISSUE THREAD

**Issue by jmht** [jwtk/jjwt#57]
In just pulling project from GitHub and building (mvn clean verify), I receive the following compile error:
<pre>
[ERROR] /F:/Code/jjwt/src/main/java/io/jsonwebtoken/impl/DefaultJwsHeader.java:[22,8] F:\Code\jjwt\src\main\java\io\jsonwebtoken\impl\DefaultJwsHeader.java:22: java.util.Map cannot be inherited with different arguments: &lt;&gt; and &lt;java.lang.String,java.lang.Object&gt;
</pre>
Looking at the code, it does appear to be a consequence of DefaultJwsHeader being a raw type where it is using/inheriting from others which are parameterized.

mvn --version
<pre>
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T16:58:10-04:00)
Maven home: C:\Programs\Apache\apache-maven-3.2.3\bin\..
Java version: 1.6.0_45, vendor: Sun Microsystems Inc.
Java home: C:\Progra~1\Java\jdk1.6.0_45\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows server 2012", version: "6.2", arch: "amd64", family: "windows"
</pre>

**Comment by lhazlewood** [comment]
You're compiling with JDK 6 - that product has been end-of-lifed *long* ago - it is not supported by JJWT.
