### ISSUE TITLE
> You forgot the `jjwt-impl` .jar:

### ISSUE THREAD

**Issue by avercastadmin** [jwtk/jjwt#572]
> You forgot the `jjwt-impl` .jar:
> 
> https://github.com/jwtk/jjwt#dependencies

OMG. Why? I'm using maven (uber jar) and I do not want external libs. The final jar does not contain the jjwt-impl classes but I can access the classes in IntelliJ

And where do I put the .JAR file?

This doesn't seem to work. The resulting JAR does not contain the implementation classes.

```
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-api</artifactId>
            <version>0.10.5</version>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-impl</artifactId>
            <version>0.10.5</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-jackson</artifactId>
            <version>0.10.5</version>
            <scope>runtime</scope>
        </dependency>
```

_Originally posted by @SharkFourSix in https://github.com/jwtk/jjwt/issues/447#issuecomment-508288658_

**Comment by yonetmen** [comment]
I'm having the same problem.

**Comment by lhazlewood** [comment]
For usability questions, please read https://github.com/jwtk/jjwt#help-questions

I can assure you that the classes are definitely in the respective .jar files, which means there is something wrong with how you are creating your fat jar - maybe a maven plugin configuration, or similar.  Double-check that whatever approach you are using ensures runtime dependencies are included in addition to compile dependencies.  Also, if you can, please ensure you're using the latest stable JJWT version, which is 0.11.0 at the time of writing.

Feel free to provide a sample (tiny) maven project that demonstrates your problem and we can see if we can help, but IMO this isn't really a JJWT question, but a general "fat jar with dependencies" question.

**Comment by yonetmen** [comment]
The problem occurred after we bumped the version to **0.11.0** The version **0.10.8** worked without a problem.

**Comment by SharkFourSix** [comment]
My solution was very easy: I switched to another library 😁
________________________________

**Comment by lhazlewood** [comment]
@yonetmen that's literally the only change you made?  A version number reference and nothing else?  What Java version are you using?

**Comment by yonetmen** [comment]
We are using dependabot to update our dependencies. Version from  0.10.8 to 0.11.0 was the only change in the build. We are using Java 11.

**Comment by SharkFourSix** [comment]
My solution was very easy: I switched to another library 😁. Long time ago.
________________________________

**Comment by lhazlewood** [comment]
@yonetmen how are you creating your "fat jar"?  What maven settings?  Do you have a mini project or maven snippet that we can use to try to re-create the issue?  If it is indeed something in JJWT's packaging structure, of course we will fix it immediately, but I can't see how it would be impacted by the 0.11.0 release.  Thanks for anything you can give us!
