### ISSUE TITLE
Update to LocalDateTime instead of the old Date API

### ISSUE THREAD

**Issue by dstr89** [jwtk/jjwt#577]
In my Unit tests I would like to use something like this to fix the time when validating JWT:

```
Instant.now(Clock.fixed(
                Instant.parse("2018-08-22T10:00:00Z"),
                ZoneOffset.UTC));
```
But this is not possible since JJWT uses the old date API. In DefaultClock now() method.

BR,
Daniel

**Comment by lhazlewood** [comment]
Closing as a duplicate of #235 .  In the meantime, you'll need to convert the JDK 8+ time concepts into a `java.util.Date`.  HTH!
