### ISSUE TITLE
Upgrade jackson-databind to 2.9.10.4

### ISSUE THREAD

**Issue by pidzama** [jwtk/jjwt#585]
Again there is couple of new critical vulnerabilities detected in jackson-databind that affect versions before 2.9.10.4 [Search result](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=jackson-databind+before+2.9.10.4&search_type=all)

**Comment by lhazlewood** [comment]
Merged to master via https://github.com/jwtk/jjwt/pull/587

Thanks!

**Comment by pidzama** [comment]
Great! Thanks.
