### ISSUE TITLE
Maps.MapBuilder::and does not return parameterized MapBuilder

### ISSUE THREAD

**Issue by chtseac** [jwtk/jjwt#591]
https://github.com/jwtk/jjwt/blob/7090bf39c3e457f274967af50105a880a42af26b/api/src/main/java/io/jsonwebtoken/lang/Maps.java#L66

Using `and` even once and the type parameters are erased and you have to put `@SuppressWarnings("unchecked")` on that line.

    @SuppressWarnings("unchecked")
    Map<String, String> myMap = Maps
        .<String, String>of("key1", "value1")  // MapBuilder<String, String>
        .and("key2", "value2")                 // MapBuilder
        .build();                              // Map

**Comment by lhazlewood** [comment]
cc @bdemers
