### ISSUE TITLE
jackson-databind security issues concern

### ISSUE THREAD

**Issue by xjune123** [jwtk/jjwt#593]
hi 
jjwt  jjwt-jackson has imported jackson-databind 2.9.8,but this version has  a security hole.
when do you improve jasckson-databind version? or can I exclude jackson-databind and import new version?

security issues:
https://github.com/FasterXML/jackson-databind/issues/2620

**Comment by lhazlewood** [comment]
You always have control over what transitive dependencies you can exclude (and then re-define explicitly in your project) via Maven dependency exclusions:

https://www.viralpatel.net/maven-ignore-transitive-dependency/

You can do the same if using Gradle.  This example shows excluding the `org.json` dependency:

https://github.com/jwtk/jjwt#dependencies

This allows you to use whatever version of Jackson you want if a library author (e.g. JJWT) doesn't publish a new release on your timeline.

**Comment by lhazlewood** [comment]
P.S. this fix was already merged into the `master` branch via https://github.com/jwtk/jjwt/pull/587

**Comment by xjune123** [comment]
thank you
