### ISSUE TITLE
ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve io.jsonwebtoken:jjwt-api:0.11.1.

### ISSUE THREAD

**Issue by sanshah** [jwtk/jjwt#594]
I was trying to add dependency in my Android application. I have added below code in build.gralde file as mentioned here: https://github.com/jwtk/jjwt#dependencies

`api 'io.jsonwebtoken:jjwt-api:0.11.1'`
  `runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.1'`
    `runtimeOnly('io.jsonwebtoken:jjwt-orgjson:0.11.1') {`
        `exclude group: 'org.json', module: 'json' //provided by Android natively`
    `}`

But once I add above dependencies, I am getting below error:
`ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve io.jsonwebtoken:jjwt-api:0.11.1.`

I also have updated proguard files as mentioned here: https://github.com/jwtk/jjwt#proguard

What could be the problem here? Did I miss anything?

**Comment by lhazlewood** [comment]
It looks like you declared it correctly.  Did you ever resolve this?

It is unclear to me if something would have changed in Android that prevents the dependencies from loading correctly.

As a test, can you see if just changing the version to 0.10.7 solves it for you?  If so, we know something might have been introduced in the 0.11.x release.  I don't really think that would be the case, but it might be worth a try.  Please let us know!

**Comment by lhazlewood** [comment]
@sanshah any update?

**Comment by sanshah** [comment]
@lhazlewood  Sorry for the delay. It got resolved. There was issue with my IDE and build system. After upgrading it, this issue has been resolved. Thanks
