### ISSUE TITLE
java.lang.NoClassDefFoundError: io/jsonwebtoken/Jwts

### ISSUE THREAD

**Issue by VilleMiekkoja** [jwtk/jjwt#599]
java.lang.NoClassDefFoundError: io/jsonwebtoken/Jwts

When I run locally with `mvn spring-boot:run` , there's no problem.

But when I package my application into a fully executable jar with `mvn clean install`and then run the jar as a systemd service, I get this error seen above.

It comes from this line:

```
String user = Jwts.parser()...
```

Some information:
Version of this package that the issue occurs: 0.11.1
Platform: Ubuntu 18.04
Related dependency in maven pom.xml:
```
<dependency>
    <groupId>io.jsonwebtoken</groupId>
    <artifactId>jjwt-impl</artifactId>
    <version>0.11.1</version>
</dependency>
```

Also I checked the generated jar file, the dependency jjwt-impl.0.11.1 is there:

BOOT-INF.lib.jjwt-impl-0.11.1.jar
BOOT-INF.lib.jjwt-api-0.11.1.jar
BOOT-INF.lib.jjwt-jackson-0.11.1.jar

Don't know how to solve this. I thought just adding the io.jsonwebtoken to maven dependency would solve all things related to classpath etc..

**Comment by lhazlewood** [comment]
`io.jsonwebtoken.Jwts` is in the `jjwt-api` .jar file.  It appears as if the .jar files are not being added to the classpath - i.e. whatever packaging mechanism you're using is not putting the .jars in the correct place, or does not have that location added to the classpath.

**Comment by VilleMiekkoja** [comment]
When I generate the classpath from the root of my app, it generates a file called classpath, and that has the jjwt-api in it:

jjwt-api-0.11.1.jar

I package the jar with just `mvn clean install -Dmaven.test.skip=true`

And in my pom.xml I have:

```
<plugin>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-maven-plugin</artifactId>
	<configuration>
		<profiles>
                 ...
		</profiles>
		<jvmArguments>
		    -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8085
		</jvmArguments>
		<executable>true</executable>
	</configuration>
</plugin>
```

**Comment by lhazlewood** [comment]
Not sure - you might want to reach out on the Spring Boot forums?  This doesn't appear to be a JJWT issue, but a Spring Boot packaging one.

**Comment by VilleMiekkoja** [comment]
Could be issue with spring-boot packaging. However my app does find other external libraries without problem it feels. Only problem is with this one so far.

**Comment by VilleMiekkoja** [comment]
I debug logged the actual classpath for the app inside the application, and for the jar version the actual classpath is the jar file itself. It makes sense since the jar file does contain the jjwt dependencies. So it should find it from classpath, but for some reason does not?

**Comment by lhazlewood** [comment]
Is there a mini/test Spring Boot project we could clone that re-creates the problem?  That way we can test what you're seeing.

**Comment by VilleMiekkoja** [comment]
At the moment no, but if I am unable to fix this soon, I'll create a one.

I tried updating maven package spring-boot-starter-parent which handles packaging to 1.5.2.RELEASE -> 1.5.22.RELEASE, and now Im getting a different error:

java.lang.NoClassDefFoundError: org/apache/tomcat/util/http/parser/AcceptLanguage

**Comment by VilleMiekkoja** [comment]
Problem fixed. Updated package spring-boot-starter-parent to latest version (2.3.0), and the error no longer appears. This can be closed, thank you and sorry for taking your time.

**Comment by lhazlewood** [comment]
Glad to hear you got it working!
