### ISSUE TITLE
Support for BiometricPrompt.CryptoObject signing on Android platforms

### ISSUE THREAD

**Issue by FeiChen-okta** [jwtk/jjwt#603]
Add support for signing with `java.security.Signature` in JwtBuilder.
Currently when using biometrics in Android platforms, the application does not have access to the `Key` if it is protected by biometrics.
Android sends back an CryptoObject containing the `Signature` once fingerprint is verified.
Would like to use this signature object to sign the JWT. Like the following:
```
Jwts.builder().signWith(signature).compact()
```
Working around this by using a different key to sign and get the JWS. Then convert the JWS to JWT and using the signature object from CryptoObject to sign. 

Reference:
https://developer.android.com/reference/android/hardware/biometrics/BiometricPrompt.CryptoObject
https://docs.microsoft.com/en-us/xamarin/android/platform/fingerprint-authentication/creating-a-cryptoobject

**Comment by lhazlewood** [comment]
This will be possible when #493 is resolved, so I'd like to close this as a duplicate of that issue.  Feel free to comment if you feel otherwise!
