### ISSUE TITLE
RequireIssuer checks multiple issuers

### ISSUE THREAD

**Issue by oussamaachech** [jwtk/jjwt#604]
It would be nice if the `JwtParserBuilder requireIssuer` can accept an array of issuer Strings in order to check if the 'iss' from the parsed jwt token matches one of these issuers.

**Comment by lhazlewood** [comment]
This should be completed as part of #336

**Comment by ars-java** [comment]
Is anybody implementing it? If not I can take this issue.

**Comment by lhazlewood** [comment]
Reopening.  However, we're introducing a new validation framework for 1.0, so the implementation of this will be dependent upon that, so please no pull requests for this feature just yet - until that is finished.

**Comment by lhazlewood** [comment]
Closing this in favor of #474 .  The `require`* methods were too numerous and didn't do nearly enough, but #474 will allow an entire range of validations.
