### ISSUE TITLE
How i can verify PS256 with java 1.8?

### ISSUE THREAD

**Issue by vkovalch** [jwtk/jjwt#606]
jws = Jwts.parserBuilder()
                        .setSigningKey(publicKey)
                        .build()
                        .parseClaimsJws(jwtString);
except with error:
io.jsonwebtoken.security.SignatureException: Unavailable RSA Signature algorithm 'RSASSA-PSS'.

How i can verify?

dependencies {
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.0.9'
    compileOnly 'com.github.pengrad:jdk9-deps:1.0'
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    api 'io.jsonwebtoken:jjwt-api:0.11.2'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.2', 'org.bouncycastle:bcprov-jdk15on:1.60'
    runtimeOnly('io.jsonwebtoken:jjwt-orgjson:0.11.2') {
        exclude group: 'org.json', module: 'json' 
    }
    //implementation 'org.bouncycastle:bcprov-jdk15on:1.60'
    implementation 'io.jsonwebtoken:jjwt-api:0.11.2'
...
}

**Comment by lhazlewood** [comment]
You'll need to check your dependency declarations and ensure BouncyCastle is declared properly.

Just a friendly reminder: JJWT's GitHub issues are for actionable work that requires changes to the JJWT codebase. Please use StackOverflow with the `#jjwt` tag for usability/help questions. Thanks!
