### ISSUE TITLE
JWT NBF and clock drift

### ISSUE THREAD

**Issue by timchaffee** [jwtk/jjwt#61]
4.1.4.  "exp" (Expiration Time) Claim

   The "exp" (expiration time) claim identifies the expiration time on
   or after which the JWT MUST NOT be accepted for processing.  The
   processing of the "exp" claim requires that the current date/time
   MUST be before the expiration date/time listed in the "exp" claim.
   **Implementers MAY provide for some small leeway, usually no more than
   a few minutes, to account for clock skew.**  Its value MUST be a number
   containing a NumericDate value. Use of this claim is OPTIONAL.

4.1.5.  "nbf" (Not Before) Claim

   The "nbf" (not before) claim identifies the time before which the JWT
   MUST NOT be accepted for processing.  The processing of the "nbf"
   claim requires that the current date/time MUST be after or equal to
   the not-before date/time listed in the "nbf" claim.  **Implementers MAY
   provide for some small leeway, usually no more than a few minutes, to
   account for clock skew.**  Its value MUST be a number containing a
   NumericDate value.  Use of this claim is OPTIONAL.

Any chance you can add the ability to set a skew/drift parameter to the exp and nbf check?

**Comment by lhazlewood** [comment]
Thanks for the issue - any suggestions on how this would be specified by a JJWT user?

**Comment by timchaffee** [comment]
Hmm - not sure - maybe:

Jwts.parser().setSigningKey(key).**setAllowedClockSkew(3)**.parseClaimsJws(s).getBody().getSubject().equals("Joe");

**Comment by ca0abinary** [comment]
+1 jose4j has similar functionality: https://bitbucket.org/b_c/jose4j/wiki/JWT%20Examples

**Comment by mrwilby** [comment]
+1 . Thinking how to do this now myself.

**Comment by lhazlewood** [comment]
fixed in master thanks to @ MichaelSims.  Will be in 0.7 shortly.
