### ISSUE TITLE
is it Safe to use SecretKey and JwtParser as static fields

### ISSUE THREAD

**Issue by john77eipe** [jwtk/jjwt#615]
Is it perfectly safe to use SecretKey and JwtParser as static fields in a spring application

```
private static SecretKey hmacKey = Keys.secretKeyFor(SignatureAlgorithm.HS256);
private static JwtParser jwtParser = Jwts.parserBuilder().setSigningKey(hmacKey).build();
```

Thanks

**Comment by lhazlewood** [comment]
Hi John!

(just a minor request if it's not too much trouble - for questions in the future, please read: https://github.com/jwtk/jjwt#help-questions (thanks!))

That said, when using `Jwts.parserBuilder()`, the `JwtParser` returned from `build()` is immutable, so yes, it is thread-safe and may be used as an application singleton ;)

Cheers!
