### ISSUE TITLE
My massage

### ISSUE THREAD

**Issue by qahari1978** [jwtk/jjwt#622]
Parse error on line 1:
��1Tt5AJ�8�VBV��xQL
^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'

**Comment by lhazlewood** [comment]
This isn't enough information to diagnose the problem.  Do you have test code we can execute that allows us to re-create the problem?

**Comment by lhazlewood** [comment]
No follow up answer or test case - closing.
