### ISSUE TITLE
Jwts.parser() works with incorrect signing keys at times

### ISSUE THREAD

**Issue by somasundaramsekar** [jwtk/jjwt#63]
SignatureAlgorithm signatureAlgorithm = SignatureAlgorithm.HS256;

        long nowMillis = System.currentTimeMillis();

        Date now = new Date(nowMillis);

        byte[] apiKeySecretBytes = DatatypeConverter.parseBase64Binary("8754487552");

        Key signingKey = new SecretKeySpec(apiKeySecretBytes, signatureAlgorithm.getJcaName());

        Map<String, Object> map = new HashMap<String, Object>();

        map.put("service", "emailverification");
        map.put(Claims.EXPIRATION, new Date(now.getTime() + 3600));

        JwtBuilder builder = Jwts.builder()
                .setClaims(map).signWith(signatureAlgorithm, signingKey);

        String jwt = builder.compact();

        Claims claims = Jwts.parser()
                .setSigningKey(DatatypeConverter.parseBase64Binary("8754487552")).parseClaimsJws(jwt).getBody();

        Claims claims1 = Jwts.parser()
                .setSigningKey(DatatypeConverter.parseBase64Binary("875448755")).parseClaimsJws(jwt).getBody();

        System.out.println("Expiration: " + claims.getExpiration());
        System.out.println("Service: " + claims.get("service"));

        System.out.println("Expiration: " + claims1.getExpiration());
        System.out.println("Service: " + claims1.get("service"));

both claims and claims1 are created where in the provided key for claims1 is different from the one that is used to sign it

**Comment by lhazlewood** [comment]
The test is invalid:  your test key lengths are invalid per the [HMAC-SHA2](https://tools.ietf.org/html/rfc4868) specification and cannot satisfy the specification's integrity protection guarantees.

When used for integrity/authentication verification (as JWS does), HMAC-SHA2 key lengths *must* be equivalent to the output length.  For HMAC-SHA-256, the output is 256 bits (32 bytes), so your key must also be 256 bits/32 bytes.  Similarly, HMAC-SHA-384 requires 384 bits (48 bytes) and HMAC-SHA-512 requires 512 bits (64 bytes).   For reference:

https://tools.ietf.org/html/rfc4868#section-2.1.1

and 

https://tools.ietf.org/html/rfc4868#section-2.6

(The 'auth/integ' ones are the relevant ones).

JJWT provides key generation methods for you to ensure you always have a valid (secure-randomly-generated) key to use:

```java
SignatureAlgorithm sigAlg = SignatureAlgorithm.HS256; //or HS384 or HS512
SecretKey key = MacProvider.generateKey(sigAlg);
//key is a length that is appropriate for the specified HMAC-SHA2 algorithm
```
