### ISSUE TITLE
Could not able to package using Maven

### ISSUE THREAD

**Issue by mohammedkalimullah** [jwtk/jjwt#635]
We are planning to use this JWT in our peoplesoft Application. but i could not able package this as JAR file. Please help advise.
![image](https://user-images.githubusercontent.com/53372610/102876957-f01f0700-4480-11eb-9d41-71893977c8fc.png)

**Comment by lhazlewood** [comment]
Did you find out what the problem was?  What JDK did you use to build?

**Comment by lhazlewood** [comment]
Closing for now - you might wish to reference this repository's .travis.yml file - it performs the full Maven builds (and a test/coverage build) across multiple operating systems, and they all work fine.
