### ISSUE TITLE
Broken dependency for Flow9 project: cannot find symbol Jwts.parserBuilder()

### ISSUE THREAD

**Issue by advancedwebdeveloper** [jwtk/jjwt#636]
Hi there.

I am experiencing some oddities with your library (v 0.10.8) , while trying to build Java packages of [Flow9](https://github.com/area9innovation/flow9) project:

https://github.com/area9innovation/flow9/issues/729
.
I am neither sure if it is acceptable to migrate to the latest version of your package nor whether is the cause of the issues with v. 0.10.8.
My experience with Java APIs allows to understand that the implementation is not properly referenced.
Please advise how to resolve this:
https://github.com/area9innovation/flow9/blob/a91e00661b45ae9305a5f59a89a3f257ec335c7b/platforms/java/com/area9innovation/flow/FlowJwt.java
.

Expecting to test this on i686 (Ubuntu 18) and rv64gc (https://en.opensuse.org/openSUSE:RISC-V) .

**Comment by advancedwebdeveloper** [comment]
CC @alstrup

**Comment by lhazlewood** [comment]
The method you refer to (`Jwts.parserBuilder()`) was introduced in 0.11.0 per https://github.com/jwtk/jjwt/blob/master/CHANGELOG.md#0110.  You must be using that version or later to reference that method.

**Comment by forinda** [comment]
> The method you refer to (`Jwts.parserBuilder()`) was introduced in 0.11.0 per https://github.com/jwtk/jjwt/blob/master/CHANGELOG.md#0110. You must be using that version or later to reference that method.

Thanks 👍🏾
