### ISSUE TITLE
Retrieve all token's headers

### ISSUE THREAD

**Issue by Fabryprog** [jwtk/jjwt#64]
Hello, an interface Jwt (io.jsonwebtoken)  has only two methods: getHeader() and getBody().

How to retrieve ALL token's headers? I am thinking a method like "getHeaders()".

Can i do it?

thankx

**Comment by lhazlewood** [comment]
The JWT specification calls all the headers just 'header', which is why JJWT's `jwt.getHeader()` method is named that way.  When you call `jwt.getHeader()`, you are actually getting all of the headers.   It's just a map.  Call `toString()` on it and see :)
