### ISSUE TITLE
Could not resolve io.jsonwebtoken:jjwt-api:0.9.1

### ISSUE THREAD

**Issue by hadestructhor** [jwtk/jjwt#640]
I'm trying to use jjwt with spring boot and I used gradle like it's said in the readme of this github like this :
```
dependencies {
    api 'io.jsonwebtoken:jjwt-api:0.11.2'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.2' 
    runtimeOnly('io.jsonwebtoken:jjwt-orgjson:0.11.2') {
        exclude group: 'org.json', module: 'json' //provided by Android natively
    }
```

and changed the version from 0.11.2 to 0.9.1 because I'm following [this guide](https://bezkoder.com/spring-boot-jwt-authentication/) that uses this library.

I keep getting this error message even when switching to the newest version: 
```
Could not resolve io.jsonwebtoken:jjwt-api:0.9.1.

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by scharrua** [comment]
Hello!
I have the same error when trying to add :
```
<dependency>
    <groupId>io.jsonwebtoken</groupId>
    <artifactId>jjwt</artifactId>
    <version>0.9.1</version>
</dependency>
```

to my pom.xml file. 

Any clue on how to solve this?

**Comment by martinvisser** [comment]
@hadestructhor There is no `jjwt-api` version `0.9.x`, that was introduced in `0.10.0`. See for example https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-api. The question is why you need to downgrade though.

@scharrua Your dependency is just fine, which should resolve normally. See https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt/0.9.1.

To me, this doesn't sound like an issue of jjwt, just a misconfiguration.

**Comment by lhazlewood** [comment]
Artifact names changed with the 0.10.x release, so when you downgraded below 0.10.x, the names were incorrect.  Please read the following for the correct current names:

https://github.com/jwtk/jjwt#install

**Comment by Mark-i7** [comment]
@scharrua Hi. How did you solve that error?:D

**Comment by scharrua** [comment]
@Mark-i7  just added the following lines to my pom.xml file:

```
		<!--  JWT Dependencies for authentication process -->	
		<!--  from tutorial https://bezkoder.com/spring-boot-jwt-authentication/  -->	 		
				
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		
		<!-- https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt -->
		<dependency>
		    <groupId>io.jsonwebtoken</groupId>
		    <artifactId>jjwt</artifactId>
		    <version>0.9.1</version>
		</dependency>
		
       <!--  end of JWT Dependencies --> 	
		
```

**Comment by AlisonPAnderson** [comment]
@Mark-i7  did that jjwt 0.9.1 solution work for you? neither that or these worked for me:
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-api</artifactId>
			<version>0.11.5</version>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-impl</artifactId>
			<version>0.11.5</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-jackson</artifactId> 
			<version>0.11.5</version>
			<scope>runtime</scope>
		</dependency>

**Comment by tamilvanan31** [comment]
Thank you @AlisonPAnderson, this worked for me

**Comment by Tobyha01** [comment]
I am also having the same issue, I have the io.jsonwebtoken:jjwt:0.9.1 in my build.gradle and when importing: io.jsonwebtoken.* I don't have an issue, but I have the same error for the import io.jsonwebtoken.io.Decoders and io.jsonwebtoken.security.Keys. So it clearly works for some imports but not for others, any solutions please?

**Comment by devJoseOtavio** [comment]
@Tobyha01 
if you are using intellij idea (ctrl+shift+o) it might solve the problem

**Comment by danbalves** [comment]
> @Mark-i7 did that jjwt 0.9.1 solution work for you? neither that or these worked for me: io.jsonwebtoken jjwt-api 0.11.5 io.jsonwebtoken jjwt-impl 0.11.5 runtime io.jsonwebtoken jjwt-jackson 0.11.5 runtime

thank you @AlisonPAnderson , this worked!

**Comment by gg2033** [comment]
> @Mark-i7 did that jjwt 0.9.1 solution work for you? neither that or these worked for me: io.jsonwebtoken jjwt-api 0.11.5 io.jsonwebtoken jjwt-impl 0.11.5 runtime io.jsonwebtoken jjwt-jackson 0.11.5 runtime

You are a genius

**Comment by alisina123** [comment]
> @Tobyha01 if you are using intellij idea (ctrl+shift+o) it might solve the problem
yes , thanks it is working for me

**Comment by mburuian6** [comment]
For me (using gradle) with the lib combo, explicitly adding the version worked :

```
implementation("io.jsonwebtoken:jjwt-api:0.11.5")
implementation("io.jsonwebtoken:jjwt-impl:0.11.5")
implementation("io.jsonwebtoken:jjwt-jackson:0.11.5")
```

**Comment by lhazlewood** [comment]
@mburuian6 these are incorrect.  `jjwt-impl` should _never_ be `implementation` scope and `jjwt-jackson` _usually_ should not be `implementation` scope.

**Comment by lhazlewood** [comment]
Everyone, please read the documentation appropriate for the version you are using.  We always have an `installation` section, with build-tool-specific instructions.

For `0.11.5`, that is here:  https://github.com/jwtk/jjwt/tree/0.11.5#installation.
