### ISSUE TITLE
DefaultClaims not immutable

### ISSUE THREAD

**Issue by ffroliva** [jwtk/jjwt#656]
https://github.com/jwtk/jjwt/blob/a4130dd1ec5d4bef4b1835927a2a1d966a519109/impl/src/main/java/io/jsonwebtoken/impl/JwtMap.java#L103

Hi,

I recently faced an issue in my code while setting claims using google guava ImmutableMap.
Since ImmutableMap is immutable no new data can be added to the claims and if so it will throw an exception. I would suggest making `DefaultClaims (JwtMap)` immutable. How does that sound?

The ideia is that every new data added to the claims map would generate a new map. JwtMap should not rely on provided map object but replace by its own internal map instance (having total control of the object creation).

I am currently working with version 0.9.1 but this issue also applies to version 0.11.2.

Regards,

Flávio Oliva

**Comment by bdemers** [comment]
Hi @ffroliva!

I'm not sure I'm following this 100%.

I only took a quick look, but it looks like JwtMap shouldn't rely on the map you pass in.  I'm likely missing something though, can you provide a quick snippet example, and the stacktrace you see?

https://github.com/jwtk/jjwt/blob/a4130dd1ec5d4bef4b1835927a2a1d966a519109/impl/src/main/java/io/jsonwebtoken/impl/JwtMap.java#L30-L40

Which version of JJWT are you using?

**Comment by ffroliva** [comment]
I currently can not generate a proper sample project, but here is the overall idea.

This code is from version 0.9.1 which is the version I am currently working with.

```java
        final Map<String, Object> claims = ImmutableMap.of("my-claim", "my-claim");
        final String subject = "admin";
        return Jwts.builder()
                .setSubject(subject)
                .setClaims(claims)
                .setIssuedAt(new Date(System.currentTimeMillis()))
                .setExpiration(new Date(System.currentTimeMillis() + 30000L))
                .signWith(SignatureAlgorithm.HS512, "SECRET")
                .compact();
```

Hi `JwtMap(Map<String, ?> map)` accept any `Map` implementation. if I create a claim using `ImmutableMap` this code will throw an exception because `setSubject(subject)` calls `map.put()` which is invalid from `ImmutableMap` perspective.

**Comment by lhazlewood** [comment]
The 0.10.0 release changed from using a direct assignment of the map to a copy constructor (https://github.com/jwtk/jjwt/blob/0.10.0/impl/src/main/java/io/jsonwebtoken/impl/JwtMap.java#L40) to avoid situations like these and prevent unexpected/uncontrolled modifications to the underlying map.

This is mostly why I request that people upgrade to the latest stable and re-test before opening a ticket. 😉

**Comment by lhazlewood** [comment]
P.S.  Sorry, didn't see your comment about 0.11.2.  I don't see how that's possible given the copy-constructor approach.  Maybe you still had the 0.9.x jars in your project config or classpath?  Would it be possible to create a mini test project to verify?

**Comment by lhazlewood** [comment]
I just did a local test in my project (with the latest 0.11.x JJWT version) with this slightly modified test (same as yours, just creates the immutable map slightly differently):

```java
final Map<String, Object> claims = java.util.Collections.unmodifiableMap(Maps.of('my-claim', 'my-map').build());
final String subject = "admin";
String jws = Jwts.builder()
            .setSubject(subject)
            .setClaims(claims)
            .setIssuedAt(new Date(System.currentTimeMillis()))
            .setExpiration(new Date(System.currentTimeMillis() + 30000L))
            .signWith(SignatureAlgorithm.HS512, Keys.secretKeyFor(SignatureAlgorithm.HS512))
            .compact();
```

No errors - it produces the JWS just fine.

I *suspect* this might be a project configuration issue?  Not sure - but if you could throw together a tiny sample project to show us, that would help.  Because based on the above, I can't reproduce the problem.

**Comment by ffroliva** [comment]
Hi Les,

You are correct. version 0.10.0 fixed the issue. The `pulAll` method fixed
it. My mistake to mention version 0.11.2. You can close this issue.

Regards,

Flávio Oliva

Em seg., 15 de mar. de 2021 às 18:26, Les Hazlewood <
***@***.***> escreveu:

**Comment by lhazlewood** [comment]
Thanks @ffroliva !  Cheers 😄
