### ISSUE TITLE
How set my public key 

### ISSUE THREAD

**Issue by YesidMarin** [jwtk/jjwt#657]
Hi! Can you please provide an example of how to sign/verify using an existing public key pair with this structure?

![image](https://user-images.githubusercontent.com/29234631/113935933-bfa77280-97bc-11eb-9d09-ca7c086732dc.png)

**Comment by bdemers** [comment]
I'm guessing @YesidMarin has already found an answer, but before this get's closed I figured I'd post a link to a simplistic JWKS key resolver: https://github.com/okta/okta-jwt-verifier-java/blob/okta-jwt-verifier-parent-0.5.1/impl/src/main/java/com/okta/jwt/impl/jjwt/RemoteJwkSigningKeyResolver.java

NOTE: v1.0 of JJWT should have support for this directly (as it is required for JWEs)
