### ISSUE TITLE
Project has no GitHub Security Policy

### ISSUE THREAD

**Issue by Marcono1234** [jwtk/jjwt#670]
The project has currently no [GitHub Security Policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository). Users therefore don't know where to report vulnerablities, in case they discover one.

**Comment by Marcono1234** [comment]
Not stale!

**Comment by Marcono1234** [comment]
@bdemers, could you please have a look?

And maybe also disable stale bot for this repository, or let it consider only issues with a special label, e.g. 'awaiting-response' (if that is possible). In its current form it closes legit issues where the maintainers have not commented yet.

**Comment by bdemers** [comment]
Agreed!

**Comment by lhazlewood** [comment]
I personally like the stalebot as it helps reiterate which ones still need attention from time to time - very useful IMO.  That said, we can remove the label from this issue

**Comment by Marcono1234** [comment]
> as it helps reiterate which ones still need attention from time to time - very useful IMO

It probably depends on the perspective. As maintainer it might be useful, but for contributors or reporters of issues this can be extremely frustrating. At some point they might just give up after repeatedly commenting, even if the reported issue still exists, or a requested feature has multiple upvotes.

However, its usage can be reasonable when maintainers await the response from a reporter.

**Comment by lhazlewood** [comment]
@Marcono1234 fair point.  I often rely on it for in the context of "hey! I've been here longer than you probably wanted! Don't forget about me!"

I'm fine removing stalebot, but I won't be aware of these things as often, probably exacerbating the delay.  I'm certainly happy to remove it if others prefer.

**Comment by lhazlewood** [comment]
Back to the topic at hand, I just added a Security Policy via https://github.com/jwtk/jjwt/commit/d91881fbacd303328da485c0b7e3217e9454c576

Please feel free to open another issue or PR to suggest changes/additions to that.  Thanks!

**Comment by Marcono1234** [comment]
Thanks a lot for addressing this issue, the new Security Policy looks great!

And sorry if my comment regarding the Stale bot sounded a bit demanding; if the bot helps you to better manage this repository, then it is completely reasonable to use it.
