### ISSUE TITLE
The signing key's algorithm 'SHA256withECDSA' does not equal a valid HmacSHA* algorithm name and cannot be used with HS512.

### ISSUE THREAD

**Issue by jiangxiaoqiang** [jwtk/jjwt#674]
I am not sure it is a bug:

https://stackoverflow.com/questions/68375397/the-signing-keys-algorithm-sha256withecdsa-does-not-equal-a-valid-hmacsha-al?noredirect=1#comment120841873_68375397

**Comment by jiangxiaoqiang** [comment]
any more infomation I am glade to provide.

**Comment by bdemers** [comment]
Looks like this is resolved now on StackOverflow 😄 
Let us know if you still have questions!
