### ISSUE TITLE
String Object in payload wrapping the variable name along with the value

### ISSUE THREAD

**Issue by pradeepovid** [jwtk/jjwt#675]
![JWT-StringLiteral](https://user-images.githubusercontent.com/87616228/126077702-2f1b0cae-f160-43b8-b1ff-d162792ed523.PNG)
![JWT-STringObject](https://user-images.githubusercontent.com/87616228/126077709-bd9e0c95-a8a7-434b-a0cb-08afad845b05.PNG)
Trying to create a Json Web Token using this library. It is working fine if i pass a string literal/ string value directly.

But when i pass it via a String object variable it is wrapping the variable name in the claim. How to avoid the variable name in the payload/claim.

I have attached the screenshots of the decoded token for your reference.

**Comment by lhazlewood** [comment]
What does the Java code look like that results in those two outputs? Can you please paste those two snippets?

Also, please ask questions according to https://github.com/jwtk/jjwt#help-questions in the future.  We use GitHub issues for actionable work to be completed on the codebase itself.  Thanks!

**Comment by pradeepovid** [comment]
Hi Team,

*Below is the working piece of code with hardcoded string value.*

*String userId = "pradeep";*

String secret = System.getProperty("STREAM_SECRET");
System.out.println(secret);
   SignatureAlgorithm signatureAlgorithm = SignatureAlgorithm.HS256;

   long nowMillis = System.currentTimeMillis();
   Date now = new Date(nowMillis);

   //We will sign our JWT with our ApiKey secret
   byte[] apiKeySecretBytes = DatatypeConverter.parseBase64Binary(secret);
   Key signingKey = new SecretKeySpec(apiKeySecretBytes,
signatureAlgorithm.getJcaName());

   //Let's set the JWT Claims
   JwtBuilder builder = Jwts.builder()
    .setId(userId)
    .claim("user_id",userId)
//     .claim("id",chatAppUserId)
           .setIssuedAt(now)
           .signWith(signingKey, signatureAlgorithm);

   return builder.compact();

----------------------------------------------------------------------------------------------------------------------

*Below is the Not working piece of code with the value coming from a String
Object parameter of the method.*

public String getUserToken(String chatAppUserId) {

* String userId = chatAppUserId;*

String secret = System.getProperty("STREAM_SECRET");
System.out.println(secret);
   SignatureAlgorithm signatureAlgorithm = SignatureAlgorithm.HS256;

   long nowMillis = System.currentTimeMillis();
   Date now = new Date(nowMillis);

   //We will sign our JWT with our ApiKey secret
   byte[] apiKeySecretBytes = DatatypeConverter.parseBase64Binary(secret);
   Key signingKey = new SecretKeySpec(apiKeySecretBytes,
signatureAlgorithm.getJcaName());

   //Let's set the JWT Claims
   JwtBuilder builder = Jwts.builder()
    .setId(userId)
    .claim("user_id",userId)
//     .claim("id",chatAppUserId)
           .setIssuedAt(now)
           .signWith(signingKey, signatureAlgorithm);

   return builder.compact();

}

Thanks & Regards,
Pradeep

**Comment by lhazlewood** [comment]
JJWT doesn't manipulate or 'wrap' any String value you use as a claim, and it doesn't add carriage-return/newlines in claim values.

I suspect whatever value you used for `chatAppUserId` was not actually a raw id value, but a JSON String from some other object that was previously marshalled.

Modify your method to print the value of `chatAppUserId` before you use it with JJWT:

```java
public String getUserToken(String chatAppUserId) {

    // What is the output of this in the console?
    System.out.println("The chatAppUserId value: " + chatAppUserId);

    String userId = chatAppUserId;

    // ... etc ...
}
```

**Comment by pradeepovid** [comment]
Hi,

 We solved it. As you rightly said the issue was in the Rest API which was
accepting the incoming values. Now everything is fine.

Thanks,
Pradeep
