### ISSUE TITLE
Jwts.builder() - setClaims - overwrite others propertyes

### ISSUE THREAD

**Issue by schotten** [jwtk/jjwt#678]
If the form do you make the Jwts.builder(), the setClaims overwrite the Subject in the wrong form.
I will sent do exemple:

**Firstly i create the claims and after i will create the JWT token string**

> public String generateProfileToken() {
>         Map<String, Object> claims = new HashMap<>();
>         claims.put("aut", "anything");
>         claims.put("company",  "anything");
>         claims.put("department",  "anything");
>         return generateIdentificationToken(claims, "my login");
>     }

**The create JWT token to form that the Subject is acessyble in future**

> private String generateIdentificationToken(Map<String, Object> claims, String username) {
>         return Jwts.builder()
>                 .setClaims(claims)
>                 .setSubject(username)
>                 .setIssuedAt(new Date(System.currentTimeMillis()))
>                 .setExpiration(new Date(System.currentTimeMillis() + TOKEN_EXPIRED))
>                 .signWith(SignatureAlgorithm.HS256, secret)
>                 .compact();
>     }

**The read JWT token and get the login**

> public String getUserByToken(String jwtToken){
>         return Jwts.parser()
>                 .setSigningKey(secret)
>                 .parseClaimsJws(jwtToken)
>                 .getBody()
>                 .getSubject();
>     }

**The error:**
If i change the order for builder in function generateIdentificationToken, the subject not can accesible in function getUserByToken.
The incorret form: (I seted the subject before the claims). In this case, the subject not acessible in the future.
> private String generateIdentificationToken(Map<String, Object> claims, String username) {
>         return Jwts.builder()
>                 .setSubject(username)
>                 .setClaims(claims)
>                 .setIssuedAt(new Date(System.currentTimeMillis()))
>                 .setExpiration(new Date(System.currentTimeMillis() + TOKEN_EXPIRED))
>                 .signWith(SignatureAlgorithm.HS256, secret)
>                 .compact();
>     }

for using a builder, is it a bug in my opinion. The builder is expansive and shouldn't overwrite others parameters the token wuen the setClaims is executed.

I record the problem and attachment the video in below link:

https://user-images.githubusercontent.com/57331623/129746155-009f48ee-8ae8-4408-bb7c-d9ed268f5ee7.mp4

**Comment by bdemers** [comment]
Hi @schotten!

The setters follow a typical Java bean pattern, the `setClaims()` method _should_ overwrite any previously added claims. I'm guessing you probably want to use the `addClaims()` method instead:

https://github.com/jwtk/jjwt/blob/6fe3759d641a5e89ea9a824fa9213b02b5e51483/api/src/main/java/io/jsonwebtoken/JwtBuilder.java#L98-L120

You may also want to look at the `setClaims(Claims)` method as well:
https://github.com/jwtk/jjwt/blob/6fe3759d641a5e89ea9a824fa9213b02b5e51483/api/src/main/java/io/jsonwebtoken/JwtBuilder.java#L87-L96

You could create a `Claims` object by calling `Jwts.claims()`, and then call the typed methods such as `setSubject()`

Does that help?

**Comment by lhazlewood** [comment]
Just noting:

It is JavaBeans idiomatic behavior to _replace_ state when calling a `set` method.  If you call `setClaims`, the expectation is that you are fully replacing the existing Claims object and/or all state associated with the existing Claims object.  `addClaims` was added to support appending state (as opposed to idiomatic full replacement).

See also #66 and #179.

As a result, and based on these two previous issue, I believe it is appropriate to close this issue.  That said, feel free to comment and/or suggest re-opening if you believe this to be in error.  Thanks!
