### ISSUE TITLE
Android 6 RSAPrivateKey

### ISSUE THREAD

**Issue by KalinKanev** [jwtk/jjwt#68]
Hello,

I understand that this may not be issue with the library but may is worth extending. Some changes were made by google in API 23 so the code below that worked on lower version is no longer valid.

    PrivateKey privateKey = KeyChain.getPrivateKey(context, "Alias");
    String jwtString = Jwts.builder().setHeaderParams(map)
                .setPayload(payload)
                .signWith(SignatureAlgorithm.RS256, privateKey)
                .compact();

Before API 23 KeyChain.getPrivateKey had a return type of OpenSSLRSAPrivateKey and post 23 it is AndroidKeyStoreRSAPrivateKey which does not expose the bytes of the key.

Could the library be enhanced to use the new Android way of signing as described in this post: 
https://code.google.com/p/android-developer-preview/issues/detail?id=2854

Thanks in advance,
Kalin

**Comment by lhazlewood** [comment]
This is actually an easy fix I think.  Instead of asserting:

```java
(key instanceof RSAPrivateKey)
```

we can just assert:

```java
(key instanceof PrivateKey && key instanceof RSAKey)
```

This would assert the correct expectations and would work both on the standard JDK because the JDK's `RSAPrivateKey` interface extends both `PrivateKey` and `RSAKey`, and so does Android's RSA private key implementation.

**Comment by lhazlewood** [comment]
This has been implemented and merged to master.  It will be in the next release.

**Comment by KalinKanev** [comment]
Working like a charm. Thanks for fast reaction!
