### ISSUE TITLE
JJwt Initialization is too Slow. Severer When it in a Concurrent System

### ISSUE THREAD

**Issue by city2011** [jwtk/jjwt#692]
**Describe the bug**
jjwt builder initialization is too slow when it in a tomcatEmbedded class context.
It may cost 500ms ~ 3500ms to loadFirst

**To Reproduce**
1. Build a simple tomcat nio application.
2. Write a code to request a remote api using jjwt signature.
3. Call the api which using jjwt signatrue with a certain number of QPS.
4. Using some tools like arthas from alibaba to trace timecost.
5. You will see that loadFirst function is slow cause of ServiceLoader logic.

**Expected behavior**
Solve the too slow problem when jjwt builder initialization first.
It is better that jwt generate cost less than 10ms.

**Screenshots**
![jjwtLoadFirst](https://user-images.githubusercontent.com/6259816/142132748-d13e42bc-10c6-4276-a9fe-c420b963dd0e.jpg)

**Comment by city2011** [comment]
code implemention like this can solve ServiceLoader and iterate through Jars

`Date expiredTime = new Date(System.currentTimeMillis() + TTL);
        JwtBuilder builder = Jwts.builder()
                .setHeaderParam("typ", "JWT")
                .signWith(Keys.hmacShaKeyFor(SECRET.getBytes()))
                .setIssuer(ISS)
                .serializeToJsonWith(new JacksonSerializer<>());
        
        return builder
                .claim("yourClaim", "my personal claim")
                .setExpiration(expiredTime)
                .compact();`

cause of jjwt compat will judge whether it need to use ServiceLoad as follow 

`@Override
    public String compact() {

        if (this.serializer == null) {
            // try to find one based on the services available
            // TODO: This util class will throw a UnavailableImplementationException here to retain behavior of previous version, remove in v1.0
            // use the previous commented out line instead
            this.serializer = LegacyServices.loadFirst(Serializer.class);
        }
...}
`

**Comment by bdemers** [comment]
I think there might be something environment-specific related to your tests.  I just created a simple (and ugly) perf test.

After the JVM warms up, I ran a similar code to yours 10,000 times with and without setting the `Serializer`. Granted these numbers are machine-specific, but they do NOT show the kind of issue you are seeing.

```txt
Average with Service Lookup: 130931ns (0.130931ms)
Average without Lookup:    138480nsns (0.13848ms)
```

NOTE: My test did NOT include Tomcat.

If you still think there is an issue on the JJWT side, please provide us with an example so we can reproduce the issue.

**Comment by city2011** [comment]
Thanks for reply！

I think this is not a issue in jjwt, but may trigger SPI a lot of times in some case. 
Using compact() in multi thread that belang to a same root thread - won't touch the logic using ServiceLoader(SPI)

jjwt is thread-context isolated, if i understand right. Every new thread-context using jjwt without Serializer, will run whole SPI to find a serializer. And I agree the point that SPI time cost is environment-specific.

I will try to reproduce the issue using a tomcat demo and test case after a time.

**Comment by bdemers** [comment]
Thanks @city2011!
I'll close the issue for now, but if you have a repo case feel free to comment and we can open the issue up again and re-evaluate the issue.
