### ISSUE TITLE
cannot find symbol method parserBuilder

### ISSUE THREAD

**Issue by realjax** [jwtk/jjwt#695]
This code:

```
import io.jsonwebtoken.JwtParser;
import io.jsonwebtoken.Jwts;
...

JwtParser parser = Jwts.parserBuilder().build();
```

gives me this error:

```
cannot find symbol
[error]   symbol:   method parserBuilder()
[error]   location: class io.jsonwebtoken.Jwts
[error]     parser = Jwts.parserBuilder().build();
```

I am running version 0.11.2. ( double checked)

What am I missing?

**Comment by bdemers** [comment]
Double check your classpath/dependencies and make sure you do t have the older 0.9 version as a dependency too. 

Please keep us posted!

**Comment by realjax** [comment]
I am using SBT and have the  following lib dependencies defined:

```
libraryDependencies += "io.jsonwebtoken" % "jjwt" % "0.9.1"
libraryDependencies += "io.jsonwebtoken" % "jjwt-api" % "0.11.2"
libraryDependencies += "io.jsonwebtoken" % "jjwt-impl" % "0.11.2" % "runtime"
libraryDependencies += "io.jsonwebtoken" % "jjwt-jackson" % "0.11.2" % "runtime"
```

However, something somewhere there is a dep to  https://repo1.maven.org/maven2/io/jsonwebtoken/jjwt/0.7.0/jjwt-0.7.0.jar
because it keeps reolving that as well. Could that be the cause?

**Comment by bdemers** [comment]
@realjax yup!  Remove that first line, and you should be good to go.

NOTE: we have a PR to help smooth out this transition in the future.

**Comment by realjax** [comment]
Actually, I put that first line in to see if it would a difference.  Which it didnt. Next to version 0.9 it still donwloaded version 0.70 from some reason. So it obviously was not that.

What DID fix it in the end was updating both SBT and the play framework. For reasons only the build gods know, it then no longer threw the error. ( Threw a shitload of new ones,  but hey! you win some, you lose some) :). 

Thanks.

**Comment by bdemers** [comment]
Were the new exceptions JJWT related?

**Comment by realjax** [comment]
Nope 😊

**Comment by kidneyflowerSE** [comment]
Claims claims = Jwts.parserBuilder().setSigningKey(key).build().parseClaimsJws(jwt).getBody();
i am using Jwts version 0.12.6 and it has an error Cannot resolve method 'parserBuilder' in 'Jwts'

**Comment by lhazlewood** [comment]
@kidneyflowerSE 

https://github.com/jwtk/jjwt/blob/2ad964a3f1d77ffa1a915640d94e9238216a52d6/CHANGELOG.md?plain=1#L347-L349

and 

https://github.com/jwtk/jjwt?tab=readme-ov-file#reading-a-jwt step `#1`

I hope that helps!

**Comment by Hikmettpk** [comment]
@lhazlewood Thanks, dude. It is beneficial
