### ISSUE TITLE
JWT method signWith(java.security.Key, io.jsonwebtoken.SignatureAlgorithm) is not found at runtime despite including all dependencies

### ISSUE THREAD

**Issue by coderman2022** [jwtk/jjwt#701]
**Describe the bug**
A library that uses JWT reports the following error at runtime (not during compile), even though all JWT dependencies are included:

`java.lang.AbstractMethodError: Receiver class io.jsonwebtoken.impl.DefaultJwtBuilder does not define or inherit an implementation of the resolved method 'abstract io.jsonwebtoken.JwtBuilder signWith(java.security.Key, io.jsonwebtoken.SignatureAlgorithm)' of interface io.jsonwebtoken.JwtBuilder`

**To Reproduce**
include these dependencies in sbt:
```
      "io.jsonwebtoken" % "jjwt-api" % "0.11.2",
      "io.jsonwebtoken" % "jjwt-impl" % "0.11.2" % "runtime",
      "io.jsonwebtoken" % "jjwt-jackson" % "0.11.2" % "runtime",
```
This occurs when using the library "io.getstream" % "stream-chat-java", which uses JWT.

If I include the additional line in sbt (this dependency was not included above):

`"io.jsonwebtoken" % "jjwt" % "0.9.1"`

Then I get a different error:

`java.lang.NoSuchMethodError: 'io.jsonwebtoken.JwtBuilder io.jsonwebtoken.JwtBuilder.signWith(java.security.Key, io.jsonwebtoken.SignatureAlgorithm)'
	at io.getstream.chat.java.services.framework.DefaultClient.jwtToken(DefaultClient.java:153)
	at io.getstream.chat.java.services.framework.DefaultClient.lambda$new$0(DefaultClient.java:98)`

**Expected behavior**
Program should run successfully when calling JWT methods.

**Comment by bdemers** [comment]
You will need to exclude the 0.9.1 version of JJWT from your build.

#629 will actually have the benefit of working around this type of problem too.

**Comment by coderman2022** [comment]
> You will need to exclude the 0.9.1 version of JJWT from your build.
> 
> #629 will actually have the benefit of working around this type of problem too.

Thanks. Do you happen to know the recommended way to do this in SBT?

**Comment by bdemers** [comment]
I haven't used sbt much, but it looks like there are a few options depending on which version you are using:

https://stackoverflow.com/questions/10958215/how-to-exclude-commons-logging-from-a-scala-sbt-slf4j-project

**Comment by coderman2022** [comment]
Those are not working for me unfortunately. When I do the sbt build, I still have `io.jsonwebtoken.jjwt-0.9.1.jar` in my output jar.

By the way, when you said exclude JJWT from the build, did you mean only `io.jsonwebtoken.jjwt-0.9.1.jar`? Or also `io.jsonwebtoken.jjwt-api-0.11.2.jar, io.jsonwebtoken.jjwt-jackson-0.11.2.jar, io.jsonwebtoken.jjwt-impl-0.11.2.jar`? I tried removing the manually from the build output after sbt, and even then I still get JWT runtime errors.

**Comment by bdemers** [comment]
You would need to remove only the old version `"io.jsonwebtoken" % "jjwt"` which sounds like it's a transitive dependency of  `stream-chat-java`

I'm guessing your sbt config would need to be updated to look something like:

```scala
libraryDependencies += "io.getstream" % "stream-chat-java" % "<version>" exclude("io.jsonwebtoken", "jjwt")
```

That said, it looks like the current version of `stream-chat-java` uses the latest version of JJWT, so it might just be easier to update `stream-chat-java`.

If that doesn't help, list the dependency tree of your project to figure out where the dependency is being added:
https://www.baeldung.com/scala/sbt-dependency-tree

**Comment by coderman2022** [comment]
The library I'm using is `io.getstream.client:stream-java:3.2.4` https://mvnrepository.com/artifact/io.getstream.client/stream-java/3.2.4

`io.getstream.client:stream-java:3.2.4` depends on a specific JWT implementation called `com.auth0:java-jwt`, this is according to the MVN repository link above, where it is listed as a Runtime Dependency. When `io.getstream.client:stream-java:3.2.4` makes its JWT call during runtime, it is probably expecting the `com.auth0:java-jwt` runtime function to be present, but instead it can only find the `io.jsonwebtoken:jjwt:0.9.1` runtime implementation of JWT, which as you said is also older than the current version. My program jar binary contains both `com.auth0:java-jwt` as well as `io.jsonwebtoken:jjwt:0.9.1`. Like you said, it sounds like the solution is to remove `io.jsonwebtoken:jjwt:0.9.1` from the build, so that only the JWT runtime that the library is expecting remains. I haven't been able to figure out how to tell `sbt` to remove that dependency though, despite trying all of the exclusion methods that sbt supports -- `io.jsonwebtoken:jjwt:0.9.1` is always in the output jar. My program is actually a `Java Play Framework` server, and it depends on and pulls in `io.jsonwebtoken:jjwt:0.9.1` transitively from many other core dependencies, so I'm not sure it's actually possible to completely remove `io.jsonwebtoken:jjwt:0.9.1` from the build. I even tried to sneakily delete the `io.jsonwebtoken.jjwt-0.9.1.jar` file from the final output jar (since jar is just a zip file). But that leads to a different, similar error. It seems to me the fix would be to let both `io.jsonwebtoken:jjwt:0.9.1` and `com.auth0:java-jwt` coexist in the output jar, but somehow tell `io.getstream.client:stream-java:3.2.4` to specifically call the `com.auth0:java-jwt` implementation.

Even more confusingly, the io.getstream documentation recommends **adding** the `io.jsonwebtoken:jjwt:0.9.1` dependency, not removing it, even though the io.getstream library depends on `com.auth0:java-jwt`, not `io.jsonwebtoken:jjwt:0.9.1`. See here: https://github.com/GetStream/stream-chat-java/issues/16

**Comment by bdemers** [comment]
What does your dependency tree look like?

**Comment by coderman2022** [comment]
[tree.txt](https://github.com/jwtk/jjwt/files/7831143/tree.txt)

**Comment by bdemers** [comment]
Looks like the dependency is coming in from a transitive dependency of: `com.typesafe.play:filters-helpers_2.12:2.8.11`

but I don't see that dependency in your list above?

**Comment by coderman2022** [comment]
Problem solved! You're right, it was Play's own plugin that brought in `com.typesafe.play:filters-helpers_2.12:2.8.11`, which then in turn brought in the JWT dependency in question. Play's own dependencies are not listed explicitly in `build.sbt` (they're brought in via the `.enablePlugins(PlayJava)` call I believe), and my mistake was that I was only excluding the JWT dependency from my own explicitly listed dependencies, rather than from Play's. `excludeDependencies += "io.jsonwebtoken" % "jjwt"` does work after all, as long as I put it at the highest level of `build.sbt`. Thanks for your assistance, that was incredibly helpful!

**Comment by coderman2022** [comment]
@bdemers What would happen if some dependency in my final build jar needed the `io.jsonwebtoken` implementation of JWT, and another dependency in my build jar needed the `com.auth0` implementation of JWT? Then I couldn't just exclude one of the JWT implementations from the jar. Is there a solution for such a scenario?

**Comment by bdemers** [comment]
The `com.auth0` project and `jjwt` are unrelated, having both your classpath should not cause any problems
