### ISSUE TITLE
setClaims and set other property order fault

### ISSUE THREAD

**Issue by Joebig7** [jwtk/jjwt#702]
hello,i use jjwt to generate token like this:
```java
 Jwts.builder()
                .setSubject((userPrincipal.getUsername()))
                .setIssuedAt(new Date())
                .setClaims(clams)
                .setExpiration(new Date((new Date()).getTime() + jwtExpirationMs))
                .signWith(SignatureAlgorithm.HS256, jwtSecret)
                .compact();
```

 
But in this order,  IssuedAt and Subject will be overrided by setClaims(clams),because this method will create a new clams,so i have to do like this :

```java
Jwts.builder()
                .setClaims(clams)
                .setSubject((userPrincipal.getUsername()))
                .setIssuedAt(new Date())
                .setExpiration(new Date((new Date()).getTime() + jwtExpirationMs))
                .signWith(SignatureAlgorithm.HS256, jwtSecret)
                .compact();
```
 

I think this place needs to be improved to prevent this from happening，Please confirm if this is true thanks a lot!

**Comment by bdemers** [comment]
@Joebig7 This is expected behavior for beans using a "setter".  Take a look at the `JwtBuilder.addClaims()` method, as that probably does what you are looking for

**Comment by lhazlewood** [comment]
Just a note - all `setter`s adhere to the JavaBeans convention of total value replacement.  As @bdemers noted, `addClaims` as added for the scenario where you don't want to adhere to the JavaBeans convention.  I hope that helps!

**Comment by Joebig7** [comment]
yes,addClaims can resovle this problem,thanks a lot
