### ISSUE TITLE
Misnomer/misconfiguration: hotspot and zulu CI

### ISSUE THREAD

**Issue by bmarwell** [jwtk/jjwt#723]
**Describe the bug**

The CI job "hostspot" uses temurin and the CI job "zulu" uses zulu.
But zulu is in fact just another hotspot JVM.

**To Reproduce**

open `ci.yml`.

**Expected behavior**

Either 
* rename `hotspot` jobs to `temurin` or
* replace `zulu` with `semeru` which is in fact the only non-hotspot-JVM as it uses OpenJ9 instead of hotspot.
… or both.

I recommend doing both.

**Comment by lhazlewood** [comment]
Resolved with merge of 451c8d44dd76d71bc2a6d402a703fa901d4af1d5
