### ISSUE TITLE
java: package io.jsonwebtoken does not exist

### ISSUE THREAD

**Issue by aca1234** [jwtk/jjwt#745]
![Untitled](https://user-images.githubusercontent.com/107209532/172908902-f38ba943-c353-4fc7-89b6-edaded341d50.png)
i have a problem can anyone help me
java: package io.jsonwebtoken does not exist

**Comment by bdemers** [comment]
This is likely an issue with your IDE settings, see:
https://stackoverflow.com/questions/9980869/force-intellij-idea-to-reread-all-maven-dependencies

I usually suggest folks try to build on the command line when you see these types of problems, as it helps narrow down the source of the issue.

Try running `mvnw package` from your project, to see if that works.
