### ISSUE TITLE
Getting SignatureException when verifying token that was created by another library

### ISSUE THREAD

**Issue by michaelHicks** [jwtk/jjwt#75]
Hi, 
I'm having a hard time decoding token created with node-jsonwebtoken (also tried tokens created in jose.4.j - didn't work as well).
Weird thing is that I can verify this token using other libraries without any problems.

I'm getting this error:
io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.

``` java
    	String text = "rfr: { user: {} }";
    	String key = "kfDYJ8t/z/EQ6pcK";
    	String token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJyZnIiOnsidXNlciI6e319LCJpYXQiOjE0NTA0NDg2MTYsImV4cCI6MTQ1MDg4MDYxNn0.X1TTm5NwnxFSaG4sx0zHvl-9MBRyn3oiKB1FsT9GMCu3lslWTgCdX-2X0jEwkiqWloyZjoEkCKIPsqA45R8IdA";
    	
    	// Encoding
    	String testToken = Jwts.builder().setPayload(text).signWith(SignatureAlgorithm.HS512, key).compact();
    	System.out.printf("Generated token is: %s%n", testToken);
    	// Decoding the token
    	String output = Jwts.parser().setSigningKey(key).parse(testToken).getBody().toString();
    	System.out.printf("Decoded payload is: %s%n%n%n", output);
    	
    	
    	// Decoding token created with node-jsonwebtoken (also tried tokens created in jose.4.j - didn't work as well)
    	String result = Jwts.parser().setSigningKey(key).parse(token).toString();
    	System.out.printf("Decoded result is: %s%n", result);
```
Am I doing something wrong?

**Comment by lhazlewood** [comment]
@michaelHicks if you are parsing a known signed string payload JWT, you shouldn't use `parse`, you should use the `parsePlaintextJws` method.

Also, are you certain your String key above is a Base64-encoded key and that key is of a valid length for HMAC-SHA-512? (If you do `TextCodec.BASE64.encode(MacProvider.generateKey().getEncoded())` - how many characters are printed?  Is it the mostly the same length as your test key above?).

Also note that calling `toString()` on a JWS<String> does *not* print out the String - it prints out any headers, body, and signature.

Your last line shows `parse(token).toString()` but your other examples above do `.parse(testToken).getBody().toString()`.  Might this discrepancy the the source of the problem?

If these questions don't shed any light - would you be able to provide a tiny Maven or Gradle project that demonstrates the behavior when tested w/ the other JWT libraries?  I'm happy to help debug if you can provide this starting point!

**Comment by michaelHicks** [comment]
Hi Les, thank you for your help. As you mentioned above, the issue was with not a valid length key for HS-512.
