### ISSUE TITLE
Add a copy() method to JwtBuilder

### ISSUE THREAD

**Issue by andrewlalis** [jwtk/jjwt#753]
**Is your feature request related to a problem? Please describe.**
I use a `JwtBuilder` to build JWT tokens (obviously), and most of the claims and settings of the builder are the same for each new token I make, with a few notable claims that must change each time. It's not feasible to simply use a common builder instance across my application, since it's a multi-threaded web app, and so I think it would be useful to have a method to create a copy of a builder from another, so that a base builder can serve as a reusable, pre-configured template.

**Describe the solution you'd like**
I would like to add the following method to `JwtBuilder`
```java
JwtBuilder copy();
```
*and of course, an implementation for `DefaultJwtBuilder`*

**Describe alternatives you've considered**
The obvious alternative is to create a factory for creating JwtBuilder instances, but this feels obtuse for what could be a simple method.

**Comment by bdemers** [comment]
@andrewlalis i'm not sure fully understand the suggestion, is this something you could do in your application with a helper method?

```java
public String createJwt(String subject) {
  return Jwts.builder()
      .setSubject(subject)
      .setExpiration(new Date())
      .signWith(this.key)
      .compact();
}
```

This could return the builder instead of a string too.

If you are trying to inject the `JwtBuilder` you could probably do something like:

```java
@Bean
@RequestScope
JwtBuilder jwtBuilder() {
  return Jwts.builder()
      .setExpiration(new Date())
      .signWith(this.key);
}
```

**Comment by andrewlalis** [comment]
Yes, I suppose a request-scoped bean would be appropriate for my use case. Although it would be nice to have a facility similar to what the JDK does for some of its own builders, like [`HttpRequest.Builder#copy`](https://docs.oracle.com/en/java/javase/17/docs/api/java.net.http/java/net/http/HttpRequest.Builder.html#copy())
