### ISSUE TITLE
jwt token failed validation in token.dev

### ISSUE THREAD

**Issue by xarick** [jwtk/jjwt#755]
Hello, I have a problem. This jwt token failed validation when checked in token.dev.

I want to check in php with a token created in java, I have the same keys but they don't match. That is, I want to work on two different projects with one token.

Please help me!

**Comment by xarick** [comment]
![image](https://user-images.githubusercontent.com/29143806/194537277-d40739d3-ee32-4ee5-8cfc-1700c18115ba.png)
![image](https://user-images.githubusercontent.com/29143806/194537345-1fdf5abd-0df2-49fa-85c5-35910667296f.png)

**Comment by bdemers** [comment]
Thanks for reaching out @xarick. 
I'm not sure I'm following the question though, Token.dev is not managed by the JJWT team.

I personally have worked on JJWT, but you can use the `email` link to contact us for that.

That said, if you are using JJWT to create the JWT. Can you include the error that you see on the PHP side, and maybe we can point you in the right direction?

**Comment by lhazlewood** [comment]
FWIW, that 'signing key' doesn't look to be a valid HS256 signing key.  If you use a base64-encoded key, please enable the 'Base64 encoded' toggle.

That said, I'm closing this issue as we use GitHub Issues for actionable work for the JJWT codebase itself.  If you have a question, please ask it here:

https://stackoverflow.com/questions/ask?tags=jjwt&guided=false

**Comment by xarick** [comment]
I am not using it because the key is not base64.
I created a question here: 
https://stackoverflow.com/questions/74010523/java-jjwt-failed-in-token-dev
