### ISSUE TITLE
Implement better documentation

### ISSUE THREAD

**Issue by mirai-toto** [jwtk/jjwt#757]
Not a good documentation, sadly.

Most of the example that can be find in the issues are deprecated.

**Comment by bdemers** [comment]
@mirai-toto we appreciate you reaching out to us, but the term “documentation” is a bit vague. Can you be more specific, as to the the problem you are seeing?

StackOverflow has a great article on how to ask good questions, it’s useful for devs of all levels: 
https://stackoverflow.com/help/how-to-ask

**Comment by mirai-toto** [comment]
I confess, I have been a little frustrated.

I was trying to verify a JWT token with a RSA public key that I have stored as a file, after a few hours digging around the issue searching for my use case, I was a bit salty.
My solution for this problem was switching to java-jwt. But this is a great project, without a doubt.

Maybe more examples on how to verify a JWT token would help newbies like me.
Have a nice day.

**Comment by bdemers** [comment]
Keys can be stored on disk in multiple formats, and that’s outside the scope of JJWT. 
That said, I don’t think having an example is a bad idea. 
What format was your key stored in?

**Comment by mirai-toto** [comment]
From what I understand, it's JWKS, I have a keycloak that I use for authentication. But I can also use pem, if needed.

**Comment by bdemers** [comment]
The next version of JJWT will support JWKS, but PEM can be read by another library (I'd suggest bouncy castle).

Are you validating ID Tokens?
