### ISSUE TITLE
JWS

### ISSUE THREAD

**Issue by ddt-tdd** [jwtk/jjwt#76]
Hi,

I had a quick look to your JWT implementation, but didn't try it (yet).
Is there a way to only use the JWS part to sign JSON data?

Greetings,
ddt

**Comment by lhazlewood** [comment]
I'm a bit confused by the request.  JWS is a specification to sign JSON data.  And JJWT fully supports JWS.  So without any further information, the answer is absolutely, it does :)

**Comment by ddt-tdd** [comment]
It's not a request, but a question. I'll have to look further and deeper then ;-).

Thanks
