### ISSUE TITLE
Unable to find an implementation for interface io.jsonwebtoken.io.Serializer ... in fat jar

### ISSUE THREAD

**Issue by bnegrao** [jwtk/jjwt#772]
I am opening this issue to report that issue https://github.com/jwtk/jjwt/issues/573 still happens in version 0.11.5, and to solve the issue i had to add the `io.jsonwebtoken:jjwt-jackson:0.11.5` dependency.

The README file in the section [Gradle](https://github.com/jwtk/jjwt#gradle) says that `io.jsonwebtoken:jjwt-jackson:0.11.5` is only needed *if you want to use RSASSA-PSS* but that is not true. Please update the README and add this dependency as always needed.

**Comment by lhazlewood** [comment]
> says that `io.jsonwebtoken:jjwt-jackson:0.11.5` is only needed _if you want to use RSASSA-PSS_ but that is not true. 

That is not what it says. 😉 

This is the code block:

```gradle
dependencies {
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5',
    // Uncomment the next line if you want to use RSASSA-PSS (PS256, PS384, PS512) algorithms:
    //'org.bouncycastle:bcprov-jdk15on:1.70',
    'io.jsonwebtoken:jjwt-jackson:0.11.5' // or 'io.jsonwebtoken:jjwt-gson:0.11.5' for gson
}
```

The relevant lines are:

```gradle
// Uncomment the next line if you want to use RSASSA-PSS (PS256, PS384, PS512) algorithms:
//'org.bouncycastle:bcprov-jdk15on:1.70',
```

`Uncomment the next line` means 1) you have to uncomment something and 2) it is the next line.  The next line is:

```gradle
//'org.bouncycastle:bcprov-jdk15on:1.70',
```

As you can see, this is commented out with double slashes (`//`), so you have to uncomment (remove the double slashes) if you want to use `RSSA-PSS` before JDK 11.  JDK 11 and later has those algorithms natively.

**Comment by lhazlewood** [comment]
Out of curiosity, given that this might be confusing, how can we improve it so it is more clear?  Maybe something like this?

```gradle
dependencies {
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5',
    //'org.bouncycastle:bcprov-jdk15on:1.70', // Uncomment to use RSASSA-PSS (PS256, PS384, etc) algorithms
    'io.jsonwebtoken:jjwt-jackson:0.11.5' // or 'io.jsonwebtoken:jjwt-gson:0.11.5' for gson
}
```

?

Or perhaps don't use comma-delimited dependencies and have a slightly more verbose declaration so that individual lines are more explicit?  Perhaps like this?

```gradle
dependencies {
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5' // or 'io.jsonwebtoken:jjwt-gson:0.11.5' for gson
    // Uncomment this next line if you want to use RSASSA-PSS (PS256, PS384, etc) algorithms <= JDK 10
    //runtimeOnly 'org.bouncycastle:bcprov-jdk15on:1.70' // not needed on JDK 11 or later
}
```

Thoughts?

**Comment by lhazlewood** [comment]
The latest README has been updated to more clearly indicate the optional dependency, it is now at the end of each example section and clearly documented on how to enable it
