### ISSUE TITLE
Misleading exception message for missing serializer .jar

### ISSUE THREAD

**Issue by lhazlewood** [jwtk/jjwt#773]
As commented by @darioseidl in https://github.com/jwtk/jjwt/issues/573#issuecomment-898606647:

> with 0.11.2 I'm also seeing this error unless I include the Jackson or Gson jar and the error message is misleading as it says that the `jjwt-impl.jar` is missing, but it's actually the `jjwt-jackson.jar` that was missing in my case:
> 
> ```
>     implementation("io.jsonwebtoken:jjwt-api:0.11.2")
>     runtimeOnly("io.jsonwebtoken:jjwt-impl:0.11.2")
> ```
> 
> results in:
> 
> `Unable to find an implementation for interface io.jsonwebtoken.io.Serializer using java.util.ServiceLoader. Ensure you include a backing implementation .jar in the classpath, for example, jjwt-impl.jar, or your own .jar for custom implementations`
> 
> but this works:
> 
> ```
>     implementation("io.jsonwebtoken:jjwt-api:0.11.2")
>     runtimeOnly("io.jsonwebtoken:jjwt-impl:0.11.2")
>     runtimeOnly("io.jsonwebtoken:jjwt-jackson:0.11.2")
> ```

The message "`for example, jjwt-impl.jar,`" should be changed to "`for example, jjwt-jackson.jar or jjwt-gson.jar`" since `jjwt-impl.jar` is always required and does not reflect a serializer implementation .jar as should be indicated.

**Comment by bdemers** [comment]
@brunogenovese can you grab your exact dependencies from `0.9.1` from your `pom.xml`?

**Comment by zOldBulldog** [comment]
Sorry to take this long to reply.  I was sick for over a week and it messed up my schedule.  Here is what I have in my old pom.  The new pom simply updated all of those versions to today's current.

As I mentioned, the new version broke things but adding the additional element(s) to the POM that @ihazlewood recommended did fix things.  

I hope it helps.

<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.release>17</maven.compiler.release>
    <commons.io.version>2.11.0</commons.io.version>
    <commons.lang.version>3.12.0</commons.lang.version>
    <commons.text.version>1.9</commons.text.version>
    <httpclient.version>4.5.13</httpclient.version>
    <jackson.version>2.12.5</jackson.version>
    <jaxb.version>2.3.1</jaxb.version>
    <jjwt.version>0.9.1</jjwt.version>
    <junit.version>4.11</junit.version>
    <log4j2.version>2.17.1</log4j2.version>
    <slf4j.version>1.7.36</slf4j.version>
    <servlet.version>4.0.1</servlet.version>
    <spring.version>5.3.15</spring.version>
    <spring-security.version>5.6.1</spring-security.version>
  </properties>

    
    <dependency>
      <groupId>io.jsonwebtoken</groupId>
      <artifactId>jjwt</artifactId>
      <version>0.9.1</version>
    </dependency>
    <dependency>
      <groupId>javax.xml.bind</groupId>
      <artifactId>jaxb-api</artifactId>
      <version>2.3.1</version>
    </dependency>

    
    <dependency>  
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.12.5</version>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpclient</artifactId>
      <version>4.5.13</version>
    </dependency>

**Comment by lhazlewood** [comment]
Your problem was occurring because a simple `<jjwt.version>` value change would not work when upgrading JJWT to 0.10.0 or later.  The dependency declarations changed, so it's not as simple as changing that value - you'd have to declare the correct dependencies.

This was covered in the change log here: https://github.com/jwtk/jjwt/blob/master/CHANGELOG.md#0100

and shown in the main documentation here: https://github.com/jwtk/jjwt#installation

That said, because this might have confused some people, we're reintroducing the `single jar` dependency declaration in a future release.  It is just an empty jar - all it does is ensure the correct dependency metadata so that Maven and Gradle. PR here: https://github.com/jwtk/jjwt/pull/629

**Comment by lhazlewood** [comment]
Also, for what it's worth, JJWT doesn't use JAXB in any way.  If you're not using it in your own application, you can remove the following:

```xml
<dependency>
  <groupId>javax.xml.bind</groupId>
  <artifactId>jaxb-api</artifactId>
  <version>2.3.1</version>
</dependency>
```

JJWT does not use this (but maybe something in your own application does).

**Comment by lhazlewood** [comment]
Closing as the JAXB APIs were only used prior to the 0.10.0 release - they have long since been removed.
