### ISSUE TITLE
Cannot use EllipticCurveSignatureValidator with Key bytes.

### ISSUE THREAD

**Issue by zemelett** [jwtk/jjwt#78]
In DefaultJwtParser.parse if a Key object is not provided but key bytes is not empty a SecretKeySpec object is created for the key:
```java
key = new SecretKeySpec(keyBytes, algorithm.getJcaName());
```
If however the algorithm is ES256, ES384 or ES512, the DefaultSignatureValidatorFactory will try to use an EllipticCurveSignatureValidator.  Which will check that the key is an instance of ECPublicKey, which it won't be because of the above.

**Comment by lhazlewood** [comment]
Resolved by #105
