### ISSUE TITLE
No signature key validation 

### ISSUE THREAD

**Issue by sidhuurs** [jwtk/jjwt#79]
I am using 0.4 release with jdk 1.6. Below is my test code. I am confused why I am able to parse with wrong key.  As shown below key used while generating jwt is "secret" . I was able to parse it with key "secr". I expect this to throw exception. Can someone help me understand why this worked?

long cur_secs = new Date().getTime();
    Date expdt = new Date(cur_secs+ 60*1000);
    Map<String, Object> claims = new HashMap<String, Object>();
    claims.put("api", "/api/public/test/category");
    // setting jwt
    String jwt = Jwts.builder().setIssuer("abcd").setIssuedAt(new Date()).
    setExpiration(expdt).setClaims(claims).signWith(SignatureAlgorithm.HS256, "secret").compact();
    System.out.println(jwt);
    // parsing jwt
    Jws<Claims> jwtCaims = Jwts.parser().setSigningKey("secr").parseClaimsJws(jwt);
    String api = (String) jwtCaims.getBody().get("api");
    System.out.println("api = "+ api);

**Comment by mikiebrenbren** [comment]
Yeah, this is definitely a bug that needs to be addressed. However I have found that if the secret is 8 characters or more then this is not happening.  The bug seems to be in the DefaultJwsParser class on line 339 where the JwtSignatureValidator class calls the isValid method.  If you dig a little more you see the MacValidator class uses the MessageDigest class to call the isEqual method and there seems to be a bug when the computed value compares the signature value.

**Comment by sidhuurs** [comment]
Thanks mikiebrenbren for your inputs.  Yes, I don't see any issue with secret having 8 or more characters. I read online that we should use BASE64 encoded secret keys. I tested with BASE64 encoded secret and its working as expected , even when the encoded secret has less than 8 chars.

        long cur_secs = new Date().getTime();
        Date expdt = new Date(cur_secs+ 60*1000);
	Map<String, Object> claims = new HashMap<String, Object>();
	System.out.println("BASE64 encoded key :"+TextCodec.BASE64.encode("sec"));
	String jwt = Jwts.builder().setIssuer("COMET").setIssuedAt(new Date()).
	setExpiration(expdt).claim("api","/api/public/comet/category").signWith(SignatureAlgorithm.HS256, TextCodec.BASE64.encode("sec")).compact();
	System.out.println(jwt);

	Jws<Claims> jwtCaims = Jwts.parser().setSigningKey(TextCodec.BASE64.encode("se")).parseClaimsJws(jwt);
	String issuer = (String)jwtCaims.getBody().getIssuer();
	Date Expdate = jwtCaims.getBody().getExpiration();
	String api = (String) jwtCaims.getBody().get("api");
	
    System.out.println("Issuer = "+ issuer);
    System.out.println("Expdate = "+ Expdate);
    System.out.println("api = "+ api);

**Comment by lhazlewood** [comment]
This is not a bug.  Please read the JavaDoc for `setSigningKey` when using a String key argument.

If your string is not base64-encoded, that is a 'yellow flag' that you might very well be using a weak/poor key that could compromise security.  

For shared-secret algorithms, you should always use a secure-random byte-array that is long enough for the chosen algorithm.  If you want to represent that byte array as a String, then you would probably base64-encode it.  Plaintext strings like "secret" and "hello" are poorly formed strings and do not have the required entropy for HMAC-SHA-2* variant algorithms.

Look at JJWT's `MacProvider` `generateKey`* method variants to generate a key that is guaranteed to be secure enough for your chosen algorithm.  Once you get a key that is strong enough, you can base64-encode it if you wish:

```java
SecretKey key = MacProvider.generateKey();
byte[] keyBytes = key.getEncoded();
String base64Encoded = TextCodec.BASE64.encode(keyBytes);
```
