### ISSUE TITLE
[Question] Is there a plan to release new version for jjwt?

### ISSUE THREAD

**Issue by hollomyfoolish** [jwtk/jjwt#804]
The latest version of jjwt-v0.11.5 was release more than 1 year ago, is there a plan to release new version? Thanks.

**Comment by joca-bt** [comment]
Also wondering this, since the documentation now mentions features not available in the last release (e.g. `content()`).

**Comment by lhazlewood** [comment]
Yep!  I'm doing everything in my power to release 0.12.0 this week.

> since the documentation now mentions features not available

That was my mistake - I should have merged everything into a staging branch before cutting the release. 😅

**Comment by hollomyfoolish** [comment]
@lhazlewood  Do you mean 0.12.0 will be released soon? Thanks.

**Comment by lhazlewood** [comment]
@hollomyfoolish 'soon' is relative, but yes, I'm trying to finish up things as fast as I can (as a volunteer) to make the release.

**Comment by hollomyfoolish** [comment]
@lhazlewood got it, thanks for your answer.

**Comment by lhazlewood** [comment]
0.12.0 has been released: https://github.com/jwtk/jjwt/discussions/848
