### ISSUE TITLE
NBF claim date exception

### ISSUE THREAD

**Issue by t2r** [jwtk/jjwt#81]
The Not_BEFORE claims date is not handled the same between Claims vs Map<String, Object>.  If you set the Not_BEFORE claims, like so:

claims.put(Claims.NOT_BEFORE, org.joda.time.DateTime.now.toDate());

Client attempts to parse it:  
io.jsonwebtoken.PrematureJwtException: JWT must not be accepted before 47988-06-20T02:48:33-0400. Current time: 2016-01-07T16:36:26-0500
    at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:384)
    at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:458)
    at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:518)

vs.

claims.setNotBefore(org.joda.time.DateTime.now.toDate());

Client parses it successfully:
Jwts.parser().setSigningKey(key).parseClaimsJws(token).getBody() --> {... nbf=1452203265 ... }

Yes, low priority, especially with the convenience methods that work around this issue.  However, I believe functionality should be identical between Map<String, Object> and Claims for the setClaims() method (and it may be that NBF is a special case).  Unless I'm missing the intended usage of Map<String, Object> for setClaims()?

**Comment by jaschenk** [comment]
Running into this issue.  Currently using the work around to set nbf via setter instead of claims map.

Any idea when this will be fixed?

Thanks,
Jeff

**Comment by lhazlewood** [comment]
Closing as this was resolved in the 0.10.0 release.
