### ISSUE TITLE
API signature enhancement for JwtBuilder.setClaims

### ISSUE THREAD

**Issue by matthewjosephtaylor** [jwtk/jjwt#84]
Currently:

```
JwtBuilder setClaims(Map<String, Object> claims);

```

Would be nice if this looked like:

```
JwtBuilder setClaims(Map<String, ? extends Object> claims);

```

This would allow one to pass a Maps of type `Map<String,String>`, etc into this method without needing to cast.

**Comment by lhazlewood** [comment]
I can't believed we missed this.  This definitely should be the case - thanks for the issue!

**Comment by longtimeago** [comment]
let me fix this, should be quick
