### ISSUE TITLE
Incompatible with auth0 java-jwt

### ISSUE THREAD

**Issue by chadjaros** [jwtk/jjwt#87]
I tried to create a token with each library, and then verify the token with the opposite library. Since both are implementing a "standard", the libraries should be able to verify signatures created by other libraries. This was not the case in either direction.

**Comment by lhazlewood** [comment]
Did you create a ticket w/ Auth0?  If so, can you please link it here?

Also, what is your test case - can you please share it?

Our code coverage is ~ 100% and tests are constructed based on actual test cases defined in the JWT RFC, so without any more information, there's not much we can do.

**Comment by lhazlewood** [comment]
Also, I created a signed JWT in JJWT and put it in auth0's jwt.io tool - it was validated and verified the signature correctly.  So it looks like their JavaScript verifier works but their Java one does not?

**Comment by chadjaros** [comment]
This is code from a scala worksheet:

```
val secret = "abcdefghij"

val jjwt = Jwts.builder
  .setSubject("1")
  .claim("authType", "password")
  .signWith(SignatureAlgorithm.HS256, secret)
  .compact()

val signer = new JWTSigner(secret)
val map = Map[String, AnyRef](
    "authType" -> "password",
    "sub" -> "1"
)
val auth0 = signer.sign(JavaConversions.mapAsJavaMap(map))

val auth0Verifier = new JWTVerifier(secret)

auth0Verifier.verify(jjwt) // fail
auth0Verifier.verify(auth0) // success

val jjwtVerifier = Jwts.parser
              .setSigningKey(secret)

jjwtVerifier.parseClaimsJws(jjwt) // success
jjwtVerifier.parseClaimsJws(auth0) // fail
```

It seems the problem was that I was failing to base64 encode the secret for the jjwt library. Once I did that, they worked together.

**Comment by chadjaros** [comment]
So it turns out that it was user error, rather than a real issue

**Comment by lhazlewood** [comment]
Closing as user error.
