### ISSUE TITLE
Typo in changelog

### ISSUE THREAD

**Issue by jimshowalter** [jwtk/jjwt#881]
https://github.com/jwtk/jjwt/blob/0.12.0/CHANGELOG.md

io.jsonwebtoken.InvalidClaimException and it's two subclasses (IncorrectClaimException and MissingClaimException) were previously mutable

it's should be its

**Comment by lhazlewood** [comment]
Thank you for finding this for us :). Would you like to issue a pull request with the proposed change? We can merge that quickly.
