### ISSUE TITLE
Using SetClaims(Map<String, Object>) makes the NotBefore and Expiration dates being multiplied by 1000

### ISSUE THREAD

**Issue by mad0gre** [jwtk/jjwt#89]
Hello,

I believe that the problem is on the JwtMap class.

The setDate(String, Date) method divides the date by 1000 (to store the date in seconds), and the getDate(String) method multiplies the dates by the same factor. 

However, the JwtMap constructor that receives a Map makes no such check for dates, therefore dates will be stored in millis and multiplied by 1000 when the getDate(String) method is used.

As a result, in many cases, it causes the parser to throw PrematureJwtException with valid NotBefore dates, or to miss throwing ExpiredJwtException with expired dates. Obviously, as a workaround, I ended up using the setIssuedAt(Date), setNotBefore(Date) and setExpiration(Date) methods of the JwtBuilder and it worked like a charm.

It's the first time I ever reported a bug on github, so i'd like to apologize if I'm not aware of github etiquette to do so. For that same reason I didn't offer to send a patch or whatever.

Thanks,
Victor

**Comment by samuelrey** [comment]
Bump. Found myself experiencing this same issue.
Like you said, this can be avoided by using the setters of the JwtBuilder class. For the sake of consistency, it may be worth considering deprecating the setClaims(...) method.

**Comment by davideas** [comment]
I was testing the fields in my Object to check if I set correctly all my data, of course dates have milliseconds, but on verification step, the parsed token returns dates without milliseconds.
So, I went to check why my test was failing, and found this when setting dates before generating the token:
``` java
// JwtMap.java
protected void setDate(String name, Date d) {
    if (d == null) {
        map.remove(name);
    } else {
        long seconds = d.getTime() / 1000;
        map.put(name, seconds);
    }
}
```
Why we save seconds and not milliseconds?
That division deletes all the milliseconds and test **fails**! :confused:

I received this answer from Auth0 project, so I guess this is on purpose also here:
> dates in JWT are expressed in "NumericDate" format, aka unix/epoch (seconds). https://tools.ietf.org/html/rfc7519#section-2.

@samuelrey, using JwtBuilder doesn't resolve it, it still divides by 1000 all dates.

**Comment by avoidwork** [comment]
Hi,

This issue creates a pretty significant interoperability problem with JWTs from other libraries (not java) that are using the correct resolution of time. My valid tokens from a node.js app are being marked as expired by this lib because this lib is expecting numbers 1000x larger.

**Comment by lhazlewood** [comment]
All JWT RFC timestamps claim fields (nbf, exp, etc) *must* be in seconds, *not* milliseconds.  Any other JWT library that allows otherwise for the RFC standard fields are violating the JWT specification.

That said, bulk setting via `setClaims` or `addClaims` will be cleaned up soon via #304.  Closing this issue and will track remaining work via #304.  Please use that issue for updates and/or discussion.  Thanks!
