### ISSUE TITLE
Add Maven BOM

### ISSUE THREAD

**Issue by sigpwned** [jwtk/jjwt#967]
**Is your feature request related to a problem? Please describe.**

Keeping Maven dependency versions consistent is hard.

**Describe the solution you'd like**

I would like a BOM published to Maven central.

**Describe alternatives you've considered**

Users of the library can keep their Maven dependency versions consistent properties.

**Additional context**

Maven BOMs have become a popular method for multi-module library projects to help users keep their dependencies up to date. Many popular libraries publish a BOM, such as [guava](https://central.sonatype.com/artifact/com.google.guava/guava-bom/versions).

**Comment by lhazlewood** [comment]
I'm honestly surprised we haven't had this yet! Thank you for creating the issue!

**Comment by lzysuqianqiu** [comment]
when to release?
