### ISSUE TITLE
Unable to load class named [io.jsonwebtoken.impl.DefaultJwtBuilder] 

### ISSUE THREAD

**Issue by ALittleHammer2** [jwtk/jjwt#973]
version:0.12.6
maven:
![image](https://github.com/user-attachments/assets/bb293525-78b2-4fc0-b1de-c3450dfa1bcd)
![image](https://github.com/user-attachments/assets/bc7e328d-5c48-48d7-8654-e3730e006e2f)
when i log in:
![image](https://github.com/user-attachments/assets/ae676fad-8991-4283-9036-a0bab1a06a2e)
![image](https://github.com/user-attachments/assets/e2eb4b63-1157-4568-826e-745128b78361)
method createToken:
![image](https://github.com/user-attachments/assets/97968c7a-f499-4048-a207-712bac581496)

**Comment by bdemers** [comment]
Thanks for reporting this issue @ALittleHammer2

These types of issues are hard to track down without information about how your application is packaged (and potentially deployed).  For example, if you are building a shaded/shadow jar, or if you deploy your application's dependencies across multiple classloaders (e.g. if parts of JJWT were loaded in different classloaders)

Can you provide a simple application that can reproduce this issue?? (or possibly describe how you are packaging/deploying your application)?

**Comment by ALittleHammer2** [comment]
**This happened when I used IDEA to launch the service directly
My project structure and there is only one service in 'admin' module:**
![image](https://github.com/user-attachments/assets/7b3fb47e-a8a2-404b-ac14-38b75627eb7a)
**All the modules below depend on the top total module, then the second layer is the framwork module, the third layer is the common module, most of the other modules depend on commons, the fifth layer is the admin module, all the controllers are in the admin module**
![1729558380157](https://github.com/user-attachments/assets/b6a073a7-0f98-45fe-91a0-3ce3728bd190)
**Here are some of my maven dependencies:**
spring boot version is 3.3.4
![image](https://github.com/user-attachments/assets/a69915a4-6adf-453c-8d3a-95bcd223ad0a)

**Comment by ALittleHammer2** [comment]
i should import jar in 'common'/pom.xml when i did it worked
